package com.traillink;

import java.util.*;

/** Pure-Java rules. Only the host owns this state; peers receive filtered views. */
public final class Game implements java.io.Serializable, Cloneable {
 private static final long serialVersionUID=3L;
 public static final String[] NAMES={"Chess","Stratego","Checkers","Reversi","Connect Four","Tic-Tac-Toe","Gomoku","Battleship","Dots & Boxes","Mancala","Nine Men's Morris","Nim","Memory Pairs","Go","Dice Duel","Rift Command"};
 public static final String[] TAGS={"The timeless strategy classic","Hidden ranks. Capture the flag.","Jump, capture, become a king","Flip the board in your favor","One more move. Four in a row.","A tiny board. A quick rivalry.","Find your line of five","Find and sink the hidden fleet","Close a box. Take another turn.","Sow stones. Collect the most.","Make mills and outmaneuver","Leave your rival the last decision","Remember more. Match more.","Surround territory. Shape the board.","Push your luck. Race to 50.","Build a base. Command an army."};
 public static final String[] RULES={
 "White moves first. Tap a piece, then a highlighted destination. Check, checkmate, stalemate, castling, en passant and promotion are supported. Choose promotion in the dialog. Automatic draws: three repetitions, 100 half-moves, or insufficient material.",
 "Classic 10×10 Stratego: arrange 40 pieces in your four home rows by tapping two pieces to swap them, then Ready. Army: 1 marshal (10), 1 general (9), 2 colonels (8), 3 majors (7), 4 captains (6), 4 lieutenants (5), 4 sergeants (4), 5 miners (3), 8 scouts (2), 1 spy (S), 6 bombs (B), 1 flag (F). Higher rank wins; equal ranks remove both. An attacking spy beats the marshal; miners defuse bombs. Scouts move and attack any clear orthogonal distance. Other moving pieces take one orthogonal step. Lakes cannot be crossed; bombs and flags cannot move. Capture the flag or immobilize the enemy to win. A fourth consecutive traversal of the same two squares is prohibited. Revealed ranks are remembered. Casual-play draw: three repeated positions or 200 non-capturing moves; tournament perpetual-chase adjudication is not implemented.",
 "American-style checkers. Dark squares only. Men move and capture forward; kings go both ways. Captures are mandatory and multiple jumps must continue. Reaching the far row crowns a king and ends the turn. No legal moves loses. 80 quiet plies draws.",
 "Place a disc so a straight line of opposing discs is bracketed by yours. All bracketed discs flip. If you have no move your turn passes automatically. When neither player can move, most discs wins.",
 "Tap a column to drop a disc. Connect four horizontally, vertically or diagonally. A full board with no line is a draw.",
 "Take turns placing a mark. Three in a row horizontally, vertically or diagonally wins. If the board fills, it is a draw.",
 "Freestyle gomoku on 11×11. Take turns placing stones. A line of five or more in any direction wins.",
 "Two 10×10 seas. Place your carrier (5), battleship (4), cruiser (3), submarine (3), and destroyer (2). Select a ship, choose horizontal or vertical, and tap its starting square. You can reposition a ship until Ready. No overlap or off-board placement. Ships may touch. Once both fleets are ready, tap the enemy sea to fire. Hit or miss, turns alternate. Sink all 17 enemy ship squares to win. Switch between Target sea and My fleet using the tabs. Placement stays on this phone until Ready.",
 "Tap an empty edge between dots. Complete a box to claim it and play again. When all 16 boxes are claimed, the higher score wins.",
 "Kalah: six pits per player, four stones per pit. Player 1 owns the bottom row, player 2 the top. Sow counterclockwise, skipping the enemy store. Ending in your store earns another turn. Ending in your empty pit captures opposite stones if any. Emptying either side ends play and remaining stones go to their owner.",
 "Place nine stones each, then move along connected lines. Form a three-stone mill to remove an enemy stone (outside a mill if possible). With only three stones, fly anywhere. Fewer than three stones or no move loses after placement. 100 turns without a capture draws.",
 "There are piles of 3, 5 and 7 stones. On your turn choose a pile, then choose how many to remove. Take at least one. Whoever takes the last stone wins (normal-play Nim).",
 "Find matching symbols on a 4×4 board. Turn over two cards. A match scores a point and gives you another turn. An unmatched pair remains visible until Next turn is pressed. Most pairs wins.",
 "Go on 9×9. Black starts; colors are randomly assigned. Place on an empty intersection. Surround an enemy group to capture it. Suicide and repeating any previous board position (positional superko) are forbidden. Pass twice to enter scoring. Tap groups to mark or unmark agreed dead stones; both players accept, or either resumes play. Chinese-style area scoring counts living stones plus surrounded empty intersections; White receives 7.5 komi. Marking changes cancel both approvals. Bots accept your dead-stone markings. Captures are shown for information, not added again to area score.",
 "Pig dice: roll to add 2–6 to your turn total. Rolling 1 loses the unbanked total and ends your turn. Hold banks your turn total and passes. The first player to bank 50 wins. Dice are generated on the host.",
 "Real-time sci-fi skirmish. Gather ore and gas, build production structures and supply relays, research upgrades, and command ground and air armies. Destroy all enemy structures. Landscape touch controls: select units, issue orders, pan/pinch the battlefield, and jump with the minimap. Bots or two Bluetooth phones; no pass-and-play. Both commanders must remain in battle. Read the Field manual in the battle HUD."};
 public int lastA=-1,lastZ=-1,lastPlayer=-1;public String lastMove="";public int[] beforeMove=new int[0],changed=new int[0],sowPath=new int[0];public HashSet<String> goPositions=new HashSet<>();
 public RiftWar rts;
 public int id,n,turn=0,winner=-1,seq=0,phase=0,selected=-1,chain=-1,ep=-1,rights=15,quiet=0;
 public int[] b=new int[200],aux=new int[200],score={0,0},count={0,0};
 public boolean setup=false; public boolean[] prepared={false,false};
 public int[] lastFrom={-1,-1},lastTo={-1,-1},shuttles={0,0};
 public ArrayList<int[]> history=new ArrayList<>(),chessStates=new ArrayList<>(),chessMoves=new ArrayList<>(),analysisBest=new ArrayList<>();public ArrayList<String> commentary=new ArrayList<>(),analysis=new ArrayList<>();
 public static final int[] FLEET={5,4,3,3,2};
 public String note="",word=""; public long guessed=0; public Random rng; public HashMap<String,Integer> repetition=new HashMap<>();
 public static final int[][] MILLS={{0,1,2},{3,4,5},{6,7,8},{9,10,11},{12,13,14},{15,16,17},{18,19,20},{21,22,23},{0,9,21},{3,10,18},{6,11,15},{1,4,7},{16,19,22},{8,12,17},{5,13,20},{2,14,23}};
 public static final int[][] LINKS={{1,9},{0,2,4},{1,14},{4,10},{1,3,5,7},{4,13},{7,11},{4,6,8},{7,12},{0,10,21},{3,9,11,18},{6,10,15},{8,13,17},{5,12,14,20},{2,13,23},{11,16},{15,17,19},{12,16},{10,19},{16,18,20,22},{13,19},{9,22},{19,21,23},{14,22}};
 public Game(int kind,long seed){id=kind;rng=new Random(seed);n=kind==13?9:kind==6?11:kind==4?7:kind==5?3:kind==1||kind==7?10:kind==12?4:8;
  switch(id){
   case 15:rts=new RiftWar(seed,0,0);break;
   case 0: int[] back={4,2,3,5,6,3,2,4};for(int i=0;i<8;i++){b[i]=-back[i];b[8+i]=-1;b[48+i]=1;b[56+i]=back[i];}remember();chessStates.add(new int[]{turn,ep,rights,quiet});history.add(Arrays.copyOf(b,64));commentary.add("Starting position. White moves first; colors are randomly assigned.");break;
   case 1:setup=true;for(int p=0;p<2;p++)randomSetup(p);break;
   case 2:for(int i=0;i<64;i++)if((i/8+i%8)%2==1){if(i<24)b[i]=-1;if(i>=40)b[i]=1;}break;
   case 3:b[27]=-1;b[28]=1;b[35]=1;b[36]=-1;break;
   case 7:setup=true;break;
   case 9:for(int i=0;i<14;i++)if(i!=6&&i!=13)b[i]=4;break;
   case 11:b[0]=3;b[1]=5;b[2]=7;break;
   case 12:ArrayList<Integer> deck=new ArrayList<>();for(int i=1;i<=8;i++){deck.add(i);deck.add(i);}Collections.shuffle(deck,rng);for(int i=0;i<16;i++)b[i]=deck.get(i);break;
   case 13:goPositions.add(goKey(b));break;
  }
 }
 public int owner(int piece){return piece>0?0:piece<0?1:-1;}
 public int sign(){return turn==0?1:-1;}
 public boolean in(int a,int max){return a>=0&&a<max;}
 public boolean move(int player,int a,int z,int choice){if(player<0||player>1||winner!=-1)return false;if(setup)return setupMove(player,a,z,choice);if(id==13&&phase==1)return goScoring(player,a);if(player!=turn)return false;boolean ok=false;int[] previousBoard=b.clone();int previousPhase=phase;String previousNote=note;String san=id==0?ChessNotation.san(this,a,z,choice):"";note="";
  switch(id){case 0:ok=chess(a,z,choice);break;case 1:ok=tactico(a,z);break;case 2:ok=checkers(a,z);break;case 3:ok=reversi(a);break;
   case 4:if(in(a,7)){for(int r=5;r>=0;r--)if(b[r*7+a]==0){a=r*7+a;ok=placeLine(a,42,7,4);break;}}break;
   case 5:ok=placeLine(a,9,3,3);break;case 6:ok=placeLine(a,121,11,5);break;
   case 7:if(in(a,100)&&aux[(1-turn)*100+a]==0){int t=(1-turn)*100+a,ship=b[t];aux[t]=ship>0?2:1;if(ship>0)score[turn]++;note=ship>0?"Hit!":"Miss";if(ship>0){boolean sunk=true;for(int i=(1-turn)*100;i<(2-turn)*100;i++)if(b[i]==ship&&aux[i]!=2)sunk=false;if(sunk)note="Sunk the "+new String[]{"","carrier","battleship","cruiser","submarine","destroyer"}[ship]+"!";}if(score[turn]==17)winner=turn;turn=1-turn;ok=true;}break;
   case 8:ok=dots(a);break;case 9:ok=mancala(a);break;case 10:ok=morris(a,z);break;
   case 11:if(in(a,3)&&z>0&&z<=b[a]){b[a]-=z;if(b[0]+b[1]+b[2]==0)winner=turn;turn=1-turn;ok=true;}break;
   case 12:ok=memory(a);break;
   case 13:ok=go(a);break;
   case 14:if(a==0){int die=rng.nextInt(6)+1;count[0]=die;if(die==1){phase=0;turn=1-turn;note="Rolled 1 — turn total lost";}else phase+=die;ok=true;}else if(a==1&&phase>0){score[turn]+=phase;phase=0;if(score[turn]>=50)winner=turn;turn=1-turn;ok=true;}break;
  }if(ok){seq++;lastA=a;lastZ=z;lastPlayer=player;beforeMove=id==9?previousBoard:new int[0];ArrayList<Integer> delta=new ArrayList<>();for(int i=0;i<b.length;i++)if(previousBoard[i]!=b[i])delta.add(i);changed=new int[delta.size()];for(int i=0;i<delta.size();i++)changed[i]=delta.get(i);lastMove=describeMove(player,a,z,choice,san,previousPhase,previousBoard);}else note=previousNote;return ok;
 }
 void result(){winner=score[0]==score[1]?2:score[0]>score[1]?0:1;}
 boolean placeLine(int a,int max,int width,int need){if(!in(a,max)||b[a]!=0)return false;b[a]=sign();for(int[] d:new int[][]{{0,1},{1,0},{1,1},{1,-1}}){int total=1;for(int s:new int[]{-1,1})for(int k=1;k<need;k++){int r=a/width+d[0]*k*s,c=a%width+d[1]*k*s;if(r<0||c<0||c>=width||r*width+c>=max||b[r*width+c]!=sign())break;total++;}if(total>=need)winner=turn;}if(winner==-1){boolean full=true;for(int i=0;i<max;i++)if(b[i]==0)full=false;if(full)winner=2;}turn=1-turn;return true;}
 public static boolean lake(int a){return a/10>=4&&a/10<=5&&(a%10==2||a%10==3||a%10==6||a%10==7);}
 boolean tacticoLegal(int a,int z,int p){if(!in(a,100)||!in(z,100)||a==z||lake(z)||owner(b[a])!=p||owner(b[z])==p||Math.abs(b[a])>10)return false;int dr=z/10-a/10,dc=z%10-a%10;if(dr!=0&&dc!=0)return false;if(shuttles[p]>=3&&a==lastTo[p]&&z==lastFrom[p])return false;if(Math.abs(dr)+Math.abs(dc)>1&&Math.abs(b[a])!=2)return false;int step=dr==0?Integer.signum(dc):Integer.signum(dr)*10;for(int i=a+step;i!=z;i+=step)if(lake(i)||b[i]!=0)return false;return true;}
 boolean tactico(int a,int z){if(!tacticoLegal(a,z,turn))return false;int atk=Math.abs(b[a]),def=Math.abs(b[z]);shuttles[turn]=a==lastTo[turn]&&z==lastFrom[turn]?shuttles[turn]+1:1;lastFrom[turn]=a;lastTo[turn]=z;quiet=def==0?quiet+1:0;if(def==0){b[z]=b[a];aux[z]=Math.abs(a-z)>10||a/10==z/10&&Math.abs(a-z)>1?1:aux[a];}else{note="Rank "+atk+" attacked "+(def==12?"flag":def==11?"bomb":def);int outcome=def==12?1:def==11?(atk==3?1:-1):atk==1&&def==10?1:Integer.compare(atk,def);if(def==12)winner=turn;if(outcome>0){b[z]=b[a];aux[z]=1;}else if(outcome==0){b[z]=0;aux[z]=0;}else aux[z]=1;}b[a]=0;aux[a]=0;turn=1-turn;boolean can=false;for(int i=0;i<100&&!can;i++)for(int j=0;j<100&&!can;j++)if(tacticoLegal(i,j,turn))can=true;if(!can&&winner==-1)winner=1-turn;if(winner==-1&&(quiet>=200||remember()>=3))winner=2;return true;}
 boolean homeSquare(int player,int a){return in(a,100)&&(player==0?a>=60:a<40);}
 public boolean placeShip(int player,int a,int step,int ship){if(!in(player,2)||!in(a,100)||!in(ship,5)||(step!=1&&step!=10))return false;int len=FLEET[ship],base=player*100;if(step==1&&a%10+len>10||step==10&&a/10+len>10)return false;for(int j=0;j<len;j++)if(b[base+a+j*step]!=0&&b[base+a+j*step]!=ship+1)return false;for(int i=base;i<base+100;i++)if(b[i]==ship+1)b[i]=0;for(int j=0;j<len;j++)b[base+a+j*step]=ship+1;return true;}
 public void randomSetup(int player){if(!setup||prepared[player])return;if(id==1){ArrayList<Integer> army=new ArrayList<>();int[] counts={0,1,8,5,4,4,4,3,2,1,1,6,1};for(int rank=1;rank<=12;rank++)for(int j=0;j<counts[rank];j++)army.add(rank);Collections.shuffle(army,rng);for(int i=0;i<40;i++)b[(player==0?60:0)+i]=(player==0?1:-1)*army.get(i);}else if(id==7){Arrays.fill(b,player*100,(player+1)*100,0);for(int ship=0;ship<5;ship++)while(!placeShip(player,rng.nextInt(100),rng.nextBoolean()?1:10,ship)){} }}
 public boolean setupComplete(int player){if(id==1)return true;for(int s=0;s<5;s++){int cells=0;for(int i=player*100;i<(player+1)*100;i++)if(b[i]==s+1)cells++;if(cells!=FLEET[s])return false;}return true;}
 boolean setupMove(int player,int a,int z,int choice){if(prepared[player])return false;boolean ok=false;if(a==-10){if(!setupComplete(player))return false;prepared[player]=true;if(prepared[0]&&prepared[1]){setup=false;note="Both players ready. Player "+(turn+1)+" starts.";if(id==1)remember();}ok=true;}else if(a==-11){randomSetup(player);ok=true;}else if(id==1&&homeSquare(player,a)&&homeSquare(player,z)){int v=b[a];b[a]=b[z];b[z]=v;ok=true;}else if(id==7)ok=placeShip(player,a,z,choice);if(ok)seq++;return ok;}
 public Game copy(){try{Game c=(Game)super.clone();c.b=b.clone();c.aux=aux.clone();c.score=score.clone();c.count=count.clone();c.prepared=prepared.clone();c.lastFrom=lastFrom.clone();c.lastTo=lastTo.clone();c.shuttles=shuttles.clone();c.repetition=new HashMap<>(repetition);c.history=new ArrayList<>(history);c.commentary=new ArrayList<>(commentary);c.chessStates=new ArrayList<>(chessStates);c.chessMoves=new ArrayList<>(chessMoves);c.analysis=new ArrayList<>(analysis);c.analysisBest=new ArrayList<>(analysisBest);c.goPositions=new HashSet<>(goPositions);c.beforeMove=beforeMove.clone();c.changed=changed.clone();c.sowPath=sowPath.clone();c.rng=new Random(0);return c;}catch(CloneNotSupportedException e){throw new AssertionError(e);}}
 boolean checkerLegal(int a,int z,boolean jump){if(!in(a,64)||!in(z,64)||owner(b[a])!=turn||b[z]!=0)return false;int dr=z/8-a/8,dc=z%8-a%8,dist=jump?2:1;if(Math.abs(dr)!=dist||Math.abs(dc)!=dist)return false;if(Math.abs(b[a])==1&&Integer.signum(dr)!=(turn==0?-1:1))return false;return !jump||owner(b[(a/8+dr/2)*8+a%8+dc/2])==1-turn;}
 boolean anyJump(){for(int a=0;a<64;a++)if(chain<0||chain==a)for(int z=0;z<64;z++)if(checkerLegal(a,z,true))return true;return false;}
 boolean checkers(int a,int z){boolean jump=checkerLegal(a,z,true);if(chain>=0&&a!=chain)return false;if(!jump&&(anyJump()||!checkerLegal(a,z,false)))return false;int piece=b[a];b[z]=piece;b[a]=0;if(jump)b[(a/8+z/8)/2*8+(a%8+z%8)/2]=0;boolean crowned=Math.abs(piece)==1&&(z/8==0||z/8==7);if(crowned)b[z]=sign()*2;quiet=jump||crowned?0:quiet+1;chain=-1;if(jump&&!crowned){chain=z;if(anyJump())return true;chain=-1;}turn=1-turn;boolean can=false;for(int i=0;i<64;i++)for(int j=0;j<64;j++)if(checkerLegal(i,j,false)||checkerLegal(i,j,true))can=true;if(!can)winner=1-turn;else if(quiet>=80)winner=2;return true;}
 ArrayList<Integer> flips(int a,int p){ArrayList<Integer> out=new ArrayList<>();if(!in(a,64)||b[a]!=0)return out;int s=p==0?1:-1;for(int dr=-1;dr<=1;dr++)for(int dc=-1;dc<=1;dc++){if(dr==0&&dc==0)continue;ArrayList<Integer> line=new ArrayList<>();int r=a/8+dr,c=a%8+dc;while(r>=0&&r<8&&c>=0&&c<8&&b[r*8+c]==-s){line.add(r*8+c);r+=dr;c+=dc;}if(r>=0&&r<8&&c>=0&&c<8&&b[r*8+c]==s)out.addAll(line);}return out;}
 boolean reversi(int a){ArrayList<Integer> list=flips(a,turn);if(list.isEmpty())return false;b[a]=sign();for(int i:list)b[i]=sign();turn=1-turn;boolean can=false;for(int i=0;i<64;i++)if(!flips(i,turn).isEmpty())can=true;if(!can){turn=1-turn;note="No legal move — opponent passes";for(int i=0;i<64;i++)if(!flips(i,turn).isEmpty())can=true;if(!can){score[0]=score[1]=0;for(int i=0;i<64;i++)if(b[i]!=0)score[owner(b[i])]++;result();}}return true;}
 boolean dots(int a){if(!in(a,40)||b[a]!=0)return false;b[a]=turn+1;int gained=0;for(int r=0;r<4;r++)for(int c=0;c<4;c++){int box=r*4+c;if(aux[box]==0&&b[r*4+c]!=0&&b[(r+1)*4+c]!=0&&b[20+r*5+c]!=0&&b[20+r*5+c+1]!=0){aux[box]=turn+1;score[turn]++;gained++;}}if(score[0]+score[1]==16)result();if(gained==0)turn=1-turn;return true;}
 boolean mancala(int a){if(!in(a,14)||a==6||a==13||b[a]==0||(turn==0?!(a<6):!(a>6&&a<13)))return false;int stones=b[a];ArrayList<Integer> path=new ArrayList<>();b[a]=0;int k=a;while(stones>0){k=(k+1)%14;if(k==(turn==0?13:6))continue;b[k]++;path.add(k);stones--;}sowPath=new int[path.size()];for(int i=0;i<path.size();i++)sowPath[i]=path.get(i);if(k!=(turn==0?6:13)&&b[k]==1&&(turn==0?k<6:k>6&&k<13)&&b[12-k]>0){b[turn==0?6:13]+=b[12-k]+1;b[k]=b[12-k]=0;}boolean empty0=true,empty1=true;for(int i=0;i<6;i++){if(b[i]>0)empty0=false;if(b[i+7]>0)empty1=false;}if(empty0||empty1){for(int i=0;i<6;i++){b[6]+=b[i];b[13]+=b[i+7];b[i]=b[i+7]=0;}score[0]=b[6];score[1]=b[13];result();}if(k!=(turn==0?6:13))turn=1-turn;return true;}
 boolean mill(int a){for(int[] m:MILLS)if((m[0]==a||m[1]==a||m[2]==a)&&b[a]!=0&&b[m[0]]==b[a]&&b[m[1]]==b[a]&&b[m[2]]==b[a])return true;return false;}
 int pieces(int p){int total=0;for(int i=0;i<24;i++)if(owner(b[i])==p)total++;return total;}
 boolean adjacent(int a,int z){for(int v:LINKS[a])if(v==z)return true;return false;}
 void endMorris(){turn=1-turn;quiet++;if(count[0]>=9&&count[1]>=9){int num=pieces(turn);if(num<3)winner=1-turn;else if(num>3){boolean can=false;for(int i=0;i<24;i++)if(owner(b[i])==turn)for(int z:LINKS[i])if(b[z]==0)can=true;if(!can)winner=1-turn;}if(quiet>=100&&winner==-1)winner=2;}}
 boolean morris(int a,int z){if(phase==1){if(!in(a,24)||owner(b[a])!=1-turn)return false;boolean outside=false;for(int i=0;i<24;i++)if(owner(b[i])==1-turn&&!mill(i))outside=true;if(outside&&mill(a))return false;b[a]=0;phase=0;quiet=0;endMorris();return true;}int target;
  if(count[turn]<9){if(!in(a,24)||b[a]!=0)return false;target=a;b[a]=sign();count[turn]++;}else{if(!in(a,24)||!in(z,24)||owner(b[a])!=turn||b[z]!=0||(pieces(turn)>3&&!adjacent(a,z)))return false;target=z;b[z]=b[a];b[a]=0;}if(mill(target)&&pieces(1-turn)>0){phase=1;note="Mill! Remove an opponent stone";}else endMorris();return true;}
 boolean memory(int a){if(phase==2){if(a!=-2)return false;aux[selected]=aux[chain]=0;selected=chain=-1;phase=0;turn=1-turn;return true;}if(!in(a,16)||aux[a]!=0)return false;aux[a]=1;if(phase==0){selected=a;phase=1;}else{chain=a;if(b[selected]==b[a]){aux[selected]=aux[a]=turn+2;score[turn]++;selected=chain=-1;phase=0;if(score[0]+score[1]==8)result();}else phase=2;}return true;}
 // Chess: 1 pawn, 2 knight, 3 bishop, 4 rook, 5 queen, 6 king.
 boolean attacked(int sq,int by){for(int a=0;a<64;a++){if(owner(b[a])!=by)continue;int dr=sq/8-a/8,dc=sq%8-a%8,p=Math.abs(b[a]);if(p==1){if(dr==(by==0?-1:1)&&Math.abs(dc)==1)return true;}else if(p==2){if(Math.abs(dr)*Math.abs(dc)==2)return true;}else if(p==6){if(Math.max(Math.abs(dr),Math.abs(dc))==1)return true;}else if((p==3&&Math.abs(dr)==Math.abs(dc))||(p==4&&(dr==0||dc==0))||(p==5&&(dr==0||dc==0||Math.abs(dr)==Math.abs(dc)))){if(a==sq)continue;int r=a/8+Integer.signum(dr),c=a%8+Integer.signum(dc);boolean clear=true;while(r!=sq/8||c!=sq%8){if(b[r*8+c]!=0){clear=false;break;}r+=Integer.signum(dr);c+=Integer.signum(dc);}if(clear)return true;}}return false;}
 boolean check(int p){for(int i=0;i<64;i++)if(b[i]==(p==0?6:-6))return attacked(i,1-p);return true;}
 boolean chessPseudo(int a,int z){if(!in(a,64)||!in(z,64)||a==z||owner(b[a])!=turn||owner(b[z])==turn||Math.abs(b[z])==6)return false;int p=Math.abs(b[a]),dr=z/8-a/8,dc=z%8-a%8,dir=turn==0?-1:1;
  if(p==1)return dc==0&&b[z]==0&&(dr==dir||(a/8==(turn==0?6:1)&&dr==2*dir&&b[a+dir*8]==0))||Math.abs(dc)==1&&dr==dir&&(b[z]!=0||(z==ep&&b[z-dir*8]==-sign()));
  if(p==2)return Math.abs(dr)*Math.abs(dc)==2;
  if(p==6){if(Math.max(Math.abs(dr),Math.abs(dc))==1)return true;int base=turn==0?60:4;if(a!=base||dr!=0||Math.abs(dc)!=2||check(turn))return false;int bit=turn==0?(dc>0?1:2):(dc>0?4:8),rook=base+(dc>0?3:-4);if((rights&bit)==0||b[rook]!=sign()*4)return false;for(int q=a+Integer.signum(dc);q!=rook;q+=Integer.signum(dc))if(b[q]!=0)return false;return !attacked(a+Integer.signum(dc),1-turn)&&!attacked(z,1-turn);}
  if(!(p==3&&Math.abs(dr)==Math.abs(dc)||p==4&&(dr==0||dc==0)||p==5&&(dr==0||dc==0||Math.abs(dr)==Math.abs(dc))))return false;int r=a/8+Integer.signum(dr),c=a%8+Integer.signum(dc);while(r!=z/8||c!=z%8){if(b[r*8+c]!=0)return false;r+=Integer.signum(dr);c+=Integer.signum(dc);}return true;
 }
 void chessApply(int a,int z,int promote){int p=b[a],old=b[z],prevEp=ep;ep=-1;if(Math.abs(p)==1&&z==prevEp&&old==0&&a%8!=z%8)b[z+(turn==0?8:-8)]=0;b[z]=p;b[a]=0;if(Math.abs(p)==1){if(Math.abs(z-a)==16)ep=(z+a)/2;if(z/8==0||z/8==7)b[z]=sign()*promote;}if(Math.abs(p)==6){rights&=turn==0?12:3;if(Math.abs(z-a)==2){int rook=a+(z>a?3:-4);b[a+(z>a?1:-1)]=b[rook];b[rook]=0;}}for(int v:new int[]{a,z}){if(v==63)rights&=~1;if(v==56)rights&=~2;if(v==7)rights&=~4;if(v==0)rights&=~8;}quiet=Math.abs(p)==1||old!=0?0:quiet+1;}
 public boolean chessLegal(int a,int z){if(!chessPseudo(a,z))return false;int[] old=b.clone();int e=ep,r=rights,q=quiet;chessApply(a,z,5);boolean legal=!check(turn);b=old;ep=e;rights=r;quiet=q;return legal;}
 String position(){int effectiveEp=-1;if(ep>=0)for(int a=0;a<64;a++)if(owner(b[a])==turn&&Math.abs(b[a])==1&&a%8!=ep%8&&chessLegal(a,ep)){effectiveEp=ep;break;}return Arrays.toString(Arrays.copyOf(b,id==1?100:64))+":"+turn+":"+rights+":"+effectiveEp;}
 int remember(){String key=position();int times=repetition.containsKey(key)?repetition.get(key)+1:1;repetition.put(key,times);return times;}
 static String square(int a){return ""+(char)('a'+a%8)+(8-a/8);}
 static String pieceName(int v){return new String[]{"","pawn","knight","bishop","rook","queen","king"}[Math.abs(v)];}
 boolean chess(int a,int z,int promote){if(promote<2||promote>5)promote=5;if(!chessLegal(a,z))return false;int piece=b[a],capture=b[z];boolean enPassant=Math.abs(piece)==1&&a%8!=z%8&&capture==0;String description=(turn==0?"White":"Black")+" "+pieceName(piece)+" "+square(a)+" → "+square(z)+".";if(Math.abs(piece)==6&&Math.abs(z-a)==2)description+=(z>a?" Kingside":" Queenside")+" castling brings the rook into play.";if(capture!=0)description+=" Captures a "+pieceName(capture)+".";if(enPassant)description+=" Captures a pawn en passant.";if(Math.abs(piece)==1&&(z/8==0||z/8==7))description+=" Promotes to "+pieceName(promote)+".";chessApply(a,z,promote);turn=1-turn;boolean can=false;for(int i=0;i<64&&!can;i++)for(int j=0;j<64&&!can;j++)if(chessLegal(i,j))can=true;if(!can)winner=check(turn)?1-turn:2;else if(quiet>=100||remember()>=3||insufficient())winner=2;note=winner==-1&&check(turn)?"Check":"";if(check(turn))description+=winner>=0&&winner!=2?" Checkmate.":" Gives check; the king must be protected.";if(winner==2)description+=" Draw.";int material=0;int[] value={0,1,3,3,5,9,0};for(int i=0;i<64;i++)material+=Integer.signum(b[i])*value[Math.abs(b[i])];description+=" Material: "+(material==0?"equal":(material>0?"White":"Black")+" +"+Math.abs(material))+" (P=1, N/B=3, R=5, Q=9).";history.add(Arrays.copyOf(b,64));chessStates.add(new int[]{turn,ep,rights,quiet});chessMoves.add(new int[]{a,z,promote});commentary.add(description);return true;}
 boolean insufficient(){int minors=0,knights=0,bishopColor=-1;boolean same=true;for(int i=0;i<64;i++){int p=Math.abs(b[i]);if(p==1||p==4||p==5)return false;if(p==2){minors++;knights++;}if(p==3){minors++;int c=(i/8+i%8)%2;if(bishopColor!=-1&&c!=bishopColor)same=false;bishopColor=c;}}return minors<=1||knights==0&&same;}

 public boolean applyFleet(int player,int[] layout){if(id!=7||!setup||prepared[player]||layout==null||layout.length!=100)return false;
  for(int v:layout)if(v<0||v>5)return false;
  for(int ship=1;ship<=5;ship++){ArrayList<Integer> cells=new ArrayList<>();for(int i=0;i<100;i++)if(layout[i]==ship)cells.add(i);if(cells.size()!=FLEET[ship-1])return false;int step=cells.get(1)-cells.get(0);if(step!=1&&step!=10)return false;for(int i=1;i<cells.size();i++)if(cells.get(i)!=cells.get(0)+i*step||step==1&&cells.get(i)/10!=cells.get(0)/10)return false;}
  System.arraycopy(layout,0,b,player*100,100);return move(player,-10,0,0);
 }
 String cellName(int a,int width){return a<0?"":""+(char)('A'+a%width)+(a/width+1);}
 String describeMove(int p,int a,int z,int choice,String san,int oldPhase,int[] previous){String who="P"+(p+1)+" · ";
  switch(id){case 0:return (p==0?"White":"Black")+" · "+san;case 1:case 2:return who+cellName(a,id==1?10:8)+" → "+cellName(z,id==1?10:8)+(note.isEmpty()?"":" · "+note);
   case 3:case 5:case 6:return who+cellName(a,n);case 4:return who+"column "+(a%7+1);case 7:return who+"fired "+cellName(a,10)+" · "+note;case 8:return who+"edge "+(a+1)+(score[p]>0?" · "+score[p]+" boxes":"");
   case 9:return who+"sowed "+previous[a]+" stones from pit "+(a<6?a+1:13-a);case 10:return who+(oldPhase==1?"removed "+(a+1):count[p]<=9&&previous[a]==0?"placed at "+(a+1):(a+1)+" → "+(z+1));
   case 11:return who+"took "+z+" from pile "+(a+1);case 12:return who+(a==-2?"closed unmatched pair":"flipped card "+(a+1));
   case 13:return (p==0?"Black":"White")+" · "+(a==-3?"Pass":goCoordinate(a))+(note.isEmpty()?"":" · "+note);
   case 14:return who+(a==0?"rolled "+count[0]:"banked points")+(note.isEmpty()?"":" · "+note);default:return who+"moved";}
 }
 public static String goCoordinate(int a){return ""+"ABCDEFGHJ".charAt(a%9)+(9-a/9);}
 static String goKey(int[] board){return Arrays.toString(Arrays.copyOf(board,81));}
 static int[] neighbors(int a){int[] all={a-9,a+9,a-1,a+1};return Arrays.stream(all).filter(t->t>=0&&t<81&&Math.abs(t/9-a/9)+Math.abs(t%9-a%9)==1).toArray();}
 static ArrayList<Integer> group(int[] board,int a){ArrayList<Integer> out=new ArrayList<>();boolean[] seen=new boolean[81];out.add(a);seen[a]=true;for(int k=0;k<out.size();k++)for(int t:neighbors(out.get(k)))if(!seen[t]&&board[t]==board[a]){seen[t]=true;out.add(t);}return out;}
 static int liberties(int[] board,ArrayList<Integer> group){boolean[] seen=new boolean[81];int n=0;for(int i:group)for(int t:neighbors(i))if(board[t]==0&&!seen[t]){seen[t]=true;n++;}return n;}
 int[] goBoard(int a){if(!in(a,81)||b[a]!=0)return null;int[] next=b.clone();next[a]=sign();for(int t:neighbors(a))if(next[t]==-sign()){ArrayList<Integer> g=group(next,t);if(liberties(next,g)==0)for(int i:g)next[i]=0;}if(liberties(next,group(next,a))==0||goPositions.contains(goKey(next)))return null;return next;}
 boolean go(int a){if(a==-3){quiet++;turn=1-turn;if(quiet>=2){phase=1;prepared[0]=prepared[1]=false;goScore();note="Mark dead groups, then both accept";}return true;}int[] next=goBoard(a);if(next==null)return false;int captures=0;for(int i=0;i<81;i++)if(b[i]==-sign()&&next[i]==0)captures++;count[turn]+=captures;b=next;goPositions.add(goKey(b));quiet=0;turn=1-turn;if(captures>0)note="Captured "+captures;return true;}
 boolean goScoring(int player,int a){if(a==-5){phase=0;quiet=0;Arrays.fill(aux,0);prepared[0]=prepared[1]=false;note="Play resumed";}else if(a==-4){prepared[player]=true;if(prepared[0]&&prepared[1]){goScore();result();note="Final area: Black "+score[0]/2.0+" · White "+score[1]/2.0;}}else if(in(a,81)&&b[a]!=0){int value=aux[a]==1?0:1;for(int i:group(b,a))aux[i]=value;prepared[0]=prepared[1]=false;goScore();note=value==1?"Group marked dead":"Group restored";}else return false;lastA=a;lastZ=-1;lastPlayer=player;lastMove="P"+(player+1)+" · "+(a==-4?"accepted score":a==-5?"resumed play":"updated dead groups");changed=new int[0];seq++;return true;}
 void goScore(){int[] board=b.clone();for(int i=0;i<81;i++)if(aux[i]==1)board[i]=0;score[0]=0;score[1]=15;boolean[] seen=new boolean[81];for(int i=0;i<81;i++){if(board[i]!=0){score[owner(board[i])]+=2;continue;}if(seen[i])continue;ArrayList<Integer> empty=group(board,i);int border=0;for(int q:empty){seen[q]=true;for(int t:neighbors(q))if(board[t]!=0)border|=board[t]>0?1:2;}if(border==1||border==2)score[border==1?0:1]+=empty.size()*2;}}
 public int[] view(int player){int[] out=b.clone();if(id==1){for(int i=0;i<100;i++)if(owner(b[i])==1-player&&aux[i]==0)out[i]=(player==0?-1:1)*13;}if(id==7){Arrays.fill(out,0);for(int i=0;i<100;i++){out[i]=setup?b[player*100+i]:aux[(1-player)*100+i];out[100+i]=aux[player*100+i]==2?3:b[player*100+i]>0?2:aux[player*100+i];}}if(id==12)for(int i=0;i<16;i++)if(aux[i]==0)out[i]=0;return out;}
 public String wordView(){StringBuilder s=new StringBuilder();for(char c:word.toCharArray())s.append(winner!=-1||(guessed&(1L<<(c-'A')))!=0?c:'_');return s.toString();}
 public ArrayList<int[]> legal(){ArrayList<int[]> out=new ArrayList<>();if(winner!=-1||setup)return out;
  if(id==0||id==1||id==2||(id==10&&phase==0&&count[turn]>=9)){int max=id==1?100:id==10?24:64;boolean forced=id==2&&anyJump();for(int a=0;a<max;a++)for(int z=0;z<max;z++){boolean ok=id==0?chessLegal(a,z):id==1?tacticoLegal(a,z,turn):id==2?(chain<0||chain==a)&&(checkerLegal(a,z,true)||!forced&&checkerLegal(a,z,false)):owner(b[a])==turn&&b[z]==0&&(pieces(turn)==3||adjacent(a,z));if(ok)out.add(new int[]{a,z});}return out;}
  int max=id==3?64:id==4?7:id==5?9:id==6?121:id==7?100:id==8?40:id==9?14:id==10?24:id==11?3:id==12?16:id==13?81:2;
  if(id==13){if(phase==1){for(int i=0;i<81;i++)if(b[i]!=0)out.add(new int[]{i,0});out.add(new int[]{-4,0});out.add(new int[]{-5,0});return out;}out.add(new int[]{-3,0});}
  if(id==12&&phase==2){out.add(new int[]{-2,0});return out;}
  for(int a=0;a<max;a++){boolean ok=false;switch(id){case 3:ok=!flips(a,turn).isEmpty();break;case 4:ok=b[a]==0;break;case 5:case 6:case 8:ok=b[a]==0;break;case 7:ok=aux[(1-turn)*100+a]==0;break;case 9:ok=b[a]>0&&(turn==0?a<6:a>6&&a<13);break;case 10:if(phase==0)ok=b[a]==0;else{boolean outside=false;for(int j=0;j<24;j++)if(owner(b[j])==1-turn&&!mill(j))outside=true;ok=owner(b[a])==1-turn&&(!outside||!mill(a));}break;case 11:for(int z=1;z<=b[a];z++)out.add(new int[]{a,z});break;case 12:ok=aux[a]==0;break;case 13:ok=goBoard(a)!=null;break;case 14:ok=a==0||phase>0;break;}if(ok)out.add(new int[]{a,0});}return out;
 }
}
