package com.traillink;

import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.bluetooth.*;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import org.json.*;import java.util.*;

public class MainActivity extends Activity implements BluetoothLink.Listener {
 static final int BG=0xfff4f0e7,INK=0xff21343d,GREEN=0xff286352,MUTED=0xff72796f,GOLD=0xffc29959;
 LinearLayout root,content;TextView connection,scanStatus;BluetoothAdapter adapter;BluetoothLink link;
 String status="Private by design • works without Internet",peer="",peerAddress="",session="",savedPeer="";
 boolean host=false,local=false,solo=false,ready=false,inGame=false,awaiting=false,destroyed=false;
 String thinkingSession="";
 Game game;JSONObject state;BoardView board;RiftView rtsView;boolean rtsVisible=false,rtsForeground=true,rtsPaused=false,rtsPeerActive=false,rtsLoopScheduled=false;int rtsMap=0,rtsDoctrine=0,rtsDialogVersion=0,rtsLastSave=-1;long rtsCommand=0;boolean passSwap=false;int devicePage=0,chatPage=0,animatedSeq=-1;String animatedSession="";final ArrayList<BluetoothDevice> foundDevices=new ArrayList<>();int libraryPage=0;boolean fleetTab=false;Game fleetDraft;String draftSession="";int draftPlayer=-1;Button fleetReady;TextView fleetHint;final ArrayList<Button> shipButtons=new ArrayList<>();JSONArray reviewMoves=new JSONArray(),reviewBest=new JSONArray();int reviewMode=0;boolean gameScreen=false;int me=0,pendingGame=-1,botLevel=1,ship=0,rotation=1,unread=0,reviewIndex=0;
 volatile String analyzing="";boolean reviewing=false;JSONArray analysisNotes=new JSONArray();
 boolean learnMode=false;int openingLesson=-1,coachSeq=-1;String coachSession="",coachRequest="";StockfishEngine.Coach coach;TextView liveChessScore,learningHint;Button hintButton;boolean hintVisible=false;int hintSeq=-1;String hintSession="";
 volatile StockfishEngine stockfish;String botError="",analysisError="";
 Bot bot;final Handler handler=new Handler();final java.util.concurrent.ExecutorService worker=java.util.concurrent.Executors.newSingleThreadExecutor();
 AlertDialog deviceDialog,invitationDialog,chatDialog;LinearLayout deviceList;TextView chatText;
 HashSet<String> seen=new HashSet<>(),discovered=new HashSet<>();ArrayList<String> chats=new ArrayList<>();JSONArray reviewBoards=new JSONArray(),reviewNotes=new JSONArray();Boolean pendingHost=null;
 final BroadcastReceiver receiver=new BroadcastReceiver(){public void onReceive(Context c,Intent i){if(BluetoothDevice.ACTION_FOUND.equals(i.getAction())){BluetoothDevice d=i.getParcelableExtra(BluetoothDevice.EXTRA_DEVICE);if(d!=null){discovered.add(d.getAddress());addDevice(d);}}else if(BluetoothDevice.ACTION_NAME_CHANGED.equals(i.getAction())){BluetoothDevice d=i.getParcelableExtra(BluetoothDevice.EXTRA_DEVICE);if(d!=null&&discovered.contains(d.getAddress()))addDevice(d);}else if(BluetoothAdapter.ACTION_DISCOVERY_FINISHED.equals(i.getAction())&&scanStatus!=null&&!adapter.isDiscovering())scanStatus.setText(seen.isEmpty()?"No nearby devices found. Ask your friend to host again, then scan.":"Scan complete • "+seen.size()+" nearby device(s). Availability is based on this scan.");}};
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);if(Build.VERSION.SDK_INT>=30)getWindow().setDecorFitsSystemWindows(false);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);BluetoothManager manager=(BluetoothManager)getSystemService(BLUETOOTH_SERVICE);adapter=manager==null?null:manager.getAdapter();link=new BluetoothLink(adapter,this);IntentFilter filter=new IntentFilter(BluetoothDevice.ACTION_FOUND);filter.addAction(BluetoothAdapter.ACTION_DISCOVERY_FINISHED);filter.addAction(BluetoothDevice.ACTION_NAME_CHANGED);if(Build.VERSION.SDK_INT>=33)registerReceiver(receiver,filter,Context.RECEIVER_EXPORTED);else registerReceiver(receiver,filter);restore();home();}
 String playerLabel(int side){return "Player "+(local&&!solo&&passSwap?2-side:side+1);}
 int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+.5f);}
 TextView text(String s,int size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setPadding(0,dp(5),0,dp(5));t.setLineSpacing(dp(2),1);return t;}
 GradientDrawable shape(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
 Button button(String s,Runnable action){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setTextSize(15);b.setTypeface(Typeface.create("sans-serif-medium",0));b.setBackground(surface(GREEN,0,12));b.setStateListAnimator(null);b.setElevation(0);b.setMinHeight(dp(48));b.setPadding(dp(14),dp(10),dp(14),dp(10));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(5),0,dp(5));b.setLayoutParams(lp);b.setOnClickListener(v->action.run());return b;}
 Button secondary(String s,Runnable r){Button b=button(s,r);b.setTextColor(INK);b.setBackground(surface(0xfffffcf5,0xffdeddd2,12));return b;}
 android.graphics.drawable.Drawable surface(int fill,int border,int radius){GradientDrawable d=shape(fill,radius);if(border!=0)d.setStroke(dp(1),border);return new android.graphics.drawable.InsetDrawable(new android.graphics.drawable.RippleDrawable(android.content.res.ColorStateList.valueOf(0x22286352),d,null),0,dp(2),0,dp(2));}
 void base(String eyebrow,String title){leaveRts();setRequestedOrientation(android.content.pm.ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);if(Build.VERSION.SDK_INT>=30)getWindow().getInsetsController().setSystemBarsAppearance(WindowInsetsController.APPEARANCE_LIGHT_STATUS_BARS|WindowInsetsController.APPEARANCE_LIGHT_NAVIGATION_BARS,WindowInsetsController.APPEARANCE_LIGHT_STATUS_BARS|WindowInsetsController.APPEARANCE_LIGHT_NAVIGATION_BARS);gameScreen=false;root=new LinearLayout(this);root.setOrientation(1);board=null;root.setLayoutDirection(View.LAYOUT_DIRECTION_LTR);root.setBackgroundColor(BG);root.setPadding(dp(16),dp(8),dp(16),dp(8));root.setOnApplyWindowInsetsListener((v,ins)->{int l=ins.getSystemWindowInsetLeft(),t=ins.getSystemWindowInsetTop(),r=ins.getSystemWindowInsetRight(),b=ins.getSystemWindowInsetBottom();if(Build.VERSION.SDK_INT>=30){android.graphics.Insets safe=ins.getInsets(WindowInsets.Type.systemBars()|WindowInsets.Type.displayCutout()|WindowInsets.Type.ime());l=safe.left;t=safe.top;r=safe.right;b=safe.bottom;}int wide=Math.max(0,(getResources().getDisplayMetrics().widthPixels-l-r-dp(600))/2);v.setPadding(l+dp(16)+wide,t+dp(6),r+dp(16)+wide,b+dp(6));return ins;});setContentView(root);root.requestApplyInsets();LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);TextView heading=text(title,26,INK);heading.setTypeface(Typeface.create("serif",Typeface.BOLD));heading.setMaxLines(1);heading.setAutoSizeTextTypeUniformWithConfiguration(16,26,1,android.util.TypedValue.COMPLEX_UNIT_SP);bar.addView(heading,new LinearLayout.LayoutParams(0,dp(46),1));Button menu=secondary("•••",()->menu());menu.setContentDescription("More options");bar.addView(menu,new LinearLayout.LayoutParams(dp(48),dp(44)));root.addView(bar);connection=text(local?(solo?Bot.LEVELS[botLevel]+" bot · Offline":"Pass & play · Offline"):ready?"●  "+peer+" · Bluetooth":"Offline-ready · Bluetooth multiplayer",11,MUTED);connection.setMaxLines(1);root.addView(connection,new LinearLayout.LayoutParams(-1,dp(27)));}
 void menu(){ArrayList<String> names=new ArrayList<>();ArrayList<Runnable> actions=new ArrayList<>();if(inGame&&state!=null){names.add("Game rules");actions.add(()->rules(state.optInt("id"),0));if(state.optInt("winner")==-1&&(local||ready)){names.add("Resign match");actions.add(()->confirm("Resign?","Your opponent wins.",()->{if(local||host){game.winner=1-me;game.seq++;game.note="Resigned";showSnapshot();}else send(obj("type","resign","session",session));}));}names.add("Game library");actions.add(()->catalog());}if(game!=null||state!=null){names.add("Clear saved match");actions.add(()->confirm("Clear match?","Remove this saved match and disconnect?",()->{link.close();ready=false;game=null;state=null;local=solo=false;session=savedPeer="";fleetDraft=null;save();home();}));}if(ready){names.add("Disconnect");actions.add(()->{link.close();ready=false;home();});}names.add("Stockfish engine & license");actions.add(()->engineAbout());names.add("How to connect");actions.add(()->new AlertDialog.Builder(this).setTitle("Play anywhere").setMessage("Pair phones once in Android Bluetooth Settings. Host on one phone and allow visibility; join and scan on the other. Use the same app version. Bluetooth can work in airplane mode when permitted. Screens stay awake while TrailLink is open.").setPositiveButton("Done",null).show());new AlertDialog.Builder(this).setTitle("TrailLink").setItems(names.toArray(new String[0]),(d,w)->actions.get(w).run()).show();}
 void rules(int id,int page){String[] words=Game.RULES[id].split(" ");ArrayList<String> pages=new ArrayList<>();StringBuilder current=new StringBuilder();for(String word:words){if(current.length()+word.length()>330){pages.add(current.toString());current=new StringBuilder();}current.append(word).append(' ');}pages.add(current.toString());int index=Math.max(0,Math.min(page,pages.size()-1));AlertDialog.Builder dialog=new AlertDialog.Builder(this).setTitle(Game.NAMES[id]+" · "+(index+1)+"/"+pages.size()).setMessage(pages.get(index)).setNegativeButton("Close",null);if(index+1<pages.size())dialog.setPositiveButton("Next",(d,w)->rules(id,index+1));if(index>0)dialog.setNeutralButton("Previous",(d,w)->rules(id,index-1));dialog.show();}

 void home(){reviewing=false;inGame=false;base("","TrailLink");LinearLayout hero=new LinearLayout(this);hero.setOrientation(1);hero.setGravity(Gravity.CENTER_VERTICAL);hero.setPadding(dp(20),dp(12),dp(20),dp(12));hero.setBackground(shape(INK,24));TextView title=text("Play closer.",29,Color.WHITE);title.setTypeface(null,Typeface.BOLD);hero.addView(title);hero.addView(text("16 games. No signal required.",14,0xffc9e5d9));root.addView(hero,new LinearLayout.LayoutParams(-1,0,1));LinearLayout primary=new LinearLayout(this);primary.setOrientation(1);root.addView(primary);if(ready){primary.addView(button(host?"Invite to a game":"Suggest a game",()->catalog()));primary.addView(secondary("Chat"+(unread>0?" ("+unread+")":""),()->chat()));}else{LinearLayout row=new LinearLayout(this);primary.addView(row);footerButton(row,"Host room",()->prepare(true));footerButton(row,"Join friend",()->prepare(false));primary.addView(button("Play against a bot",()->offline(true)));primary.addView(secondary("Pass & play",()->offline(false)));}if((game!=null||state!=null)&&(local||ready))primary.addView(secondary("Resume match",()->{if(local)showSnapshot();else if(host)showSnapshot();else renderGame();}));primary.addView(secondary("Game library",()->catalog()));root.addView(text("PRIVATE  ·  NO ADS  ·  NO INTERNET",10,MUTED));}

 void offline(boolean bots){confirm(bots?"Play offline against a bot?":"Pass & play?","Starting a game replaces the saved match. No Internet or Bluetooth is needed.",()->{link.close();ready=false;game=null;state=null;session="";savedPeer="";local=true;solo=bots;save();if(bots)new AlertDialog.Builder(this).setTitle("Choose bot difficulty").setItems(new String[]{"Easy · Stockfish skill 0 / relaxed bots","Medium · Stockfish skill 8 / tactical bots","Hard · Stockfish skill 20 / strongest bots"},(d,w)->{botLevel=w;catalog();}).show();else catalog();});}
 void catalog(){reviewing=false;inGame=false;base("","Game library");LinearLayout pages=new LinearLayout(this);pages.setOrientation(1);root.addView(pages,new LinearLayout.LayoutParams(-1,0,1));for(int r=0;r<3;r++){LinearLayout row=new LinearLayout(this);pages.addView(row,new LinearLayout.LayoutParams(-1,0,1));for(int col=0;col<2;col++){final int id=libraryPage*6+r*2+col;if(id>=Game.NAMES.length){row.addView(new View(this),new LinearLayout.LayoutParams(0,-1,1));continue;}LinearLayout card=new LinearLayout(this);card.setOrientation(1);card.setGravity(Gravity.CENTER_VERTICAL);card.setPadding(dp(14),dp(8),dp(14),dp(8));card.setBackground(shape(Color.WHITE,20));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-1,1);lp.setMargins(dp(4),dp(5),dp(4),dp(5));row.addView(card,lp);TextView number=text(String.format(Locale.ROOT,"%02d",id+1),11,GREEN);card.addView(number);TextView title=text(Game.NAMES[id],18,INK);title.setMaxLines(2);title.setAutoSizeTextTypeUniformWithConfiguration(12,18,1,android.util.TypedValue.COMPLEX_UNIT_SP);title.setTypeface(null,Typeface.BOLD);card.addView(title,new LinearLayout.LayoutParams(-1,0,1));card.addView(text(local?"PLAY →":ready?host?"INVITE →":"SUGGEST →":"RULES →",10,GREEN));card.setOnClickListener(v->{if(local){if(game==null)startFromLibrary(id);else confirm("New match?","Replace the current game?",()->startFromLibrary(id));}else if(ready){if(id==15&&host)chooseRts();else invite(id);}else rules(id,0);});}}LinearLayout nav=new LinearLayout(this);root.addView(nav);footerButton(nav,"‹",()->{libraryPage=(libraryPage+2)%3;catalog();});footerButton(nav,(libraryPage+1)+" / 3",()->home());footerButton(nav,"›",()->{libraryPage=(libraryPage+1)%3;catalog();});}

 boolean permissions(){if(adapter==null){toast("No Bluetooth adapter. Offline games are available.");return false;}ArrayList<String> needed=new ArrayList<>();String[] perms=Build.VERSION.SDK_INT>=31?new String[]{"android.permission.BLUETOOTH_CONNECT","android.permission.BLUETOOTH_SCAN","android.permission.BLUETOOTH_ADVERTISE"}:new String[]{"android.permission.ACCESS_FINE_LOCATION"};for(String p:perms)if(checkSelfPermission(p)!=PackageManager.PERMISSION_GRANTED)needed.add(p);if(!needed.isEmpty()){requestPermissions(needed.toArray(new String[0]),4);return false;}if(!adapter.isEnabled()){startActivityForResult(new Intent(BluetoothAdapter.ACTION_REQUEST_ENABLE),5);return false;}return true;}
 void prepare(boolean hosting){if(!local&&!session.isEmpty()&&hosting!=host){toast(host?"Resume by hosting again, or clear the saved match.":"Resume by joining your host, or clear the saved match.");return;}pendingHost=hosting;if(!permissions())return;pendingHost=null;if(local){game=null;state=null;session="";savedPeer="";local=solo=false;}host=hosting;ready=false;pendingGame=-1;if(host){link.host();home();Intent discover=new Intent(BluetoothAdapter.ACTION_REQUEST_DISCOVERABLE);discover.putExtra(BluetoothAdapter.EXTRA_DISCOVERABLE_DURATION,300);startActivityForResult(discover,6);}else devices();}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] results){super.onRequestPermissionsResult(r,p,results);if(r==4){boolean allowed=results.length>0;for(int v:results)if(v!=PackageManager.PERMISSION_GRANTED)allowed=false;if(allowed&&pendingHost!=null)prepare(pendingHost);else toast("Nearby devices permission is needed for Bluetooth play.");}}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==5&&result==RESULT_OK&&pendingHost!=null)prepare(pendingHost);}
 void devices(){deviceList=new LinearLayout(this);deviceList.setOrientation(1);deviceList.setPadding(dp(16),0,dp(16),0);deviceDialog=new AlertDialog.Builder(this).setTitle("Nearby devices").setView(deviceList).setNegativeButton("Cancel",(d,w)->adapter.cancelDiscovery()).setPositiveButton("Pair phones",(d,w)->{adapter.cancelDiscovery();pairSettings();}).setNeutralButton("Scan again",null).create();deviceDialog.setOnDismissListener(d->adapter.cancelDiscovery());deviceDialog.setOnShowListener(d->{deviceDialog.getButton(-3).setOnClickListener(v->scan());scan();});deviceDialog.show();}
 void scan(){adapter.cancelDiscovery();seen.clear();discovered.clear();foundDevices.clear();devicePage=0;deviceList.removeAllViews();scanStatus=text("Scanning… Only devices seen in this scan appear. Your friend must tap Host a room and allow visibility.",14,MUTED);deviceList.addView(scanStatus);if(!adapter.startDiscovery())scanStatus.setText("Could not start discovery. Check Bluetooth and Nearby devices permission, then retry.");}
 void pairSettings(){new AlertDialog.Builder(this).setTitle("Pair once, play anywhere").setMessage("Open Bluetooth Settings on BOTH phones. Select the other phone, then confirm matching codes on both. Contacts access is not needed.\n\nReturn to TrailLink: Host a room on one phone, Join a friend on the other.").setPositiveButton("Open Settings",(d,w)->startActivity(new Intent(android.provider.Settings.ACTION_BLUETOOTH_SETTINGS))).setNegativeButton("Back",null).show();}
 void addDevice(BluetoothDevice d){if(deviceList==null||deviceDialog==null||!deviceDialog.isShowing()||seen.contains(d.getAddress()))return;String n=d.getName();if(n==null||n.trim().isEmpty())return;BluetoothClass cls=d.getBluetoothClass();if(cls!=null&&cls.getMajorDeviceClass()!=BluetoothClass.Device.Major.PHONE&&cls.getMajorDeviceClass()!=BluetoothClass.Device.Major.UNCATEGORIZED)return;seen.add(d.getAddress());foundDevices.add(d);deviceResults();}
 void deviceResults(){deviceList.removeAllViews();scanStatus=text("Nearby phones · "+foundDevices.size()+" found",13,MUTED);deviceList.addView(scanStatus);int pages=Math.max(1,(foundDevices.size()+2)/3);devicePage=Math.min(devicePage,pages-1);for(int i=devicePage*3;i<Math.min(foundDevices.size(),devicePage*3+3);i++){BluetoothDevice d=foundDevices.get(i);deviceList.addView(button(d.getName()+(d.getBondState()==BluetoothDevice.BOND_BONDED?" · paired":" · pair first"),()->{deviceDialog.dismiss();adapter.cancelDiscovery();if(d.getBondState()!=BluetoothDevice.BOND_BONDED){pairSettings();return;}status="Connecting to "+d.getName();home();link.join(d);}));}if(pages>1){LinearLayout nav=new LinearLayout(this);deviceList.addView(nav);footerButton(nav,"‹",()->{devicePage=(devicePage+pages-1)%pages;deviceResults();});footerButton(nav,(devicePage+1)+"/"+pages,()->{});footerButton(nav,"›",()->{devicePage=(devicePage+1)%pages;deviceResults();});}}
 @Override public void connected(String name,String address){runOnUiThread(()->{peer=name==null?"Friend":name;peerAddress=address;status="Bluetooth connected • checking version";if(connection!=null)connection.setText(status);send(obj("type","hello","version",4));});}
 @Override public void status(String value){runOnUiThread(()->{status=value;if(connection!=null&&!local)connection.setText(status);});}
 @Override public void lost(){runOnUiThread(()->{ready=false;rtsPeerActive=false;awaiting=false;pendingGame=-1;if(state!=null&&state.optInt("id")==15)try{state.put("paused",true);}catch(Exception ignored){}if(invitationDialog!=null)invitationDialog.dismiss();if(chatDialog!=null)chatDialog.dismiss();if(inGame&&state!=null)renderGame();});}
 void send(JSONObject o){link.send(o);}static JSONObject obj(Object... pairs){JSONObject o=new JSONObject();try{for(int i=0;i<pairs.length;i+=2)o.put((String)pairs[i],pairs[i+1]);}catch(Exception e){throw new IllegalArgumentException(e);}return o;}
 @Override public void message(JSONObject m){runOnUiThread(()->{try{String type=m.getString("type");if(type.equals("hello")){if(m.optInt("version")!=4){link.close();ready=false;status("Version mismatch • install the same APK on both phones");return;}if(!savedPeer.isEmpty()&&!savedPeer.equals(peerAddress)){link.close();ready=false;status("Different phone • clear the previous match first");return;}ready=true;status="Connected to "+peer+" • Bluetooth only";if(host&&game!=null)showSnapshot();else{if(host)send(obj("type","room"));home();}return;}if(!ready)return;
  if(type.equals("room")&&!host){game=null;state=null;session="";savedPeer="";save();home();return;}
  if(type.equals("chat")){String body=m.optString("text").trim();if(!body.isEmpty()&&body.length()<=300)appendChat(peer+": "+body,true);return;}
  if(type.equals("offer")||type.equals("suggest")){boolean valid=type.equals("offer")&&!host||type.equals("suggest")&&host;int id=m.optInt("game",-1);if(!valid||id<0||id>=Game.NAMES.length)return;if(pendingGame>=0){send(obj("type","decline"));return;}if(invitationDialog!=null)invitationDialog.dismiss();invitationDialog=new AlertDialog.Builder(this).setTitle(peer+(host?" suggests ":" invites you to ")+Game.NAMES[id]).setMessage("Start a new match with a fresh random starter? This replaces the current match.").setPositiveButton("Play",(d,w)->{if(ready){if(host)startGame(id);else send(obj("type","accept","game",id));}}).setNegativeButton("Not now",(d,w)->{if(ready)send(obj("type","decline"));}).setCancelable(false).show();}
  else if(type.equals("accept")&&host&&pendingGame>=0&&m.optInt("game",-1)==pendingGame){int id=pendingGame;pendingGame=-1;startGame(id);}
  else if(type.equals("decline")){pendingGame=-1;toast("Your friend declined or is handling another invitation.");if(inGame)renderGame();}
  else if(type.equals("rts_presence")&&host&&game!=null&&game.id==15&&session.equals(m.optString("session"))){rtsPeerActive=m.optBoolean("active");}
  else if(type.equals("rts_order")&&host&&game!=null&&game.id==15&&session.equals(m.optString("session"))&&!rtsIsPaused()){JSONArray ids=m.optJSONArray("ids");if(ids!=null&&ids.length()>0&&ids.length()<=24){int[] chosen=new int[ids.length()];for(int i=0;i<chosen.length;i++)chosen[i]=ids.optInt(i,-1);game.rts.issue(1-me,m.optLong("command"),m.optInt("action"),chosen,m.optInt("unit",-1),m.optInt("x",-1),m.optInt("y",-1));}}
  else if(type.equals("rts_resign")&&host&&game!=null&&game.id==15&&session.equals(m.optString("session"))){game.rts.winner=game.winner=me;publishRts();save();}
  else if(type.equals("state")&&!host){if(m.optInt("id",-1)<0||m.optInt("id")>=Game.NAMES.length||m.optJSONArray("b")==null||m.optJSONArray("moves")==null)return;String incoming=m.getString("session");boolean newRtsSession=!session.equals(incoming),wasRtsVisible=rtsVisible;if(newRtsSession){rtsView=null;rtsVisible=false;rtsCommand=0;rtsLastSave=-1;reviewBoards=new JSONArray();reviewNotes=new JSONArray();analysisNotes=new JSONArray();reviewMoves=new JSONArray();reviewBest=new JSONArray();fleetDraft=null;fleetTab=false;ship=0;}state=m;session=incoming;me=m.getInt("me");savedPeer=peerAddress;pendingGame=-1;awaiting=false;if(state.optInt("id")!=15||state.optInt("seq")/50!=rtsLastSave||state.optInt("winner")>=0){rtsLastSave=state.optInt("seq")/50;save();}if(state.optInt("id")!=15||newRtsSession||wasRtsVisible)renderGame();}
  else if(type.equals("review")&&!host&&session.equals(m.optString("session"))){int start=m.optInt("start");JSONArray boards=m.getJSONArray("boards"),notes=m.getJSONArray("notes");if(start==0){reviewBoards=new JSONArray();reviewNotes=new JSONArray();}if(start!=reviewBoards.length())return;for(int i=0;i<boards.length();i++){reviewBoards.put(boards.get(i));reviewNotes.put(notes.get(i));if(m.optJSONArray("played")!=null)reviewMoves.put(start+i,m.getJSONArray("played").get(i));if(m.optJSONArray("best")!=null)reviewBest.put(start+i,m.getJSONArray("best").get(i));if(m.optJSONArray("analysis")!=null)analysisNotes.put(start+i,m.optJSONArray("analysis").optString(i));}if(inGame&&state!=null&&reviewBoards.length()==state.optInt("reviewCount"))renderGame();save();}
  else if(type.equals("analysis")&&!host&&session.equals(m.optString("session"))){int index=m.optInt("index",-1);if(index>=0&&index<10000){analysisNotes.put(index,m.optString("result"));if(m.optJSONArray("best")!=null)reviewBest.put(index,m.optJSONArray("best"));save();if(reviewing)review();}}
  else if(type.equals("fleet")&&host&&game!=null&&session.equals(m.optString("session"))){JSONArray arr=m.optJSONArray("layout");if(arr!=null&&arr.length()==100){int[] layout=new int[100];for(int i=0;i<100;i++)layout[i]=arr.optInt(i,-1);if(game.applyFleet(1-me,layout))showSnapshot();else sendSnapshot();}}
  else if(type.equals("move")&&host&&game!=null){if(!session.equals(m.optString("session"))||m.optInt("seq",-1)!=game.seq){sendSnapshot();return;}if(game.move(1-me,m.getInt("a"),m.getInt("z"),m.optInt("choice",5)))showSnapshot();else sendSnapshot();}
  else if(type.equals("resign")&&host&&game!=null&&session.equals(m.optString("session"))&&game.winner==-1){game.winner=me;game.seq++;game.note="Opponent resigned";showSnapshot();}
  else if(type.equals("error"))toast(m.optString("text","Connection error"));
 }catch(Exception e){android.util.Log.w("TrailLink","Rejected malformed message",e);}});}
 void invite(int id){if(!ready)return;if(pendingGame!=-1){toast("Waiting for your friend's response.");return;}pendingGame=id;send(obj("type",host?"offer":"suggest","game",id));toast((host?"Invitation":"Suggestion")+" sent for "+Game.NAMES[id]);if(inGame)renderGame();}
 void startGame(int id){if(id==15&&local&&!solo){toast("Real-time skirmishes use bots or two Bluetooth phones, not pass & play.");return;}rtsVisible=false;rtsView=null;rtsPeerActive=false;rtsPaused=false;rtsLastSave=-1;rtsCommand=0;reviewing=false;hintVisible=false;coach=null;coachRequest="";coachSeq=-1;if(id!=0){learnMode=false;openingLesson=-1;}botError=analysisError="";fleetDraft=null;fleetTab=false;reviewMoves=new JSONArray();reviewBest=new JSONArray();long seed=new java.security.SecureRandom().nextLong();game=new Game(id,seed);if(id==15)game.rts=new RiftWar(seed,rtsMap,rtsDoctrine);me=new Random(seed^0x7913L).nextBoolean()?0:1;if(solo&&id==0&&learnMode&&openingLesson>=0)me=0;if(id==15)game.rts.doctrine0=me==0?rtsDoctrine:1-rtsDoctrine;game.turn=0;passSwap=local&&!solo&&(id==0||id==13)&&me==1;if(local&&!solo){game.turn=id==0||id==13?0:me;me=game.setup?0:game.turn;}bot=solo?new Bot(botLevel,seed^9321):null;if(solo&&game.setup){game.randomSetup(1-me);game.move(1-me,-10,0,0);}session=UUID.randomUUID().toString();savedPeer=local?"":peerAddress;pendingGame=-1;ship=0;rotation=1;reviewBoards=new JSONArray();reviewNotes=new JSONArray();analysisNotes=new JSONArray();analyzing="";if(local&&!solo&&game.setup)handover();else showSnapshot();}
 static JSONArray array(int[] values){JSONArray a=new JSONArray();for(int v:values)a.put(v);return a;}
 JSONObject snapshot(int p){if(game.id==15)return RiftWire.snapshot(game.rts,p,session,rtsIsPaused());JSONArray moves=new JSONArray();if(!game.setup&&game.turn==p)for(int[] m:game.legal())moves.put(array(m));return obj("type","state","session",session,"id",game.id,"seq",game.seq,"me",p,"passSwap",passSwap,"turn",game.turn,"winner",game.winner,"b",array(game.view(p)),"aux",array(game.id==7||game.id==1?new int[200]:game.aux),"score",array(game.score),"count",array(game.count),"phase",game.phase,"chain",game.chain,"note",game.note,"word",game.wordView(),"guessed",game.guessed,"moves",moves,"setup",game.setup,"prepared",new JSONArray(Arrays.asList(game.prepared[0],game.prepared[1])),"canReady",game.setup&&(game.id==1||game.id==7)&&game.setupComplete(p),"lastA",game.lastA,"lastZ",game.lastZ,"lastPlayer",game.lastPlayer,"lastMove",game.lastMove,"changed",array(game.changed),"before",array(game.beforeMove),"sow",array(game.sowPath),"reviewCount",game.id==0&&game.winner>=0?game.history.size():0);}
 void sendSnapshot(){if(!local&&host&&ready){if(game.id==15){link.sendLatest(snapshot(1-me));return;}send(snapshot(1-me));if(game.id==0&&game.winner>=0){for(int start=0;start<game.history.size();start+=10){JSONArray boards=new JSONArray(),notes=new JSONArray(),analyses=new JSONArray(),playedMoves=new JSONArray(),bestMoves=new JSONArray();for(int i=start;i<Math.min(start+10,game.history.size());i++){boards.put(array(game.history.get(i)));playedMoves.put(i>0?array(game.chessMoves.get(i-1)):new JSONArray());bestMoves.put(i>0&&i-1<game.analysisBest.size()?array(game.analysisBest.get(i-1)):new JSONArray());notes.put(game.commentary.get(i));analyses.put(i>0&&i-1<game.analysis.size()?game.analysis.get(i-1):"");}send(obj("type","review","session",session,"start",start,"boards",boards,"notes",notes,"analysis",analyses,"played",playedMoves,"best",bestMoves));}}}}
 void showSnapshot(){if(game!=null&&game.id==15){state=snapshot(me);save();sendSnapshot();showRts();scheduleRts();return;}if(game!=null&&(game.seq!=hintSeq||!session.equals(hintSession)))hintVisible=false;if(game==null){if(state!=null)renderGame();else home();return;}if(local&&!solo&&!game.setup){me=game.turn;if(game.id==13&&game.phase==1&&game.prepared[me]&&!game.prepared[1-me])me=1-me;}state=snapshot(me);if(solo&&bot!=null)bot.observe(game,1-me);save();sendSnapshot();if(reviewing)review();else renderGame();scheduleBot();beginAnalysis();scheduleCoach();}
 void scheduleBot(){
  if(!solo||game==null||game.id==15||game.setup||game.winner>=0||session.equals(thinkingSession)||destroyed||!botError.isEmpty())return;
  if(game.id==13&&game.phase==1){if(!game.prepared[1-me]){game.move(1-me,-4,0,5);showSnapshot();}return;}
  if(game.turn==me)return;
  final String match=session;
  final int seq=game.seq,player=1-me,level=botLevel;
  final Game position=game.copy();
  final Bot brain=bot;
  // A guided response is authored data, not an engine request.  Keep it off
  // the Stockfish worker so an abandoned match can never hold up a lesson.
  final boolean scriptedLesson=learnMode&&openingLesson>=0&&position.id==0;
  final int lesson=scriptedLesson?openingLesson:-1;
  final int[] scripted=scriptedLesson?ChessTutor.next(position,lesson):null;
  thinkingSession=match;
  if(scripted!=null){
   handler.postDelayed(()->{
    if(match.equals(thinkingSession))thinkingSession="";
    if(destroyed)return;
    boolean sameMatch=solo&&game!=null&&session.equals(match)&&game.seq==seq&&game.turn==player&&game.winner<0;
    boolean sameLesson=learnMode&&openingLesson==lesson;
    if(sameMatch&&sameLesson){
     if(game.move(player,scripted[0],scripted[1],scripted.length>2?scripted[2]:5)){botError="";showSnapshot();}
     else{botError="The planned lesson reply could not be applied. Tap Retry bot.";renderGame();}
    }else scheduleBot();
   },350L);
   return;
  }
  worker.execute(()->{
   int[] move=null;String error="";
   try{
    move=position.id==0?getStockfish().choose(position,level):brain.choose(position,player);
    if(move==null)error="The bot returned no move.";
   }catch(Exception e){error="Engine unavailable. Tap Retry bot.";android.util.Log.e("TrailLink","Bot failed",e);}
   final int[] chosen=move;final String failure=error;
   handler.postDelayed(()->{
    if(match.equals(thinkingSession))thinkingSession="";
    if(destroyed)return;
    boolean sameMatch=solo&&game!=null&&session.equals(match)&&game.seq==seq&&game.turn==player&&game.winner<0;
    if(sameMatch){
     if(chosen!=null&&game.move(player,chosen[0],chosen[1],chosen.length>2?chosen[2]:5)){botError="";showSnapshot();}
     else{botError=failure.isEmpty()?"Invalid engine move. Tap Retry bot.":failure;renderGame();}
    }else scheduleBot();
   },position.id==9?3300:150);
  });
 }
 void startFromLibrary(int id){if(id==15){chooseRts();return;}if(id==0&&solo){new AlertDialog.Builder(this).setTitle("Chess mode").setItems(new String[]{"Play chess · live score","Learn chess · hints and openings"},(d,w)->{learnMode=w==1;openingLesson=-1;startGame(0);}).show();}else startGame(id);}
 String lessonText(){if(game==null)return "";if(openingLesson>=0){int[] move=ChessTutor.next(game,openingLesson);return move==null?ChessTutor.NAMES[openingLesson]+" complete · continue with Stockfish.":ChessTutor.NAMES[openingLesson]+" · step "+(game.chessMoves.size()+1)+"/"+ChessTutor.LINES[openingLesson].split(" ").length+" · "+(game.turn==me?ChessTutor.explain(game,move):"Watch Black's planned reply.");}return ChessTutor.opening(game);}
 void openingLesson(int index){int pick=Math.max(0,Math.min(ChessTutor.NAMES.length-1,index));new AlertDialog.Builder(this).setTitle(ChessTutor.NAMES[pick]+" · "+(pick+1)+"/"+ChessTutor.NAMES.length).setMessage(ChessTutor.INTRO[pick]+"\n\nGuided practice: you play White, Black follows the lesson. Use Hint if needed. Other moves are blocked until the short line is complete. Afterward, continue against Stockfish.").setPositiveButton("Start lesson",(d,w)->confirm("Start opening lesson?","This replaces the current saved match.",()->{learnMode=true;openingLesson=pick;startGame(0);})).setNeutralButton("Next opening",(d,w)->openingLesson((pick+1)%ChessTutor.NAMES.length)).setNegativeButton("Free learning",(d,w)->{openingLesson=-1;save();renderGame();scheduleCoach();}).show();}
 void scheduleCoach(){if(!solo||game==null||game.id!=0||game.winner>=0||game.turn!=me||destroyed)return;final String token=session;final int seq=game.seq,player=me;String request=token+":"+seq;if(request.equals(coachRequest))return;coachRequest=request;final Game position=game.copy();worker.execute(()->{StockfishEngine.Coach result=null;try{result=getStockfish().coach(position,player);}catch(Exception e){android.util.Log.w("TrailLink","Coach unavailable",e);}final StockfishEngine.Coach value=result;handler.post(()->{if(destroyed||game==null||!session.equals(token)||game.seq!=seq)return;coach=value;coachSeq=seq;coachSession=token;if(gameScreen&&!reviewing){if(liveChessScore!=null)liveChessScore.setText(value==null?"Score unavailable · reopen match to retry":"LIVE · "+value.score);if(hintButton!=null&&learnMode&&value!=null)hintButton.setVisibility(View.VISIBLE);}if(value==null)coachRequest="";});});}
 void showCoachHint(){if(!solo||!learnMode||game==null||!active())return;hintVisible=!hintVisible;hintSeq=game.seq;hintSession=session;updateInlineHint();}
 void updateInlineHint(){if(game==null||board==null||learningHint==null)return;int[] move=ChessTutor.next(game,openingLesson);boolean current=coach!=null&&coachSeq==game.seq&&coachSession.equals(session);String explanation=move!=null?ChessTutor.explain(game,move):current?coach.explanation:"Evaluating…";if(move==null&&current)move=coach.move;try{JSONObject display=new JSONObject(state.toString());if(hintVisible&&move!=null){display.put("bestFrom",move[0]);display.put("bestTo",move[1]);}board.update(display,false);}catch(Exception ignored){}learningHint.setText(hintVisible?"HINT  ·  "+explanation:"COACH  ·  "+lessonText());if(hintButton!=null)hintButton.setText(hintVisible?"Hide hint":"Hint");}
 int undoPly(){return local?ChessTimeline.undoPly(game,solo,me):-1;}
 void undoChess(){int ply=undoPly();if(ply<0)return;confirm("Take back your move?",solo?"Return to your previous decision, including the bot's reply. Later moves will be replaced.":"Take back the last move. Both players should agree before continuing.",()->continueChess(ply));}
 void continueChess(int ply){if(!local||game==null||game.id!=0)return;try{Game branch=ChessTimeline.branch(game,ply);analyzing="";session=UUID.randomUUID().toString();game=branch;coach=null;coachSeq=-1;coachRequest="";hintVisible=false;botError=analysisError="";awaiting=false;reviewing=false;reviewBoards=new JSONArray();reviewNotes=new JSONArray();analysisNotes=new JSONArray();reviewMoves=new JSONArray();reviewBest=new JSONArray();if(solo)bot=new Bot(botLevel,System.nanoTime());showSnapshot();}catch(IllegalArgumentException e){toast(e.getMessage());}}
 void continueReview(){if(!local||game==null)return;final int ply=reviewMode==1?reviewIndex:reviewIndex-1;confirm("Play from this position?",(reviewMode==1?"Continue AFTER the displayed move.":"Continue BEFORE this move; the arrows are suggestions, not moves already made.")+" Later moves and their review will be replaced. "+(solo?"You keep your color; Stockfish plays if it is its turn.":"Continue in pass & play."),()->continueChess(ply));}

 StockfishEngine getStockfish()throws Exception{if(destroyed||Thread.currentThread().isInterrupted())throw new InterruptedException();if(stockfish!=null)return stockfish;java.io.File net=new java.io.File(getFilesDir(),"nn-5af11540bbfe.nnue");if(!net.isFile()||net.length()!=40119326){java.io.File temp=new java.io.File(getFilesDir(),"stockfish-net.tmp");java.security.MessageDigest digest=java.security.MessageDigest.getInstance("SHA-256");try(java.io.InputStream input=getAssets().open("stockfish/nn-5af11540bbfe.nnue");java.io.OutputStream out=new java.io.FileOutputStream(temp)){byte[] data=new byte[65536];int size;while((size=input.read(data))!=-1){if(Thread.currentThread().isInterrupted())throw new InterruptedException();digest.update(data,0,size);out.write(data,0,size);}}StringBuilder hash=new StringBuilder();for(byte part:digest.digest())hash.append(String.format(Locale.ROOT,"%02x",part&255));if(!hash.toString().equals("5af11540bbfefcb54e38c5dd000cab4b469dfa7599a1d55be5d2722c20a8929b"))throw new java.io.IOException("Stockfish network checksum mismatch");java.nio.file.Files.move(temp.toPath(),net.toPath(),java.nio.file.StandardCopyOption.REPLACE_EXISTING);}if(destroyed||Thread.currentThread().isInterrupted())throw new InterruptedException();stockfish=new StockfishEngine(new java.io.File(getApplicationInfo().nativeLibraryDir,"libstockfish.so"),net);return stockfish;}
 void engineAbout(){new AlertDialog.Builder(this).setTitle("Stockfish 16 · offline NNUE").setMessage("Chess bots and new reviews use the genuine Stockfish engine. Easy: skill 0, Medium: 8, Hard: 20. One search thread, 32 MB hash; no pondering or network needed. Strength depends on device and search time.\n\n© 2004–2023 the Stockfish developers. GNU GPL v3 or later. Exact engine source and build instructions are included with TrailLink's source package.").setNegativeButton("Close",null).setNeutralButton("License",(d,w)->engineLicense(0)).setPositiveButton("Source",(d,w)->{try{startActivity(new Intent(Intent.ACTION_VIEW,android.net.Uri.parse("https://github.com/official-stockfish/Stockfish/tree/sf_16")));}catch(Exception e){toast("No browser available; source is included with the app source ZIP.");}}).show();}
 void engineLicense(int page){try{java.io.ByteArrayOutputStream out=new java.io.ByteArrayOutputStream();try(java.io.InputStream in=getAssets().open("stockfish/COPYING.txt")){byte[] data=new byte[4096];int n;while((n=in.read(data))!=-1)out.write(data,0,n);}String license=out.toString("UTF-8");int pages=(license.length()+329)/330,p=Math.max(0,Math.min(pages-1,page));AlertDialog.Builder d=new AlertDialog.Builder(this).setTitle("GPL · "+(p+1)+"/"+pages).setMessage(license.substring(p*330,Math.min(license.length(),(p+1)*330))).setNegativeButton("Close",null);if(p>0)d.setNeutralButton("Previous",(x,w)->engineLicense(p-1));if(p+1<pages)d.setPositiveButton("Next",(x,w)->engineLicense(p+1));d.show();}catch(Exception e){toast("License is included in the source package.");}}

 void handover(){state=snapshot(me);save();inGame=true;base("Private handover","Pass the phone");root.addView(text("Give the phone to Player "+(me+1)+" before revealing their board.",20,INK));root.addView(button("I'm Player "+(me+1)+" • reveal",()->showSnapshot()));}
 boolean active(){return state!=null&&state.optInt("winner")==-1&&(local||ready&&link.connected)&&!awaiting&&(state.optBoolean("setup")?!state.optJSONArray("prepared").optBoolean(me):state.optInt("id")==13&&state.optInt("phase")==1||state.optInt("turn")==me);}
 void act(int a,int z,int choice){if(!active()||board!=null&&board.animating())return;if(local||host){if(solo&&learnMode&&game.id==0&&openingLesson>=0){int[] expected=ChessTutor.next(game,openingLesson);if(expected!=null&&(a!=expected[0]||z!=expected[1]||choice!=expected[2])){if(learningHint!=null)learningHint.setText("TRY AGAIN  ·  "+ChessTutor.explain(game,expected));if(board!=null)board.performHapticFeedback(HapticFeedbackConstants.REJECT);return;}}int old=me;if(game.move(me,a,z,choice)){if(local&&!solo&&game.winner<0&&(game.id==1||game.id==7)&&(game.setup&&game.prepared[old]||!game.setup&&old!=game.turn)){me=game.setup?1-old:game.turn;handover();}else showSnapshot();}else if(game.setup)toast("That placement does not fit. Choose a clear starting square.");}else{awaiting=true;send(obj("type","move","session",session,"seq",state.optInt("seq"),"a",a,"z",z,"choice",choice));if(connection!=null)connection.setText("Sending…");}}
 void ensureDraft(){if(fleetDraft!=null&&draftSession.equals(session)&&draftPlayer==me)return;fleetDraft=new Game(7,0);draftSession=session;draftPlayer=me;JSONArray arr=state.optJSONArray("b");for(int i=0;i<100;i++)fleetDraft.b[i]=arr.optInt(i);android.content.SharedPreferences prefs=getSharedPreferences("fleet-draft",0);if((session+":"+me).equals(prefs.getString("session","")))try{JSONArray saved=new JSONArray(prefs.getString("layout","[]"));if(saved.length()==100)for(int i=0;i<100;i++)fleetDraft.b[i]=saved.optInt(i);}catch(Exception ignored){}}
 JSONObject displayState(){if(state.optInt("id")==7&&state.optBoolean("setup")&&!state.optJSONArray("prepared").optBoolean(me)){ensureDraft();try{JSONObject view=new JSONObject(state.toString());view.put("b",array(fleetDraft.view(0)));return view;}catch(Exception e){return state;}}return state;}
 void updateFleet(){if(board!=null)board.update(displayState(),false);boolean complete=fleetDraft.setupComplete(0);if(fleetReady!=null)fleetReady.setVisibility(complete?View.VISIBLE:View.INVISIBLE);if(fleetHint!=null)fleetHint.setText(new String[]{"Carrier","Battleship","Cruiser","Submarine","Destroyer"}[ship]+" · "+Game.FLEET[ship]+" cells · "+(rotation==1?"Horizontal":"Vertical"));for(int i=0;i<shipButtons.size();i++){shipButtons.get(i).setBackground(shape(i==ship?GREEN:0xffe1ebe6,12));shipButtons.get(i).setTextColor(i==ship?Color.WHITE:INK);}getSharedPreferences("fleet-draft",0).edit().putString("session",session+":"+me).putString("layout",array(Arrays.copyOf(fleetDraft.b,100)).toString()).apply();}
 void setupTap(int a,int z){if(state.optInt("id")==1){act(a,z,0);return;}if(!active())return;ensureDraft();if(fleetDraft.placeShip(0,a,rotation,ship)){updateFleet();board.performHapticFeedback(HapticFeedbackConstants.CLOCK_TICK);}else{fleetHint.setText("Doesn't fit · choose a clear starting square");board.performHapticFeedback(HapticFeedbackConstants.REJECT);}}
 void lockFleet(){if(!active())return;ensureDraft();int[] layout=Arrays.copyOf(fleetDraft.b,100);if(local||host){if(game.applyFleet(me,layout)){fleetDraft=null;if(local&&!solo&&game.setup){me=1-me;handover();}else showSnapshot();}}else{awaiting=true;send(obj("type","fleet","session",session,"layout",array(layout)));if(fleetReady!=null)fleetReady.setVisibility(View.INVISIBLE);}}
 void statusPanel(LinearLayout parent,String title,String detail){LinearLayout card=new LinearLayout(this);card.setOrientation(1);card.setPadding(dp(12),dp(5),dp(12),dp(5));card.setBackground(shape(INK,16));TextView heading=text(title,17,0xfffff8e7);heading.setTypeface(null,Typeface.BOLD);heading.setMaxLines(1);heading.setAutoSizeTextTypeUniformWithConfiguration(12,17,1,android.util.TypedValue.COMPLEX_UNIT_SP);card.addView(heading,new LinearLayout.LayoutParams(-1,dp(30)));TextView info=text(detail,11,0xffcbd6cc);info.setMaxLines(2);card.addView(info,new LinearLayout.LayoutParams(-1,dp(30)));parent.addView(card);}
 void addBoard(LinearLayout parent,JSONObject position,boolean animate){FrameLayout frame=new FrameLayout(this);frame.setPadding(dp(5),dp(5),dp(5),dp(5));frame.setBackground(shape(position.optInt("id")==0?BG:Color.WHITE,16));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,0,1);lp.setMargins(0,dp(6),0,dp(6));parent.addView(frame,lp);board=new BoardView(this,position,me);frame.addView(board,new FrameLayout.LayoutParams(-1,-1));board.update(position,animate);}
 void renderGame(){if(state==null)return;if(state.optInt("id")==15){showRts();return;}boolean animate=gameScreen&&!reviewing&&(!animatedSession.equals(session)||animatedSeq!=state.optInt("seq"));if(state.optInt("id")==9){animatedSession=session;animatedSeq=state.optInt("seq");}reviewing=false;inGame=true;int id=state.optInt("id"),turn=state.optInt("turn"),win=state.optInt("winner");boolean setup=state.optBoolean("setup"),ownReady=state.optJSONArray("prepared").optBoolean(me);base("",id==0&&solo&&learnMode?"Chess · Learn":Game.NAMES[id]);gameScreen=true;String headline=win==2?"Draw":win>=0?(local&&!solo?playerLabel(win)+" wins":win==me?"You win":solo?"Bot wins":"Your friend wins"):!local&&!ready?"Reconnect to continue":setup?(ownReady?"Waiting for opponent":"Arrange your "+(id==7?"fleet":"army")):id==13&&state.optInt("phase")==1?"Agree the final score":id==10&&state.optInt("phase")==1?"Mill · remove an enemy stone":local&&!solo?playerLabel(turn)+" to move":turn==me?"Your turn":solo?(!botError.isEmpty()?"Engine needs attention":id==0?"Stockfish is thinking…":"Bot is thinking…"):"Opponent's turn";
  String detail=id==0?(me==0?"You play White":"You play Black"):setup?id==7?"Choose a ship · tap to place · lock when ready":"Tap two home pieces to swap their positions":"You are Player "+(me+1);if(id==0&&solo)detail=(me==0?"You: White":"You: Black")+" · Stockfish 16 · "+Bot.LEVELS[botLevel];JSONArray count=state.optJSONArray("count"),score=state.optJSONArray("score");if(id==10)detail="Reserve  P1: "+Math.max(0,9-count.optInt(0))+"  ·  P2: "+Math.max(0,9-count.optInt(1))+"     Board: "+piecesInView(0)+" / "+piecesInView(1);if(id==9)detail="P1 store: "+state.optJSONArray("b").optInt(6)+"   ·   P2 store: "+state.optJSONArray("b").optInt(13)+"     Follow the arrows";if(id==13)detail=state.optInt("phase")==1||win>=0?"Area  Black "+score.optInt(0)/2.0+" · White "+score.optInt(1)/2.0+" (7.5 komi)":"Black captures "+count.optInt(0)+" · White captures "+count.optInt(1)+" · 9×9";if(id==8||id==12||id==14)detail="Player 1: "+score.optInt(0)+"     Player 2: "+score.optInt(1);statusPanel(root,headline,detail);
  if(id==0&&solo&&win<0){liveChessScore=text(coach!=null&&coachSeq==state.optInt("seq")&&coachSession.equals(session)?"LIVE · "+coach.score:turn==me?"Evaluating position…":"Score updates on your turn",12,GREEN);liveChessScore.setMaxLines(1);liveChessScore.setAutoSizeTextTypeUniformWithConfiguration(10,12,1,android.util.TypedValue.COMPLEX_UNIT_SP);liveChessScore.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("How to read your score").setMessage("Positive: you are ahead. Negative: you are behind. A score of +1.00 is roughly a pawn-sized advantage, including position—not just captured material. Mate in N names the side with a forced mate. These are time-limited Stockfish estimates, not win probabilities.").setPositiveButton("Got it",null).show());root.addView(liveChessScore,new LinearLayout.LayoutParams(-1,dp(29)));}
  if(id==7&&setup&&!ownReady){ensureDraft();LinearLayout ships=new LinearLayout(this);root.addView(ships);shipButtons.clear();for(int i=0;i<5;i++){final int pick=i;Button b=secondary(""+Game.FLEET[i],()->{ship=pick;updateFleet();});shipButtons.add(b);ships.addView(b,new LinearLayout.LayoutParams(0,dp(43),1));}fleetHint=text("",12,GREEN);fleetHint.setMaxLines(1);root.addView(fleetHint,new LinearLayout.LayoutParams(-1,dp(28)));}
  if(id==7&&!setup){LinearLayout tabs=new LinearLayout(this);root.addView(tabs);footerButton(tabs,fleetTab?"Target sea":"● Target sea",()->{fleetTab=false;renderGame();});footerButton(tabs,fleetTab?"● My fleet":"My fleet",()->{fleetTab=true;renderGame();});}
  addBoard(root,displayState(),animate);
  if(id==0&&solo&&learnMode&&win<0){learningHint=text("COACH  ·  "+lessonText(),12,INK);learningHint.setPadding(dp(12),dp(6),dp(12),dp(6));learningHint.setBackground(shape(0xffe5e9dc,12));learningHint.setMaxLines(3);learningHint.setAutoSizeTextTypeUniformWithConfiguration(10,12,1,android.util.TypedValue.COMPLEX_UNIT_SP);root.addView(learningHint,new LinearLayout.LayoutParams(-1,dp(62)));}
  TextView last=text(state.optString("lastMove","").isEmpty()?(setup?"Your layout stays private.":id==10&&state.optInt("phase")==1?"Mill formed · remove an enemy stone":id==0&&solo&&learnMode&&openingLesson>=0?"Guided lesson · you play White":"First move · starting side chosen randomly"):"LAST  "+state.optString("lastMove"),12,INK);last.setMaxLines(2);last.setEllipsize(android.text.TextUtils.TruncateAt.END);root.addView(last,new LinearLayout.LayoutParams(-1,dp(id==0?36:49)));
  LinearLayout actions=new LinearLayout(this);root.addView(actions);if(id==0&&solo&&learnMode&&win<0){footerButton(actions,"Openings",()->openingLesson(0));if(active()){hintButton=secondary("Hint",()->showCoachHint());hintButton.setTextSize(13);LinearLayout.LayoutParams hintLayout=new LinearLayout.LayoutParams(0,dp(48),1);hintLayout.setMargins(dp(7),0,0,0);actions.addView(hintButton,hintLayout);hintButton.setVisibility(ChessTutor.next(game,openingLesson)!=null||coach!=null&&coachSeq==game.seq?View.VISIBLE:View.INVISIBLE);}}if(id==0&&local&&win<0&&undoPly()>=0)footerButton(actions,"Undo",()->undoChess());if(solo&&!botError.isEmpty())footerButton(actions,"Retry bot",()->{botError="";renderGame();scheduleBot();});if(setup&&active()){if(id==7){footerButton(actions,"Rotate",()->{rotation=rotation==1?10:1;updateFleet();});footerButton(actions,"Shuffle",()->{fleetDraft.randomSetup(0);updateFleet();});fleetReady=button("Ready",()->lockFleet());actions.addView(fleetReady,new LinearLayout.LayoutParams(0,dp(48),1));updateFleet();}else{footerButton(actions,"Shuffle",()->act(-11,0,0));footerButton(actions,"Ready",()->act(-10,0,0));}}else if(active()){if(id==12&&state.optInt("phase")==2)footerButton(actions,"Next turn",()->act(-2,0,5));if(id==14){footerButton(actions,"Roll",()->act(0,0,5));if(state.optInt("phase")>0)footerButton(actions,"Bank "+state.optInt("phase"),()->act(1,0,5));}if(id==13){if(state.optInt("phase")==0)footerButton(actions,"Pass",()->act(-3,0,5));else{if(!state.optJSONArray("prepared").optBoolean(me))footerButton(actions,"Accept score",()->act(-4,0,5));footerButton(actions,"Resume play",()->act(-5,0,5));}}}
  if(win>=0){if(id==0&&!analysisError.isEmpty())footerButton(actions,"Retry analysis",()->{analysisError="";beginAnalysis();renderGame();});if((local||ready)&&pendingGame<0)footerButton(actions,"Replay",()->{if(local)startGame(id);else invite(id);});if(id==0)footerButton(actions,"Review",()->{reviewIndex=1;reviewMode=0;review();});}
  LinearLayout footer=new LinearLayout(this);root.addView(footer);footerButton(footer,"Rules",()->rules(id,0));if(id==0&&local&&win<0&&!game.chessMoves.isEmpty())footerButton(footer,"History",()->{reviewIndex=game.chessMoves.size();reviewMode=1;review();});if(!local&&ready)footerButton(footer,"Chat"+(unread>0?" ("+unread+")":""),()->chat());footerButton(footer,"Room",()->home());if(id==0&&solo&&learnMode&&win<0)updateInlineHint();}
 int piecesInView(int side){int total=0;JSONArray arr=state.optJSONArray("b");for(int i=0;i<(state.optInt("id")==10?24:100);i++){int v=arr.optInt(i);if(side==0?v>0:v<0)total++;}return total;}

 void footerButton(LinearLayout row,String label,Runnable action){row.setBaselineAligned(false);Button b=secondary(label,action);b.setTextSize(13);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(48),1);if(row.getChildCount()>0)lp.setMargins(dp(7),0,0,0);row.addView(b,lp);}
 void review(){reviewing=true;int total=local||host?game.history.size():reviewBoards.length();if(total<2)return;reviewIndex=Math.max(1,Math.min(total-1,reviewIndex));inGame=true;base("","Chess review");LinearLayout header=(LinearLayout)root.getChildAt(0);Button done=(Button)header.getChildAt(header.getChildCount()-1);done.setText("Done");done.setTextSize(12);done.setContentDescription("Back to game");done.setOnClickListener(v->renderGame());int ply=reviewIndex-1;JSONArray played=local||host?array(game.chessMoves.get(ply)):reviewMoves.optJSONArray(reviewIndex);JSONArray best=local||host?(ply<game.analysisBest.size()?array(game.analysisBest.get(ply)):null):reviewBest.optJSONArray(reviewIndex);String report=local||host?(ply<game.analysis.size()?game.analysis.get(ply):""):analysisNotes.optString(reviewIndex);ChessReviewText presentation=ChessReviewText.from(report);report=presentation.report;String[] lines=report.split("\n");String verdict=report.isEmpty()?(game!=null&&game.winner<0?"Move history":analysisError.isEmpty()?"Stockfish analyzing…":"Analysis paused"):lines[0];String moveLine=lines.length>2?lines[1]+"   ·   "+lines[2]:local||host?"Played: "+ChessNotation.san(ChessAnalysis.position(game,ply),game.chessMoves.get(ply)[0],game.chessMoves.get(ply)[1],game.chessMoves.get(ply)[2]):"Analysis appears after the match";statusPanel(root,(ply/2+1)+(ply%2==0?". White":"… Black")+" · "+verdict,moveLine);
  JSONArray before=local||host?array(game.history.get(ply)):reviewBoards.optJSONArray(ply);JSONArray shown=before;boolean after=reviewMode==1;if(after)shown=local||host?array(game.history.get(reviewIndex)):reviewBoards.optJSONArray(reviewIndex);JSONObject position=obj("id",0,"b",shown,"aux",new JSONArray(),"moves",new JSONArray(),"winner",2,"turn",ply%2);try{if(played!=null&&reviewMode!=2){position.put("playedFrom",played.optInt(0,-1));position.put("playedTo",played.optInt(1,-1));}if(best!=null&&reviewMode!=1){position.put("bestFrom",best.optInt(0,-1));position.put("bestTo",best.optInt(1,-1));}}catch(Exception ignored){}addBoard(root,position,false);
  TextView legend=text(reviewMode==1?"Position after the played move · orange arrow":reviewMode==2?"Before the move · green = best move found":"Orange = played · green = best",11,MUTED);legend.setMaxLines(1);root.addView(legend,new LinearLayout.LayoutParams(-1,dp(24)));final String shownReport=report;LinearLayout scoreRow=new LinearLayout(this);root.addView(scoreRow,new LinearLayout.LayoutParams(-1,dp(60)));reviewScore(scoreRow,"AFTER PLAYED",report.isEmpty()&&game!=null&&game.winner<0?"After game":presentation.playedScore);reviewScore(scoreRow,"BEST FOUND",report.isEmpty()&&game!=null&&game.winner<0?"After game":presentation.bestScore);TextView perspective=text(presentation.side.isEmpty()?"Analysis details ›":"Scores for "+presentation.side+" · positive is better · Details ›",10,GREEN);perspective.setMaxLines(1);perspective.setOnClickListener(v->analysisDetails(shownReport,4));root.addView(perspective,new LinearLayout.LayoutParams(-1,dp(27)));TextView summary=text(report.isEmpty()&&game!=null&&game.winner<0?"Explore your moves or branch from this position. Full analysis is available after the match.":presentation.reason,12,INK);summary.setMaxLines(2);summary.setAutoSizeTextTypeUniformWithConfiguration(10,12,1,android.util.TypedValue.COMPLEX_UNIT_SP);summary.setOnClickListener(v->analysisDetails(shownReport,3));root.addView(summary,new LinearLayout.LayoutParams(-1,dp(36)));LinearLayout modes=new LinearLayout(this);root.addView(modes);footerButton(modes,"Compare",()->{reviewMode=0;review();});footerButton(modes,"Played",()->{reviewMode=1;review();});footerButton(modes,"Best",()->{reviewMode=2;review();});for(int i=0;i<3;i++){Button tab=(Button)modes.getChildAt(i);tab.setTextColor(i==reviewMode?Color.WHITE:INK);tab.setBackground(surface(i==reviewMode?INK:0xfffffcf5,i==reviewMode?0:0xffdeddd2,12));}LinearLayout nav=new LinearLayout(this);nav.setBaselineAligned(false);root.addView(nav,new LinearLayout.LayoutParams(-1,dp(48)));reviewArrow(nav,"‹",reviewIndex>1,()->{reviewIndex--;review();});TextView step=text(reviewIndex+"/"+(total-1),11,INK);step.setGravity(Gravity.CENTER);boolean branchable=local&&!(reviewMode==1&&reviewIndex==total-1&&game.winner>=0);nav.addView(step,branchable?new LinearLayout.LayoutParams(dp(48),dp(48)):new LinearLayout.LayoutParams(0,dp(48),1));reviewArrow(nav,"›",reviewIndex<total-1,()->{reviewIndex++;review();});if(branchable){Button play=button("Play from here",()->continueReview());play.setTextSize(13);LinearLayout.LayoutParams playLayout=new LinearLayout.LayoutParams(0,dp(48),1);playLayout.leftMargin=dp(7);nav.addView(play,playLayout);}}
 void reviewArrow(LinearLayout row,String label,boolean available,Runnable action){View v=available?secondary(label,action):new View(this);row.addView(v,new LinearLayout.LayoutParams(dp(44),dp(48)));}

 void reviewScore(LinearLayout row,String label,String value){LinearLayout card=new LinearLayout(this);card.setOrientation(1);card.setPadding(dp(10),dp(2),dp(10),dp(2));card.setBackground(shape(Color.WHITE,12));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-1,1);if(row.getChildCount()>0)lp.setMargins(dp(8),0,0,0);row.addView(card,lp);TextView title=text(label,9,MUTED);card.addView(title,new LinearLayout.LayoutParams(-1,dp(24)));TextView score=text(value,16,INK);score.setTypeface(null,Typeface.BOLD);score.setMaxLines(1);score.setAutoSizeTextTypeUniformWithConfiguration(10,16,1,android.util.TypedValue.COMPLEX_UNIT_SP);card.addView(score,new LinearLayout.LayoutParams(-1,dp(32)));}
 void analysisDetails(String report,int page){String[] lines=report.isEmpty()?new String[]{"Analysis is still running."}:report.split("\\n");int p=Math.max(0,Math.min(lines.length-1,page));AlertDialog.Builder d=new AlertDialog.Builder(this).setTitle("Analysis · "+(p+1)+"/"+lines.length).setMessage(lines[p]).setNegativeButton("Close",null);if(p>0)d.setNeutralButton("Previous",(x,w)->analysisDetails(report,p-1));if(p+1<lines.length)d.setPositiveButton("Next",(x,w)->analysisDetails(report,p+1));d.show();}

 void chat(){chatPage=0;showChat();}
 void showChat(){if(!ready||local)return;unread=0;if(chatDialog!=null){chatDialog.setOnDismissListener(null);chatDialog.dismiss();}LinearLayout box=new LinearLayout(this);box.setOrientation(1);box.setPadding(dp(16),dp(6),dp(16),dp(6));int pages=Math.max(1,chats.size());chatPage=Math.max(0,Math.min(chatPage,pages-1));String message=chats.isEmpty()?"Say hello. Messages stay on Bluetooth.":chats.get(chats.size()-1-chatPage);chatText=text(message,14,INK);chatText.setMaxLines(12);chatText.setAutoSizeTextTypeUniformWithConfiguration(11,14,1,android.util.TypedValue.COMPLEX_UNIT_SP);box.addView(chatText,new LinearLayout.LayoutParams(-1,dp(200)));LinearLayout nav=new LinearLayout(this);box.addView(nav);if(chatPage+1<pages)footerButton(nav,"Older",()->{chatPage++;showChat();});TextView pageLabel=text((pages-chatPage)+"/"+pages,12,MUTED);pageLabel.setGravity(Gravity.CENTER);nav.addView(pageLabel,new LinearLayout.LayoutParams(0,dp(48),1));if(chatPage>0)footerButton(nav,"Newer",()->{chatPage--;showChat();});EditText input=new EditText(this);input.setHint("Message…");input.setSingleLine(true);input.setFilters(new android.text.InputFilter[]{new android.text.InputFilter.LengthFilter(300)});box.addView(input);chatDialog=new AlertDialog.Builder(this).setTitle("Bluetooth chat").setView(box).setNegativeButton("Close",null).setPositiveButton("Send",null).create();chatDialog.setOnShowListener(d->chatDialog.getButton(-1).setOnClickListener(v->{String body=input.getText().toString().trim();if(!body.isEmpty()&&ready){sendChat(body);chatPage=0;input.setText("");showChat();}}));chatDialog.setOnDismissListener(d->{chatText=null;if(inGame)renderGame();else home();});chatDialog.show();}
 void sendChat(String body){if(!ready||local||body.trim().isEmpty()||body.length()>300)return;send(obj("type","chat","text",body));appendChat("You: "+body,false);}
 void appendChat(String value,boolean incoming){chats.add(value);while(chats.size()>100)chats.remove(0);if(chatText!=null){chatText.setText(value);chatPage=0;}else if(incoming){unread++;toast("New Bluetooth message");if(inGame)renderGame();else home();}save();}

 boolean canAnalyzeChessGame(){return game!=null&&game.id==0&&game.winner>=0;}
 void beginAnalysis(){if(!canAnalyzeChessGame()||session.equals(analyzing)||!analysisError.isEmpty())return;if(!game.analysis.isEmpty()&&!game.analysis.get(0).contains(StockfishEngine.NAME)){game.analysis.clear();game.analysisBest.clear();}if(game.analysis.size()>=game.chessMoves.size())return;final Game match=game.copy();final String token=session;analyzing=token;worker.execute(()->{try{for(int ply=match.analysis.size();ply<match.chessMoves.size();ply++){if(destroyed||!token.equals(analyzing))return;final int index=ply;final StockfishEngine.Review result=getStockfish().analyze(match,ply);handler.post(()->{if(game==null||!token.equals(session)||destroyed)return;if(game.analysis.size()==index){game.analysis.add(result.text);game.analysisBest.add(result.best);}if(!local&&host&&ready)send(obj("type","analysis","session",session,"index",index+1,"result",result.text,"best",array(result.best)));save();if(reviewing)review();});}}catch(Exception e){android.util.Log.e("TrailLink","Stockfish analysis failed",e);handler.post(()->{if(token.equals(session)&&!destroyed){analysisError="Stockfish analysis paused; return to the result and tap Retry analysis.";toast(analysisError);if(reviewing)review();else renderGame();}});}finally{handler.post(()->{if(token.equals(analyzing))analyzing="";});}});}


 void choosePromotion(int a,int z){new AlertDialog.Builder(this).setTitle("Promote your pawn").setItems(new String[]{"Queen","Rook","Bishop","Knight"},(d,w)->act(a,z,new int[]{5,4,3,2}[w])).show();}
 void nim(int pile,int amount){String[] choices=new String[amount];for(int i=0;i<amount;i++)choices[i]="Take "+(i+1);new AlertDialog.Builder(this).setTitle("Remove from pile "+(pile+1)).setItems(choices,(d,w)->act(pile,w+1,5)).show();}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}void confirm(String title,String msg,Runnable yes){new AlertDialog.Builder(this).setTitle(title).setMessage(msg).setPositiveButton("Continue",(d,w)->yes.run()).setNegativeButton("Cancel",null).show();}
 @Override public void onBackPressed(){if(rtsVisible){rtsMenu();return;}if(reviewing)renderGame();else if(inGame)home();else super.onBackPressed();}
 void save(){getSharedPreferences("coach",0).edit().putString("session",session).putBoolean("learn",learnMode).putInt("lesson",openingLesson).apply();try{java.io.File tmp=new java.io.File(getFilesDir(),"match.tmp");try(java.io.ObjectOutputStream out=new java.io.ObjectOutputStream(new java.io.FileOutputStream(tmp))){out.writeInt(3);out.writeBoolean(local);out.writeBoolean(host);out.writeBoolean(solo);out.writeInt(me);out.writeInt(botLevel);out.writeUTF(session);out.writeUTF(savedPeer);out.writeObject(game);out.writeObject(bot);out.writeObject(state==null?"":state.toString());out.writeObject(chats);out.writeObject(reviewBoards.toString());out.writeObject(reviewNotes.toString());out.writeObject(analysisNotes.toString());out.writeObject(reviewMoves.toString());out.writeObject(reviewBest.toString());}java.nio.file.Files.move(tmp.toPath(),new java.io.File(getFilesDir(),"match.bin").toPath(),java.nio.file.StandardCopyOption.REPLACE_EXISTING);}catch(Exception e){android.util.Log.e("TrailLink","Could not save match",e);toast("Could not save match. Keep the app open.");}}
 @SuppressWarnings("unchecked") void restore(){java.io.File file=new java.io.File(getFilesDir(),"match.bin");if(!file.exists())return;try(java.io.ObjectInputStream in=new java.io.ObjectInputStream(new java.io.FileInputStream(file))){if(in.readInt()!=3){toast("Version 3 uses new match rules. Your old match cannot be resumed.");return;}local=in.readBoolean();host=in.readBoolean();solo=in.readBoolean();me=in.readInt();botLevel=in.readInt();session=in.readUTF();savedPeer=in.readUTF();game=(Game)in.readObject();bot=(Bot)in.readObject();String json=(String)in.readObject();state=json.isEmpty()?null:new JSONObject(json);passSwap=state!=null&&state.optBoolean("passSwap");chats=(ArrayList<String>)in.readObject();reviewBoards=new JSONArray((String)in.readObject());reviewNotes=new JSONArray((String)in.readObject());analysisNotes=new JSONArray((String)in.readObject());reviewMoves=new JSONArray((String)in.readObject());reviewBest=new JSONArray((String)in.readObject());android.content.SharedPreferences coachPrefs=getSharedPreferences("coach",0);learnMode=solo&&game!=null&&game.id==0&&session.equals(coachPrefs.getString("session",""))&&coachPrefs.getBoolean("learn",false);openingLesson=learnMode?coachPrefs.getInt("lesson",-1):-1;if(state!=null)status=local?"Saved offline match":"Saved match • reconnect to resume";}catch(Exception e){game=null;state=null;session="";savedPeer="";local=solo=false;android.util.Log.e("TrailLink","Could not restore match",e);}}

 void chooseRts(){if(local&&!solo){new AlertDialog.Builder(this).setTitle("Real-time skirmish").setMessage("Rift Command needs simultaneous commanders. Play against a bot or use two Bluetooth phones.").setPositiveButton("Play bot",(d,w)->{solo=true;chooseRts();}).setNegativeButton("Cancel",null).show();return;}String[] choices={"Bastion · durable structures","Flux · faster units and training"};new AlertDialog.Builder(this).setTitle("Rift Command · choose doctrine").setItems(choices,(d,w)->{rtsDoctrine=w;new AlertDialog.Builder(this).setTitle("Choose battlefield").setItems(new String[]{"The Divide · central passage","Northfall · two fronts","Ash Basin · southern route"},(a,b)->{rtsMap=b;if(local)startGame(15);else invite(15);}).show();}).show();}
 void leaveRts(){if(rtsVisible){rtsVisible=false;rtsPresence();if(game!=null&&game.id==15)save();}rtsView=null;}
 boolean rtsIsPaused(){return !rtsForeground||!rtsVisible||rtsPaused||!local&&(!ready||!link.connected||!rtsPeerActive);}
 void rtsPresence(){if(!local&&ready&&!host&&state!=null&&state.optInt("id")==15)send(obj("type","rts_presence","session",session,"active",rtsVisible&&rtsForeground&&!rtsPaused));}
 void showRts(){if(state==null)return;rtsCommand=Math.max(rtsCommand,state.optLong("ack"));boolean already=rtsVisible&&rtsView!=null;inGame=true;reviewing=false;gameScreen=false;rtsVisible=true;if(already){rtsView.update(state);return;}setRequestedOrientation(android.content.pm.ActivityInfo.SCREEN_ORIENTATION_SENSOR_LANDSCAPE);getWindow().setStatusBarColor(RiftView.BG);getWindow().setNavigationBarColor(RiftView.BG);getWindow().getDecorView().setSystemUiVisibility(0);if(Build.VERSION.SDK_INT>=30)getWindow().getInsetsController().setSystemBarsAppearance(0,WindowInsetsController.APPEARANCE_LIGHT_STATUS_BARS|WindowInsetsController.APPEARANCE_LIGHT_NAVIGATION_BARS);board=null;root=new LinearLayout(this);root.setOrientation(1);root.setLayoutDirection(View.LAYOUT_DIRECTION_LTR);root.setBackgroundColor(RiftView.BG);root.setOnApplyWindowInsetsListener((v,ins)->{int l=ins.getSystemWindowInsetLeft(),t=ins.getSystemWindowInsetTop(),r=ins.getSystemWindowInsetRight(),b=ins.getSystemWindowInsetBottom();if(Build.VERSION.SDK_INT>=30){android.graphics.Insets safe=ins.getInsets(WindowInsets.Type.systemBars()|WindowInsets.Type.displayCutout());l=safe.left;t=safe.top;r=safe.right;b=safe.bottom;}v.setPadding(l+dp(8),t,r+dp(8),b);return ins;});rtsView=new RiftView(this,state);root.addView(rtsView,new LinearLayout.LayoutParams(-1,-1));setContentView(root);root.requestApplyInsets();rtsPresence();scheduleRts();}
 void scheduleRts(){if(rtsLoopScheduled||destroyed||game==null||game.id!=15||!(local||host))return;rtsLoopScheduled=true;handler.postDelayed(()->{rtsLoopScheduled=false;if(destroyed||game==null||game.id!=15)return;if(!rtsIsPaused()&&game.rts.winner<0){game.rts.step();if(solo)game.rts.bot(1-me,botLevel);game.seq=game.rts.tick;game.winner=game.rts.winner;}if(game.rts.tick%2==0||rtsIsPaused())publishRts();if(game.winner>=0?rtsLastSave!=-2:game.rts.tick/50!=rtsLastSave){rtsLastSave=game.winner>=0?-2:game.rts.tick/50;save();}scheduleRts();},100);}
 void publishRts(){if(game==null||game.id!=15)return;state=snapshot(me);if(rtsVisible&&rtsView!=null)rtsView.update(state);sendSnapshot();}
 void rtsOrder(int action,int[] ids,int unit,int x,int y){if(state==null||state.optInt("id")!=15||state.optBoolean("paused")||!rtsVisible||rtsPaused||!local&&!ready)return;if(local||host){rtsCommand=Math.max(rtsCommand,game.rts.lastCommand[me]);game.rts.issue(me,++rtsCommand,action,ids,unit,x,y);publishRts();}else send(obj("type","rts_order","session",session,"command",++rtsCommand,"action",action,"ids",array(ids),"unit",unit,"x",x,"y",y));}
 void rtsDialog(AlertDialog.Builder builder){final int generation=++rtsDialogVersion;rtsPaused=true;rtsPresence();AlertDialog dialog=builder.create();dialog.setOnDismissListener(d->{if(generation==rtsDialogVersion){rtsPaused=false;rtsPresence();}});dialog.show();}
 void rtsMenu(){rtsDialog(new AlertDialog.Builder(this).setTitle("Rift Command · paused").setItems(local?new String[]{"Resume battle","Save and return to room","Surrender"}:new String[]{"Resume battle","Save and return to room","Bluetooth chat","Surrender"},(d,w)->{if(w==1)home();if(w==2&&!local&&ready)chat();if(w==(local?2:3)){if(local||host){game.rts.winner=game.winner=1-me;publishRts();save();}else send(obj("type","rts_resign","session",session));}}));}
 void rtsHelp(int page){String[] help={"Select a harvester, choose Build, then tap clear visible ground. Blue crystals provide ore. Build an extractor on a green vent, then use Gather on it for gas. Workers carry resources back to a command core. Use another worker to finish an abandoned site with Repair.",
 "Supply relays let you field larger armies (up to 100 supply). Barracks produce Rangers. A Foundry unlocks Rovers; add a Research lab for Siege crawlers and Menders. A Skyport produces flying Wraithwings. Queue up to five orders. Research weapons and armor at a lab.",
 "Tap your units to select. Army or Workers selects a group; Box select lets you drag a selection rectangle. Use Attack move, then tap a destination. Drag to pan, pinch or use +/− to zoom, and tap the minimap to jump. Destroy all enemy structures to win. Both phones must stay in battle; leaving or disconnecting pauses it."};int p=Math.floorMod(page,help.length);rtsDialog(new AlertDialog.Builder(this).setTitle("Field manual · "+(p+1)+"/3").setMessage(help[p]).setPositiveButton("Done",null).setNeutralButton("Next",(d,w)->rtsHelp(p+1)));}
 void rtsRematch(){if(local)chooseRts();else if(ready)invite(15);}
 @Override protected void onPause(){rtsForeground=false;rtsPresence();if(game!=null&&game.id==15){publishRts();save();}super.onPause();}
 @Override protected void onResume(){super.onResume();rtsForeground=true;rtsPresence();scheduleRts();}

 @Override protected void onStop(){save();super.onStop();}
 @Override protected void onDestroy(){destroyed=true;handler.removeCallbacksAndMessages(null);worker.shutdownNow();if(stockfish!=null)stockfish.close();try{unregisterReceiver(receiver);}catch(Exception ignored){}link.close();link.writer.shutdownNow();super.onDestroy();}
}
