package com.traillink;

import android.view.*;import android.graphics.*;import org.json.*;import java.util.*;

/** Native, resolution-independent board drawing. No external images or fonts. */
public final class BoardView extends View {
 final MainActivity app;JSONObject s;final int id,me;final int[] b=new int[200],aux=new int[200];final ArrayList<int[]> moves=new ArrayList<>();final Paint p=new Paint(3);final ArrayList<RectF> hit=new ArrayList<>();int selected=-1;float w,ox,oy;int[] animationBoard;long animationStart;int animationSeq=-1;
 final ChessPieces chessPieces=new ChessPieces();
 final int CREAM=0xffe7edf8,DARK=0xff5875a6,TEAL=0xff75d5ad,ORANGE=0xffffbc7b;
 public BoardView(MainActivity a,JSONObject state,int player){super(a);app=a;id=state.optInt("id");me=player;update(state,false);setFocusable(true);}
 public void update(JSONObject state,boolean animate){s=state;JSONArray arr=s.optJSONArray("b"),other=s.optJSONArray("aux");for(int i=0;i<200;i++){b[i]=arr==null?0:arr.optInt(i);aux[i]=other==null?0:other.optInt(i);}moves.clear();JSONArray legal=s.optJSONArray("moves");if(legal!=null)for(int i=0;i<legal.length();i++){JSONArray m=legal.optJSONArray(i);moves.add(new int[]{m.optInt(0),m.optInt(1)});}if(animate&&id==9&&s.optInt("seq")!=animationSeq&&s.optJSONArray("before")!=null&&s.optJSONArray("before").length()>=14){animationSeq=s.optInt("seq");animationBoard=new int[14];for(int i=0;i<14;i++)animationBoard[i]=s.optJSONArray("before").optInt(i);animationStart=android.os.SystemClock.uptimeMillis();}setContentDescription(Game.NAMES[id]+". "+s.optString("lastMove"));invalidate();}
 public int heightDp(){return 320;}
 float ratio(){return id==9?.70f:id==11?.7f:id==14?.46f:id==4?.86f:1;}
 @Override protected void onMeasure(int ws,int hs){int width=MeasureSpec.getSize(ws),available=MeasureSpec.getSize(hs);int height=MeasureSpec.getMode(hs)==MeasureSpec.UNSPECIFIED?(int)(width*ratio()):available;setMeasuredDimension(width,height);}
 public boolean animating(){return animationBoard!=null&&android.os.SystemClock.uptimeMillis()-animationStart<animationDuration();}
 long animationDuration(){JSONArray path=s.optJSONArray("sow");return path==null?0:Math.min(3000,450+path.length()*160);}
 void rect(RectF r,int color,float radius){p.setColor(color);p.setStyle(Paint.Style.FILL);if(radius==0)canvas.drawRect(r,p);else canvas.drawRoundRect(r,radius,radius,p);}Canvas canvas;
 void label(String txt,float x,float y,float size,int color){p.setStyle(Paint.Style.FILL);p.setColor(color);p.setTypeface(Typeface.create("sans-serif-medium",Typeface.NORMAL));p.setTextSize(size);p.setTextAlign(Paint.Align.CENTER);canvas.drawText(txt,x,y-(p.ascent()+p.descent())/2,p);}
 void line(float x,float y,float z,float t,int color,float stroke){p.setColor(color);p.setStrokeWidth(stroke);p.setStrokeCap(Paint.Cap.ROUND);canvas.drawLine(x,y,z,t,p);}
 void disc(float x,float y,float r,int color){p.setStyle(Paint.Style.FILL);p.setColor(color);canvas.drawCircle(x,y,r,p);}
 boolean target(int i){for(int[] m:moves)if(selected>=0?m[0]==selected&&m[1]==i:m[0]==i)return true;return false;}
 @Override protected void onDraw(Canvas c){super.onDraw(c);canvas=c;w=Math.min(getWidth(),getHeight()/ratio());ox=(getWidth()-w)/2;oy=(getHeight()-w*ratio())/2;c.save();c.translate(ox,oy);hit.clear();if(id==8){dots();finishBoard();return;}if(id==9){mancala();finishBoard();return;}if(id==10){morris();finishBoard();return;}if(id==11){nim();finishBoard();return;}if(id==13){go();finishBoard();return;}if(id==14){dice();finishBoard();return;}int cols=id==6?11:id==4?7:id==5?3:id==1||id==7?10:id==12?4:8,rows=id==4?6:cols;float cell=w/cols;for(int i=0;i<cols*rows;i++){int logical=(me==1&&(id==0||id==1||id==2))?cols*rows-1-i:i;float x=i%cols*cell,y=i/cols*cell;RectF r=id==0?new RectF(x,y,x+cell,y+cell):new RectF(x+1,y+1,x+cell-1,y+cell-1);while(hit.size()<=logical)hit.add(new RectF());hit.set(logical,r);int background=(id==0||id==2)?((i/cols+i%cols)%2==0?CREAM:DARK):id==7?0xffdce8e7:id==12?TEAL:0xffe4e8dc;if(logical==selected||s.optJSONArray("changed")!=null&&contains(s.optJSONArray("changed"),logical))background=0xfff0c583;if(logical==s.optInt("playedFrom",-9)||logical==s.optInt("playedTo",-9))background=0xffffd3bd;if(id==1&&Game.lake(logical))background=0xffbadbdf;rect(r,background,id==0||id==2?0:cell*.12f);
   int v=id==7&&!s.optBoolean("setup")&&app.fleetTab?b[100+logical]:b[logical];if(id==0){if(logical==s.optInt("hintFrom",-9))rect(r,0x9975d5ad,0);if(v!=0)chessPieces.draw(canvas,v,x+cell/2,y+cell/2,cell*.93f);}
   else if(id==1){if(v!=0){disc(x+cell/2,y+cell/2,cell*.38f,v>0?TEAL:ORANGE);String val=Math.abs(v)==13?"?":Math.abs(v)==11?"B":Math.abs(v)==12?"F":Math.abs(v)==1?"S":""+Math.abs(v);label(val,x+cell/2,y+cell/2,cell*.42f,Color.WHITE);}}
   else if(id==7&&s.optBoolean("setup")){if(v>0){rect(r,v==app.ship+1?0xffe4b46f:TEAL,cell*.1f);label(""+v,x+cell/2,y+cell/2,cell*.43f,Color.WHITE);}}
   else if(id==7){if(app.fleetTab&&v==2)disc(x+cell/2,y+cell/2,cell*.25f,TEAL);if(v==3)label("×",x+cell/2,y+cell/2,cell*.7f,0xffb2503b);if(v==1)label("·",x+cell/2,y+cell/2,cell*.9f,0xff7e9995);if(v==2&&!app.fleetTab)label("×",x+cell/2,y+cell/2,cell*.7f,0xffb2503b);}
   else if(id==12){if(v!=0){rect(r,aux[logical]>=2?(aux[logical]==2?0xffc6e0c8:0xfff0d4b3):0xfff0e6c9,cell*.12f);label(new String[]{"","★","●","▲","◆","☀","♥","✿","☾"}[v],x+cell/2,y+cell/2,cell*.5f,TEAL);}else label("✦",x+cell/2,y+cell/2,cell*.3f,0xffaacbb6);}
   else if(id==5){if(v!=0)label(v==1?"×":"○",x+cell/2,y+cell/2,cell*.72f,v==1?TEAL:ORANGE);}
   else if(v!=0){disc(x+cell/2,y+cell/2,cell*.37f,v>0?TEAL:ORANGE);if(id==2&&Math.abs(v)==2)label("K",x+cell/2,y+cell/2,cell*.4f,Color.WHITE);}
   if(target(logical)&&(selected>=0||id==3)){if(v==0)disc(x+cell/2,y+cell/2,cell*.10f,0xff5eaa80);else{p.setColor(0xfff4c069);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(3);canvas.drawRoundRect(r,cell*.12f,cell*.12f,p);p.setStyle(Paint.Style.FILL);}}
  }
  if(id==0){for(int i=0;i<8;i++){int tone=(i%2==0)?0x8897a9cb:0x88edf3ff;label(""+(char)('a'+(me==1?7-i:i)),(i+.87f)*cell,8*cell-cell*.10f,cell*.15f,tone);label(""+(me==1?i+1:8-i),cell*.10f,(i+.15f)*cell,cell*.15f,tone);}arrowCells(s.optInt("playedFrom",-1),s.optInt("playedTo",-1),0xdddc6b45);arrowCells(s.optInt("bestFrom",-1),s.optInt("bestTo",-1),0xee218c75);}
  finishBoard();
 }
 boolean contains(JSONArray arr,int n){for(int i=0;i<arr.length();i++)if(arr.optInt(i)==n)return true;return false;}
 void finishBoard(){if(id!=0){int at=s.optInt("lastA",-1);if(at>=0&&at<hit.size()&&!(id==7&&s.optInt("lastPlayer")!=me&&!app.fleetTab)&&!(id==7&&s.optInt("lastPlayer")==me&&app.fleetTab)){RectF r=hit.get(at);p.setStyle(Paint.Style.STROKE);p.setColor(0xffd99c3c);p.setStrokeWidth(app.dp(2));canvas.drawRoundRect(r,6,6,p);p.setStyle(Paint.Style.FILL);}}canvas.restore();for(RectF r:hit)r.offset(ox,oy);}
 void arrowCells(int a,int z,int color){if(a<0||z<0||a>=hit.size()||z>=hit.size())return;RectF from=hit.get(a),to=hit.get(z);arrow(from.centerX(),from.centerY(),to.centerX(),to.centerY(),color,w*.018f);}
 void arrow(float x,float y,float tx,float ty,int color,float stroke){float dx=tx-x,dy=ty-y,len=(float)Math.hypot(dx,dy);if(len<1)return;dx/=len;dy/=len;line(x,y,tx-dx*stroke,ty-dy*stroke,color,stroke);Path head=new Path();head.moveTo(tx,ty);head.lineTo(tx-dx*stroke*3-dy*stroke*1.7f,ty-dy*stroke*3+dx*stroke*1.7f);head.lineTo(tx-dx*stroke*3+dy*stroke*1.7f,ty-dy*stroke*3-dx*stroke*1.7f);head.close();p.setColor(color);p.setStyle(Paint.Style.FILL);canvas.drawPath(head,p);}
 void go(){float pad=w*.065f,step=(w-2*pad)/8;rect(new RectF(0,0,w,w),0xffe6c995,16);for(int i=0;i<9;i++){line(pad,pad+i*step,w-pad,pad+i*step,0xff705c3d,2);line(pad+i*step,pad,pad+i*step,w-pad,0xff705c3d,2);}for(int r:new int[]{2,4,6})for(int col:new int[]{2,4,6})disc(pad+col*step,pad+r*step,w*.005f,0xff705c3d);for(int i=0;i<81;i++){float x=pad+i%9*step,y=pad+i/9*step;hit.add(new RectF(x-step*.46f,y-step*.46f,x+step*.46f,y+step*.46f));if(b[i]!=0){disc(x+1,y+2,step*.44f,0x33000000);disc(x,y,step*.43f,b[i]>0?0xff182626:0xfffafbf7);if(aux[i]==1)label("×",x,y,step*.65f,0xffdd6447);}}}

 void dots(){float pad=w*.08f,step=w*.21f;for(int r=0;r<4;r++)for(int col=0;col<4;col++){int own=aux[r*4+col];if(own>0)rect(new RectF(pad+col*step+4,pad+r*step+4,pad+(col+1)*step-4,pad+(r+1)*step-4),own==1?0xffc9e1ce:0xfff2d9bd,5);}for(int i=0;i<40;i++){float x,y,z,t;if(i<20){x=pad+i%4*step;y=pad+i/4*step;z=x+step;t=y;}else{x=pad+(i-20)%5*step;y=pad+(i-20)/5*step;z=x;t=y+step;}hit.add(new RectF(Math.min(x,z)-step*.17f,Math.min(y,t)-step*.17f,Math.max(x,z)+step*.17f,Math.max(y,t)+step*.17f));line(x,y,z,t,b[i]==0?0xffc7d0c3:b[i]==1?TEAL:ORANGE,b[i]==0?3:7);}for(int r=0;r<5;r++)for(int col=0;col<5;col++)disc(pad+col*step,pad+r*step,5,TEAL);}
 void mancala(){int[] shown=b;int sowAt=-1;if(animating()){shown=animationBoard.clone();int from=s.optInt("lastA");if(from>=0&&from<14)shown[from]=0;JSONArray path=s.optJSONArray("sow");int steps=Math.min(path.length(),(int)((android.os.SystemClock.uptimeMillis()-animationStart)/Math.max(50,(animationDuration()-450)/Math.max(1,path.length()))));for(int i=0;i<steps;i++){sowAt=path.optInt(i);shown[sowAt]++;}postInvalidateDelayed(32);}else animationBoard=null;rect(new RectF(0,w*.07f,w,w*.58f),0xffe6d6b8,w*.08f);for(int i=0;i<14;i++){float x,y,rx=w*.052f,ry=w*.09f;if(i==6||i==13){x=i==6?w*.94f:w*.06f;y=w*.325f;ry=w*.21f;}else{int index=i<6?i:12-i;x=w*.19f+index*w*.123f;y=i<6?w*.45f:w*.20f;}RectF r=new RectF(x-rx,y-ry,x+rx,y+ry);hit.add(r);rect(r,i==6||i==13?0xffcbb993:0xfff5eedf,w*.05f);label(""+shown[i],x,y,w*.055f,TEAL);if(i==sowAt){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(4);p.setColor(ORANGE);canvas.drawOval(r,p);p.setStyle(Paint.Style.FILL);}if(target(i))disc(x,y+ry*.72f,3,ORANGE);}if(animating()){JSONArray path=s.optJSONArray("sow");float interval=Math.max(50,(animationDuration()-450)/(float)Math.max(1,path.length()));float progress=(android.os.SystemClock.uptimeMillis()-animationStart)/interval;int index=(int)progress;if(index<path.length()){int from=index==0?s.optInt("lastA"):path.optInt(index-1),to=path.optInt(index);if(from>=0&&from<14&&to>=0&&to<14){RectF a=hit.get(from),z=hit.get(to);float f=progress-index;disc(a.centerX()+(z.centerX()-a.centerX())*f,a.centerY()+(z.centerY()-a.centerY())*f-(float)Math.sin(f*Math.PI)*w*.06f,w*.025f,ORANGE);label("Sowing · "+(path.length()-index)+" in hand",w*.5f,w*.325f,w*.03f,TEAL);}}}arrow(w*.23f,w*.64f,w*.78f,w*.64f,TEAL,w*.012f);arrow(w*.78f,w*.02f,w*.23f,w*.02f,TEAL,w*.012f);}
 static final int[][] MORRIS_POS={{0,0},{3,0},{6,0},{1,1},{3,1},{5,1},{2,2},{3,2},{4,2},{0,3},{1,3},{2,3},{4,3},{5,3},{6,3},{2,4},{3,4},{4,4},{1,5},{3,5},{5,5},{0,6},{3,6},{6,6}};
 float mx(int i){return w*(.08f+MORRIS_POS[i][0]*.14f);}float my(int i){return w*(.08f+MORRIS_POS[i][1]*.14f);}
 void morris(){for(int i=0;i<24;i++)for(int j:Game.LINKS[i])if(j>i)line(mx(i),my(i),mx(j),my(j),0xffa6b6a2,3);for(int i=0;i<24;i++){float x=mx(i),y=my(i),r=w*.045f;hit.add(new RectF(x-r*1.3f,y-r*1.3f,x+r*1.3f,y+r*1.3f));disc(x,y,r,b[i]==0?0xffd9e2d2:b[i]>0?TEAL:ORANGE);if(selected==i){p.setStyle(Paint.Style.STROKE);p.setColor(0xffb07735);p.setStrokeWidth(4);canvas.drawCircle(x,y,r*1.2f,p);p.setStyle(Paint.Style.FILL);}if(target(i))disc(x,y,b[i]==0?4:2,0xffeeaf61);}}
 void nim(){for(int i=0;i<3;i++){RectF r=new RectF(0,i*w*.22f+5,w,(i+1)*w*.22f-5);hit.add(r);rect(r,0xffe4e8dc,14);label(""+(i+1),w*.07f,r.centerY(),w*.06f,MUTED());for(int j=0;j<b[i];j++)disc(w*.20f+j*w*.11f,r.centerY(),w*.038f,TEAL);if(b[i]==0)label("Empty",w*.5f,r.centerY(),w*.045f,MUTED());}}
 int MUTED(){return 0xff738272;}
 void dice(){rect(new RectF(0,6,w,w*.44f),0xffe4e8dc,20);JSONArray count=s.optJSONArray("count");int die=count.optInt(0);label(die==0?"Ready to roll":"⚄  Last roll: "+die,w/2,w*.12f,w*.068f,TEAL);label(""+s.optInt("phase"),w/2,w*.27f,w*.15f,TEAL);label("UNBANKED THIS TURN",w/2,w*.39f,w*.032f,MUTED());}
 @Override public boolean onTouchEvent(android.view.MotionEvent event){if(event.getAction()!=MotionEvent.ACTION_UP)return true;performClick();if(s.optInt("winner")!=-1||!app.active()||animating()||id==7&&!s.optBoolean("setup")&&app.fleetTab)return true;int a=-1;float best=Float.MAX_VALUE;for(int i=0;i<hit.size();i++)if(hit.get(i).contains(event.getX(),event.getY())){RectF r=hit.get(i);float dist=(r.centerX()-event.getX())*(r.centerX()-event.getX())+(r.centerY()-event.getY())*(r.centerY()-event.getY());if(dist<best){best=dist;a=i;}}if(a<0)return true;
  if(s.optBoolean("setup")){if(s.optJSONArray("prepared").optBoolean(me))return true;if(id==7){app.setupTap(a,0);return true;}if(id==1&&(me==0?a>=60:a<40)){if(selected<0)selected=a;else{app.setupTap(selected,a);selected=-1;}invalidate();}return true;}
  boolean moving=id==0||id==1||id==2||(id==10&&s.optInt("phase")==0&&s.optJSONArray("count").optInt(me)>=9);
  if(moving){if(selected>=0){for(int[] m:moves)if(m[0]==selected&&m[1]==a){if(id==0&&Math.abs(b[selected])==1&&(a/8==0||a/8==7))app.choosePromotion(selected,a);else app.act(selected,a,5);selected=-1;invalidate();return true;}}boolean can=false;for(int[] m:moves)if(m[0]==a)can=true;selected=can?a:-1;invalidate();}
  else if(id==13&&s.optInt("phase")==1){app.act(a,0,5);}else if(id==11){if(b[a]>0)app.nim(a,b[a]);}else if(id==4)app.act(a%7,0,5);else{for(int[] m:moves)if(m[0]==a){app.act(a,0,5);break;}}return true;
 }
 @Override public boolean performClick(){super.performClick();return true;}
}
