package com.traillink;

import android.graphics.*;import android.view.*;import org.json.*;import java.util.*;

/** Original vector battlefield and fixed touch HUD. Camera panning is in-world, not page scrolling. */
final class RiftView extends View {
 final RiftArt art=new RiftArt();final MainActivity app;final Paint p=new Paint(3);final ArrayList<Hit> buttons=new ArrayList<>();final LinkedHashSet<Integer> selected=new LinkedHashSet<>();
 JSONObject state;JSONArray units=new JSONArray(),nodes=new JSONArray(),terrain=new JSONArray();String fog="";RectF field=new RectF(),mini=new RectF();float zoom,cx,cy,downX,downY,lastX,lastY;boolean moved,box=false;int mode=0,placing=-1,buildPage=0;String tip="Select a harvester to build. Drag terrain to move the camera.";
 final HashMap<Integer,float[]> previous=new HashMap<>();long updated;final ScaleGestureDetector scale;boolean scaling;float boxX,boxY;Canvas c;
 static final int BG=0xff0a1420,PANEL=0xff132332,INK=0xffe4eced,BLUE=0xff68d5f0,GREEN=0xff95e1ac,RED=0xffff846c;
 static final class Hit {RectF rect;Runnable action;String label;Hit(RectF r,String s,Runnable a){rect=r;label=s;action=a;}}
 RiftView(MainActivity a,JSONObject s){super(a);app=a;zoom=d(23);cx=s.optInt("me")==0?8:27;cy=12;setFocusable(true);setContentDescription("Rift Command real-time battlefield. Select units, then issue orders using the command dock.");scale=new ScaleGestureDetector(a,new ScaleGestureDetector.SimpleOnScaleGestureListener(){@Override public boolean onScale(ScaleGestureDetector detector){zoom=Math.max(d(9),Math.min(d(45),zoom*detector.getScaleFactor()));scaling=true;return true;}});update(s);}
 float d(float v){return app.dp(v);}void update(JSONObject s){for(int i=0;i<units.length();i++){JSONArray u=units.optJSONArray(i);previous.put(u.optInt(0),new float[]{u.optInt(3)/100f,u.optInt(4)/100f});}state=s;units=s.optJSONArray("units");if(units==null)units=new JSONArray();nodes=s.optJSONArray("nodes");terrain=s.optJSONArray("terrain");fog=s.optString("fog");updated=android.os.SystemClock.uptimeMillis();selected.removeIf(id->unit(id)==null);if(selected.isEmpty()&&state.optInt("seq")==0)for(int i=0;i<units.length();i++){JSONArray u=units.optJSONArray(i);if(own(u)&&u.optInt(2)==RiftWar.CORE){selected.add(u.optInt(0));break;}}setContentDescription("Rift Command. Ore "+s.optInt("ore")+", gas "+s.optInt("gas")+", supply "+s.optInt("used")+" of "+s.optInt("cap")+". "+tip);invalidate();}
 JSONArray unit(int id){for(int i=0;i<units.length();i++){JSONArray u=units.optJSONArray(i);if(u.optInt(0)==id)return u;}return null;}boolean own(JSONArray u){return u!=null&&u.optInt(1)==state.optInt("me");}
 float wx(float screen){return cx+(screen-field.centerX())/zoom;}float wy(float screen){return cy+(screen-field.centerY())/zoom;}float sx(float world){return field.centerX()+(world-cx)*zoom;}float sy(float world){return field.centerY()+(world-cy)*zoom;}
 void fill(RectF r,int color,float radius){p.setStyle(Paint.Style.FILL);p.setColor(color);c.drawRoundRect(r,radius,radius,p);}void text(String s,float x,float y,float size,int color){p.setStyle(Paint.Style.FILL);p.setColor(color);p.setTypeface(Typeface.create("sans-serif-medium",0));p.setTextSize(d(size));p.setTextAlign(Paint.Align.LEFT);c.drawText(s,x,y,p);}void line(float x,float y,float a,float b,int color,float width){p.setColor(color);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(width);p.setStrokeCap(Paint.Cap.ROUND);c.drawLine(x,y,a,b,p);p.setStyle(Paint.Style.FILL);}
 void button(String label,float x,float y,float w,float h,Runnable action,boolean accent){RectF r=new RectF(x,y,x+w,y+h);fill(r,accent?0xff235c66:0xff203444,d(7));String[] lines=label.split("\n");p.setTypeface(Typeface.create("sans-serif-medium",0));p.setTextSize(d(11));float tx=x+(w-p.measureText(lines[0]))/2;text(lines[0],tx,y+h*.48f,11,INK);if(lines.length>1){p.setTextSize(d(9));text(lines[1],x+(w-p.measureText(lines[1]))/2,y+h*.78f,9,0xff9bb4c4);}buttons.add(new Hit(r,label,action));}
 @Override protected void onDraw(Canvas canvas){c=canvas;c.drawColor(BG);buttons.clear();float w=getWidth(),h=getHeight(),top=d(44),dock=h-d(132);field.set(0,top,w,dock);cx=Math.max(0,Math.min(RiftWar.W-1,cx));cy=Math.max(0,Math.min(RiftWar.H-1,cy));
  c.save();c.clipRect(field);for(int y=0;y<RiftWar.H;y++)for(int x=0;x<RiftWar.W;x++){float left=sx(x-.5f),yy=sy(y-.5f);RectF tile=new RectF(left,yy,left+zoom,yy+zoom);if(!RectF.intersects(field,tile))continue;int at=y*RiftWar.W+x;char f=at<fog.length()?fog.charAt(at):'0';int color=f=='0'?0xff101b28:((x*13+y*7)%5==0?0xff293c48:0xff243540);fill(tile,color,0);if(f!='0'){line(left,yy,left+zoom,yy,0xff2c3e49,1);if(terrain!=null&&terrain.optInt(at)==1){Path rock=new Path();rock.moveTo(left+zoom*.08f,yy+zoom*.8f);rock.lineTo(left+zoom*.2f,yy+zoom*.2f);rock.lineTo(left+zoom*.7f,yy+zoom*.05f);rock.lineTo(left+zoom*.95f,yy+zoom*.55f);rock.lineTo(left+zoom*.75f,yy+zoom*.9f);rock.close();p.setColor(0xff56616c);c.drawPath(rock,p);line(left+zoom*.2f,yy+zoom*.2f,left+zoom*.7f,yy+zoom*.05f,0xff87919a,2);}if(f=='1')fill(tile,0xaa09141f,0);}}
  if(nodes!=null)for(int i=0;i<nodes.length();i++){JSONArray n=nodes.optJSONArray(i);int at=n.optInt(0);float x=sx(at%RiftWar.W),y=sy(at/RiftWar.W);if(n.optInt(2)<=0)continue;int color=n.optInt(1)==1?BLUE:GREEN;p.setColor(color);if(n.optInt(1)==1){Path crystal=new Path();crystal.moveTo(x,y-zoom*.55f);crystal.lineTo(x+zoom*.4f,y);crystal.lineTo(x,y+zoom*.4f);crystal.lineTo(x-zoom*.3f,y);crystal.close();c.drawPath(crystal,p);line(x,y-zoom*.45f,x,y+zoom*.3f,0xffdcffff,1);}else{p.setColor(0xff2f6954);c.drawOval(x-zoom*.5f,y-zoom*.3f,x+zoom*.5f,y+zoom*.3f,p);p.setColor(GREEN);c.drawCircle(x,y,zoom*.2f,p);}}
  float f=Math.min(1,(android.os.SystemClock.uptimeMillis()-updated)/180f);for(int i=0;i<units.length();i++){JSONArray u=units.optJSONArray(i);float x=u.optInt(3)/100f,y=u.optInt(4)/100f;float[] before=previous.get(u.optInt(0));if(before!=null&&!state.optBoolean("paused")){x=before[0]+(x-before[0])*f;y=before[1]+(y-before[1])*f;}drawEntity(u,sx(x),sy(y));}
  for(int i=0;i<units.length();i++){JSONArray u=units.optJSONArray(i),victim=unit(u.optInt(15,-1));if(victim!=null)line(sx(u.optInt(3)/100f),sy(u.optInt(4)/100f),sx(victim.optInt(3)/100f),sy(victim.optInt(4)/100f),u.optInt(2)==RiftWar.MEDIC?GREEN:0xfff8db82,d(1.5f));}
  if(moved&&box){RectF selection=new RectF(Math.min(downX,lastX),Math.min(downY,lastY),Math.max(downX,lastX),Math.max(downY,lastY));fill(selection,0x3368d5f0,0);p.setStyle(Paint.Style.STROKE);p.setColor(BLUE);c.drawRect(selection,p);p.setStyle(Paint.Style.FILL);}c.restore();
  fill(new RectF(0,0,w,top),PANEL,0);text("RIFT COMMAND",d(12),d(27),14,BLUE);String resources="ORE "+state.optInt("ore")+"    GAS "+state.optInt("gas")+"    "+state.optInt("used")+" / "+state.optInt("cap");text(resources,d(155),d(27),12,INK);button("Ⅱ",w-d(96),0,d(44),top,()->app.rtsMenu(),false);button("?",w-d(48),0,d(44),top,()->app.rtsHelp(0),false);
  fill(new RectF(0,dock,w,h),PANEL,0);mini.set(d(8),dock+d(24),d(120),dock+d(24)+d(112)*RiftWar.H/RiftWar.W);drawMini();text(String.format(java.util.Locale.ROOT,"%02d:%02d",state.optInt("seq")/600,state.optInt("seq")/10%60),d(12),dock+d(16),11,0xff9bb4c4);
  float left=d(132),available=w-left-d(8);JSONArray first=selected.isEmpty()?null:unit(selected.iterator().next());String name=first==null?"COMMAND DECK":selected.size()>1?selected.size()+" units selected":RiftWar.NAMES[first.optInt(2)]+"  "+first.optInt(5)+"/"+first.optInt(6)+(first.optInt(7)>0?" · building":"");text(name,left,dock+d(17),12,INK);
  ArrayList<String> labels=new ArrayList<>();ArrayList<Runnable> actions=new ArrayList<>();if(state.optInt("winner")>=0){add(labels,actions,"Rematch",()->app.rtsRematch());add(labels,actions,"Room",()->app.home());}
  else if(placing>=0){add(labels,actions,"Cancel site",()->{placing=-1;mode=0;tip="Construction cancelled";});text("PLACE "+RiftWar.NAMES[placing]+" · tap clear visible terrain",left+d(130),dock+d(17),11,GREEN);}
  else if(mode==RiftWar.BUILD){for(int i=0;i<4;i++){final int type=10+buildPage*4+i;add(labels,actions,RiftWar.NAMES[type]+"\n"+RiftWar.ORE[type]+" ore · "+RiftWar.GAS[type]+" gas",()->{placing=type;tip="Tap visible terrain for "+RiftWar.NAMES[type];});}add(labels,actions,"More",()->buildPage=1-buildPage);add(labels,actions,"Back",()->mode=0);}
  else if(first!=null){int type=first.optInt(2);if(type>=10){if(first.optInt(7)>0){tip="A harvester must stay nearby to finish construction.";}else {int[] train=type==RiftWar.CORE?new int[]{0}:type==RiftWar.BARRACKS?new int[]{1,4}:type==RiftWar.FACTORY?new int[]{2,3}:type==RiftWar.AIRPAD?new int[]{5}:type==RiftWar.LAB?new int[]{20,21}:new int[0];for(int t:train){final int pick=t;if(state.optJSONArray("tech").optBoolean(t))add(labels,actions,RiftWar.NAMES[t]+"\n"+(RiftWar.ORE[t]*(t==20?state.optInt("weapons")+1:t==21?state.optInt("armor")+1:1))+" ore · "+(RiftWar.GAS[t]*(t==20?state.optInt("weapons")+1:t==21?state.optInt("armor")+1:1))+" gas",()->order(t>=20?RiftWar.RESEARCH:RiftWar.TRAIN,pick,0,0));}if(first.optJSONArray(10).length()>0)add(labels,actions,"Cancel queue\n"+first.optJSONArray(10).length()+" queued",()->order(RiftWar.CANCEL,0,0,0));if(type==RiftWar.CORE||type==RiftWar.BARRACKS||type==RiftWar.FACTORY||type==RiftWar.AIRPAD)add(labels,actions,"Rally point",()->{mode=RiftWar.RALLY;tip="Tap a rally point on the battlefield.";});}}
   else{add(labels,actions,"Move",()->{mode=RiftWar.MOVE;tip="Tap a destination.";});add(labels,actions,"Attack move",()->{mode=RiftWar.ATTACK;tip="Tap a destination; engage enemies along the way.";});if(type==RiftWar.WORKER){add(labels,actions,"Build",()->{mode=RiftWar.BUILD;buildPage=0;});add(labels,actions,"Gather",()->{mode=RiftWar.GATHER;tip="Tap blue ore or an owned gas extractor.";});add(labels,actions,"Repair",()->{mode=RiftWar.REPAIR;tip="Tap your damaged or unfinished structure.";});}else add(labels,actions,"Hold",()->order(RiftWar.HOLD,0,0,0));add(labels,actions,"Stop",()->order(RiftWar.STOP,0,0,0));}}
  float gap=d(4),bw=(available-gap*Math.max(0,labels.size()-1))/Math.max(1,labels.size());for(int i=0;i<labels.size();i++)button(labels.get(i),left+i*(bw+gap),dock+d(24),bw,d(48),actions.get(i),true);
  String[] quick={"Army","Workers","Base",box?"Pan":"Box select","−","+"};float qw=(available-gap*5)/6;for(int i=0;i<6;i++){final int action=i;button(quick[i],left+i*(qw+gap),dock+d(78),qw,d(44),()->{if(action<2)selectGroup(action==0);else if(action==2){cx=state.optInt("me")==0?5:30;cy=12;}else if(action==3)box=!box;else zoom=Math.max(d(9),Math.min(d(45),zoom*(action==5?1.2f:.83f)));},false);}
  String banner=state.optInt("winner")>=0?state.optInt("winner")==2?"DRAW":state.optInt("winner")==state.optInt("me")?"VICTORY · Enemy structures destroyed":"DEFEAT · Your structures were destroyed":state.optBoolean("paused")?"PAUSED · Both commanders must be in the battle":placing>=0||mode!=0?tip:state.optString("message",tip);p.setTextSize(d(11));int maxChars=Math.max(25,(int)((w-d(24))/d(6)));if(banner.length()>maxChars)banner=banner.substring(0,maxChars-1)+"…";float tw=p.measureText(banner);fill(new RectF(d(8),top+d(5),Math.min(w-d(8),tw+d(28)),top+d(30)),0xdf0a1420,d(6));text(banner,d(16),top+d(22),11,state.optBoolean("paused")?0xfff8db82:INK);postInvalidateDelayed(33);
 }
 void drawEntity(JSONArray u,float x,float y){int type=u.optInt(2),color=own(u)?BLUE:RED;float r=zoom*(type>=10?1.1f:type==RiftWar.SIEGE?.55f:.35f);if(!field.contains(x,y)&&!RectF.intersects(field,new RectF(x-r,y-r,x+r,y+r)))return;p.setColor(0x66000000);c.drawOval(x-r,y+r*.4f,x+r,y+r*1.1f,p);if(selected.contains(u.optInt(0))){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(d(1));p.setColor(GREEN);c.drawOval(x-r*1.25f,y-r*.8f,x+r*1.25f,y+r*1.15f,p);p.setStyle(Paint.Style.FILL);}
  float facing=0;float[] previousPosition=previous.get(u.optInt(0));if(type<10&&previousPosition!=null){float dx=u.optInt(3)/100f-previousPosition[0],dy=u.optInt(4)/100f-previousPosition[1];if(Math.abs(dx)+Math.abs(dy)>.01f)facing=(float)(Math.atan2(dy,dx)*180/Math.PI)+90;}art.draw(c,type,x,y,r,color,state.optInt("seq"),facing);
  float hp=(float)u.optInt(5)/Math.max(1,u.optInt(6));fill(new RectF(x-r,y-r-d(5),x+r,y-r-d(2)),0xff19222b,0);fill(new RectF(x-r,y-r-d(5),x-r+2*r*hp,y-r-d(2)),hp>.35?GREEN:RED,0);if(u.optInt(7)>0||u.optJSONArray(10).length()>0){float progress=u.optInt(7)>0?1-u.optInt(7)/(float)RiftWar.TIME[type]:u.optInt(9)/(float)RiftWar.TIME[u.optJSONArray(10).optInt(0)];fill(new RectF(x-r,y+r+d(3),x-r+2*r*Math.min(1,progress),y+r+d(6)),0xfff8db82,0);}if(u.optInt(8)>0){p.setColor(0xaaeecc88);c.drawCircle(x,y,r*.7f,p);}
 }
 void drawMini(){fill(mini,0xff071019,d(3));float step=mini.width()/RiftWar.W;for(int i=0;i<fog.length();i++)if(fog.charAt(i)!='0'){p.setColor(fog.charAt(i)=='2'?0xff3b5361:0xff24313d);c.drawRect(mini.left+i%RiftWar.W*step,mini.top+i/RiftWar.W*step,mini.left+(i%RiftWar.W+1)*step,mini.top+(i/RiftWar.W+1)*step,p);}for(int i=0;i<units.length();i++){JSONArray u=units.optJSONArray(i);p.setColor(own(u)?BLUE:RED);c.drawCircle(mini.left+u.optInt(3)/100f*step,mini.top+u.optInt(4)/100f*step,d(1.5f),p);}p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1);p.setColor(INK);RectF camera=new RectF(mini.left+wx(field.left)*step,mini.top+wy(field.top)*step,mini.left+wx(field.right)*step,mini.top+wy(field.bottom)*step);c.save();c.clipRect(mini);c.drawRect(camera,p);c.restore();p.setStyle(Paint.Style.FILL);}
 void add(ArrayList<String> labels,ArrayList<Runnable> actions,String text,Runnable action){labels.add(text);actions.add(action);}void order(int action,int type,int x,int y){int[] ids=new int[Math.min(24,selected.size())];int i=0;for(int id:selected){if(i==ids.length)break;ids[i++]=id;}app.rtsOrder(action,ids,type,x,y);mode=0;placing=-1;}
 void selectGroup(boolean army){selected.clear();for(int i=0;i<units.length()&&selected.size()<24;i++){JSONArray u=units.optJSONArray(i);if(own(u)&&u.optInt(2)<10&&(army?u.optInt(2)!=0:u.optInt(2)==0))selected.add(u.optInt(0));}mode=0;placing=-1;tip=army?"Army selected. Tap Attack move, then a destination.":"Harvesters selected. Select one worker before building.";}
 @Override public boolean onTouchEvent(MotionEvent e){scale.onTouchEvent(e);float x=e.getX(),y=e.getY();if(e.getActionMasked()==MotionEvent.ACTION_DOWN){downX=lastX=x;downY=lastY=y;moved=false;scaling=false;return true;}if(e.getActionMasked()==MotionEvent.ACTION_MOVE){if(Math.hypot(x-downX,y-downY)>d(8))moved=true;if(moved&&!box&&!scaling&&field.contains(downX,downY)){cx-=(x-lastX)/zoom;cy-=(y-lastY)/zoom;}lastX=x;lastY=y;return true;}if(e.getActionMasked()!=MotionEvent.ACTION_UP)return true;performClick();if(scaling)return true;
  if(moved){if(box&&field.contains(downX,downY)){selected.clear();float l=Math.min(wx(downX),wx(x)),r=Math.max(wx(downX),wx(x)),t=Math.min(wy(downY),wy(y)),b=Math.max(wy(downY),wy(y));for(int i=0;i<units.length()&&selected.size()<24;i++){JSONArray u=units.optJSONArray(i);float ux=u.optInt(3)/100f,uy=u.optInt(4)/100f;if(own(u)&&u.optInt(2)<10&&ux>=l&&ux<=r&&uy>=t&&uy<=b)selected.add(u.optInt(0));}}moved=false;return true;}
  for(Hit hit:new ArrayList<>(buttons))if(hit.rect.contains(x,y)){hit.action.run();performHapticFeedback(HapticFeedbackConstants.CLOCK_TICK);invalidate();return true;}if(mini.contains(x,y)){cx=(x-mini.left)/mini.width()*RiftWar.W;cy=(y-mini.top)/mini.height()*RiftWar.H;return true;}if(!field.contains(x,y))return true;int tx=Math.round(wx(x)),ty=Math.round(wy(y));if(tx<0||ty<0||tx>=RiftWar.W||ty>=RiftWar.H)return true;
  if(placing>=0){order(RiftWar.BUILD,placing,tx,ty);return true;}if(mode!=0&&mode!=RiftWar.BUILD){order(mode,0,tx,ty);return true;}JSONArray tapped=null;float nearest=1.6f;for(int i=0;i<units.length();i++){JSONArray u=units.optJSONArray(i);float dist=RiftWar.distance(wx(x),wy(y),u.optInt(3)/100f,u.optInt(4)/100f);if(dist<nearest&&(dist<.8||u.optInt(2)>=10)){tapped=u;nearest=dist;}}if(own(tapped)){selected.clear();selected.add(tapped.optInt(0));mode=0;placing=-1;return true;}if(!selected.isEmpty()){JSONArray first=unit(selected.iterator().next());int action=tapped!=null?RiftWar.ATTACK:RiftWar.MOVE;if(first!=null&&first.optInt(2)==RiftWar.WORKER&&nodes!=null)for(int i=0;i<nodes.length();i++)if(nodes.optJSONArray(i).optInt(0)==ty*RiftWar.W+tx)action=RiftWar.GATHER;order(action,0,tx,ty);}return true;
 }
 @Override public boolean performClick(){super.performClick();return true;}
}
