package com.traillink;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.view.*;import android.widget.*;import android.view.accessibility.AccessibilityNodeInfo;import org.json.*;import java.io.*;import java.util.*;
public class DeviceTests extends Instrumentation {
 Bundle args;MainActivity app;StringBuilder report=new StringBuilder();
 @Override public void onCreate(Bundle extras){args=extras==null?new Bundle():extras;start();}
 void say(String value){report.append(value).append('\n');Bundle b=new Bundle();b.putString("stream",value+"\n");sendStatus(0,b);}
 void require(boolean value,String msg){if(!value)throw new AssertionError(msg);}
 void main(Runnable r){final Throwable[] failure={null};runOnMainSync(()->{try{r.run();}catch(Throwable e){failure[0]=e;}});waitForIdleSync();if(failure[0]!=null)throw new AssertionError("UI test assertion",failure[0]);}
 @Override public void onStart(){Bundle result=new Bundle();try{Intent intent=new Intent();intent.setClassName("com.traillink","com.traillink.MainActivity");intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);app=(MainActivity)startActivitySync(intent);waitForIdleSync();String mode=args.getString("mode","ui");if(mode.equals("ui"))ui();else if(mode.equals("host")||mode.equals("client"))multiplayer(mode.equals("host"));else if(mode.equals("recover-host")||mode.equals("recover-client"))recovery(mode.equals("recover-host"));else if(mode.equals("physical-host"))physicalHost();say("PASS");result.putString("stream",report.toString());finish(Activity.RESULT_OK,result);}catch(Throwable t){say("FAIL: "+t);result.putString("stream",report+"\n"+android.util.Log.getStackTraceString(t));finish(Activity.RESULT_CANCELED,result);}}
 void tap(float x,float y){long t=SystemClock.uptimeMillis();MotionEvent down=MotionEvent.obtain(t,t,MotionEvent.ACTION_DOWN,x,y,0),up=MotionEvent.obtain(t,t+70,MotionEvent.ACTION_UP,x,y,0);getUiAutomation().injectInputEvent(down,true);getUiAutomation().injectInputEvent(up,true);down.recycle();up.recycle();waitForIdleSync();SystemClock.sleep(150);}
 void cell(int index){BoardView board=app.board;int[] pos=new int[2];main(()->board.getLocationOnScreen(pos));RectF r=board.hit.get(index);tap(pos[0]+r.centerX(),pos[1]+r.centerY());}
 boolean clickText(String value){AccessibilityNodeInfo root=getUiAutomation().getRootInActiveWindow();if(root==null)return false;ArrayDeque<AccessibilityNodeInfo> queue=new ArrayDeque<>();queue.add(root);while(!queue.isEmpty()){AccessibilityNodeInfo node=queue.remove();if(node.getText()!=null&&value.equalsIgnoreCase(node.getText().toString())){Rect r=new Rect();node.getBoundsInScreen(r);tap(r.centerX(),r.centerY());return true;}for(int i=0;i<node.getChildCount();i++){AccessibilityNodeInfo child=node.getChild(i);if(child!=null)queue.add(child);}}return false;}
 void screen(String name)throws Exception{SystemClock.sleep(180);Bitmap image=getUiAutomation().takeScreenshot();require(image!=null,"Screenshot available");File dir=new File(app.getExternalFilesDir(null),"verification");dir.mkdirs();try(FileOutputStream f=new FileOutputStream(new File(dir,name+".png"))){image.compress(Bitmap.CompressFormat.PNG,100,f);}image.recycle();}
 void ui()throws Exception{GameTest.run();say("Rules: "+GameTest.assertions+" assertions on device");for(int i=0;i<15;i++){final int id=i;main(()->{app.link.close();app.local=true;app.host=false;app.me=0;app.startGame(id);});SystemClock.sleep(200);screen(String.format(Locale.ROOT,"%02d-%s",i,Game.NAMES[i].replace(' ','-')));int[] move=app.game.legal().get(0);
   if(id==14){require(clickText("Roll the die"),"Roll button exists");}
   else if(id==11){cell(move[0]);require(clickText("Take 1"),"Nim quantity dialog");}
   else if(id==0||id==1||id==2){cell(move[0]);cell(move[1]);}
   else cell(move[0]);
   require(app.game.seq==1,Game.NAMES[id]+" touch move applied; seq="+app.game.seq);say("UI touch passed: "+Game.NAMES[id]);}
  main(()->{app.local=true;app.startGame(5);app.act(0,0,5);app.act(3,0,5);app.act(1,0,5);app.act(4,0,5);app.act(2,0,5);});require(app.game.winner==0,"Complete on-device match");main(()->{app.save();app.game=null;app.state=null;app.restore();});require(app.game.winner==0&&app.game.seq==5,"Saved game round trip");say("Complete match + persistent save passed");
  main(()->{app.game=null;app.state=null;app.session="";app.savedPeer="";app.local=false;app.save();app.home();});screen("home");}
 void pairing(){clickText("Pair");clickText("PAIR");clickText("התאמה");}
 boolean connected(){final boolean[] ready={false};main(()->ready[0]=app.ready&&app.link.connected);return ready[0];}
 void setup(boolean host){main(()->{app.game=null;app.state=null;app.session="";app.savedPeer="";app.local=false;app.host=host;app.me=host?0:1;app.ready=false;if(host)app.link.host();else app.link.join(app.adapter.getRemoteDevice(args.getString("address")));});}
 void waitConnected()throws Exception{for(int i=0;i<100&&!connected();i++){pairing();SystemClock.sleep(500);}require(connected(),"Bluetooth connected: "+app.status);say("Connected via actual BluetoothSocket: "+app.peerAddress);}
 void multiplayer(boolean hosting)throws Exception{setup(hosting);waitConnected();Random rng=new Random(7);if(hosting){for(int id=0;id<15;id++){final int kind=id;main(()->app.invite(kind));for(int wait=0;wait<100&&(app.game==null||app.game.id!=kind);wait++)SystemClock.sleep(100);require(app.game!=null&&app.game.id==kind,"Invitation accepted for "+Game.NAMES[kind]);for(int steps=0;steps<3000;steps++){final int[] info=new int[3];main(()->{info[0]=app.game.turn;info[1]=app.game.winner;info[2]=app.game.seq;});if(info[1]>=0)break;if(info[0]==0){main(()->{ArrayList<int[]> legal=app.game.legal();int[] move=legal.get(rng.nextInt(legal.size()));app.act(move[0],move[1],5);});}else SystemClock.sleep(25);if(steps==2999)throw new AssertionError("Peer stalled in "+Game.NAMES[id]);}require(app.game.winner>=0,"Match completed");say("Bluetooth match passed: "+Game.NAMES[id]+", moves="+app.game.seq);screen("multiplayer-"+id);SystemClock.sleep(1000);}
  main(()->app.send(MainActivity.obj("type","error","text","TEST_COMPLETE")));SystemClock.sleep(500);
 }else{long deadline=SystemClock.uptimeMillis()+600000;int finished=0,lastId=-1;while(SystemClock.uptimeMillis()<deadline&&finished<15){main(()->{if(app.state!=null&&app.state.optInt("winner")==-1&&app.state.optInt("turn")==1&&!app.awaiting){JSONArray moves=app.state.optJSONArray("moves");if(moves.length()>0){JSONArray move=moves.optJSONArray(rng.nextInt(moves.length()));app.act(move.optInt(0),move.optInt(1),5);}}});if(app.state!=null&&app.state.optInt("winner")>=0&&app.state.optInt("id")!=lastId){lastId=app.state.optInt("id");finished++;say("Peer finished "+Game.NAMES[lastId]);}if(app.state==null||app.state.optInt("winner")>=0)clickText("Play");SystemClock.sleep(15);}require(finished==15,"All 15 received by client, got "+finished);}
 }
 void waitSeq(int seq)throws Exception{long end=SystemClock.uptimeMillis()+15000;while(SystemClock.uptimeMillis()<end&&(app.state==null||app.state.optInt("seq")<seq))SystemClock.sleep(50);require(app.state!=null&&app.state.optInt("seq")==seq,"Expected synchronized sequence "+seq);}
 void recovery(boolean hosting)throws Exception{setup(hosting);waitConnected();if(hosting){main(()->{app.startGame(5);app.act(0,0,5);});waitSeq(2);require(app.game.b[0]==1&&app.game.b[3]==-1,"Opening synchronized");String match=app.session;main(()->{app.ready=false;app.link.close();app.save();app.game=null;app.state=null;app.restore();});SystemClock.sleep(1800);main(()->app.link.host());waitConnected();require(app.session.equals(match)&&app.game.seq==2,"Host restored same match after socket loss");main(()->app.act(1,0,5));waitSeq(4);main(()->app.act(2,0,5));require(app.game.winner==0,"Resumed match completes");say("Disconnect + disk restore + Bluetooth reconnect + completed match passed");screen("reconnected-win");SystemClock.sleep(1500);
 }else{waitSeq(1);String match=app.session;main(()->app.send(MainActivity.obj("type","move","session",match,"seq",0,"a",3,"z",0,"choice",5)));SystemClock.sleep(400);require(app.state.optInt("seq")==1,"Stale move rejected");main(()->app.send(MainActivity.obj("type","move","session","wrong-session","seq",1,"a",3,"z",0,"choice",5)));SystemClock.sleep(400);require(app.state.optInt("seq")==1,"Wrong session rejected");main(()->app.act(3,0,5));waitSeq(2);long end=SystemClock.uptimeMillis()+12000;while(connected()&&SystemClock.uptimeMillis()<end)SystemClock.sleep(100);require(!connected(),"Connection loss detected");SystemClock.sleep(2300);main(()->app.link.join(app.adapter.getRemoteDevice(args.getString("address"))));waitConnected();require(match.equals(app.session),"Guest resumes same match");waitSeq(3);main(()->app.act(4,0,5));waitSeq(5);require(app.state.optInt("winner")==0,"Guest receives resumed winner");say("Stale move + wrong session rejection and reconnection passed");screen("reconnected-peer");}
 }
 void physicalHost()throws Exception{setup(true);say("Physical host waiting for Windows Bluetooth peer");waitConnected();Random rng=new Random(73);for(int id=0;id<15;id++){final int kind=id;main(()->app.startGame(kind));for(int step=0;step<5000&&app.game.winner<0;step++){if(app.game.turn==0)main(()->{ArrayList<int[]> legal=app.game.legal();int[] move=legal.get(rng.nextInt(legal.size()));app.act(move[0],move[1],5);});else SystemClock.sleep(40);}require(app.game.winner>=0,"Physical Bluetooth game complete: "+Game.NAMES[id]);say("Vivo physical Bluetooth passed: "+Game.NAMES[id]+", moves="+app.game.seq);if(id==0||id==1||id==7)screen("bluetooth-"+id);SystemClock.sleep(120);}main(()->app.home());}
}
