package com.traillink;
import android.app.*;import android.content.*;import android.os.*;import android.view.*;import android.widget.*;import java.io.*;import java.nio.file.*;import java.util.*;

public final class LearningDeviceTests extends V3DeviceTests {
 @Override public void onStart(){Bundle result=new Bundle();byte[] saved=null;File file=null;Map<String,?> prefs=null,fleetPrefs=null;try{
  Intent intent=new Intent();intent.setClassName("com.traillink","com.traillink.MainActivity");intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);app=(MainActivity)startActivitySync(intent);waitForIdleSync();file=new File(app.getFilesDir(),"match.bin");if(file.exists())saved=Files.readAllBytes(file.toPath());prefs=new HashMap<>(app.getSharedPreferences("coach",0).getAll());fleetPrefs=new HashMap<>(app.getSharedPreferences("fleet-draft",0).getAll());LearningTest.run();TimelineTest.run();say("Rules/presentation: "+LearningTest.assertions+"; timeline: "+TimelineTest.assertions);
  main(()->{clean();app.learnMode=true;app.openingLesson=0;app.solo=true;app.botLevel=1;app.startGame(0);});require(app.me==0,"Lesson always gives learner White");waitScore();fits();screen("learning-opening");
  int seq=app.game.seq;main(()->app.act(51,35,5));require(app.game.seq==seq,"Wrong lesson move gives feedback without changing board");
  require(clickText("Hint"),"Visible Hint control");require(app.board.s.optInt("bestFrom")==52&&app.board.s.optInt("bestTo")==36,"Hint arrow maps e4");BoardView hintBoard=app.board;require(app.hintVisible&&app.learningHint.getText().toString().contains("HINT"),"Hint is inline");fits();screen("chess-inline-hint");cell(52);cell(36);waitSequence(2);require(app.game.seq==2&&!app.hintVisible,"Board remains playable with hint open; hint clears after move");
  for(int i=0;i<2;i++){int[] move=ChessTutor.next(app.game,0);require(move!=null&&app.game.turn==app.me,"Learner turn in lesson");int before=app.game.seq;main(()->app.act(move[0],move[1],move[2]));long until=SystemClock.uptimeMillis()+10000;while(app.game.seq<before+2&&SystemClock.uptimeMillis()<until)SystemClock.sleep(80);require(app.game.seq==before+2,"Scripted reply follows lesson");}
  require(app.game.chessMoves.size()==6&&ChessTutor.next(app.game,0)==null,"Guided opening complete");waitScore();fits();screen("learning-complete");main(()->{app.save();app.learnMode=false;app.openingLesson=-1;app.restore();});require(app.learnMode&&app.openingLesson==0,"Lesson mode persists");
  require(clickText("Undo")&&clickText("Continue"),"Undo confirmation");require(app.game.seq==4&&app.game.turn==app.me,"Undo removes learner move and scripted reply");waitScore();main(()->{int[] m=ChessTutor.next(app.game,0);app.act(m[0],m[1],m[2]);app.continueChess(4);});SystemClock.sleep(1800);require(app.game.seq==4,"Stale bot reply cannot land after takeback");main(()->{int[] m=ChessTutor.next(app.game,0);app.act(m[0],m[1],m[2]);});waitSequence(6);waitScore();screen("chess-takeback");
  int[] free=app.game.legal().get(0);int freeSeq=app.game.seq;main(()->{app.showSnapshot();app.act(free[0],free[1],5);});long freeUntil=SystemClock.uptimeMillis()+12000;while(app.game.seq<freeSeq+2&&SystemClock.uptimeMillis()<freeUntil)SystemClock.sleep(100);require(app.game.seq>=freeSeq+2,"Stockfish continues after lesson");waitScore();
  Game mate=new Game(0,1);mate.move(0,53,45,5);mate.move(1,12,28,5);mate.move(0,54,38,5);mate.move(1,3,39,5);StockfishEngine.Review nativeReview=app.getStockfish().analyze(mate,3);ChessReviewText nativeText=ChessReviewText.from(nativeReview.text);require(nativeText.bestScore.equals(nativeText.playedScore)&&nativeText.bestScore.equals("Black mates in 1"),"Native identical move has one canonical mate evaluation");
  main(()->{clean();app.game=mate;for(int i=0;i<4;i++){app.game.analysis.add(i==3?nativeReview.text:"");app.game.analysisBest.add(i==3?nativeReview.best:app.game.chessMoves.get(i));}app.state=app.snapshot(1);app.me=1;app.reviewIndex=4;app.review();});fits();screen("review-native-mate");
  main(()->{clean();app.learnMode=false;app.openingLesson=-1;app.game=new Game(0,1);app.game.move(0,53,45,5);app.game.move(1,12,28,5);app.game.move(0,54,38,5);app.game.move(1,3,39,5);for(int i=0;i<4;i++){app.game.analysis.add(LearningTest.report("d4","d4","Mate scores are shown below; search-limited evaluations can change.","opponent mate in 5","opponent mate in 3"));app.game.analysisBest.add(app.game.chessMoves.get(i));}app.state=app.snapshot(0);app.reviewIndex=3;app.review();});
  fits();require(find(app.root,"Black mates in 5")>=2,"Both mate scores visible on main review");screen("review-visible-mate");
  main(()->{app.game.analysis.set(2,LearningTest.report("Kd1","Kd1","Stockfish prefers the alternative by about 0.94 pawns.","-0.20","-1.14"));app.review();});fits();require(find(app.root,"-0.20 pawns")>=2,"Identical move values visible");require(find(app.root,"0.94")==0,"Contradiction absent");screen("review-same-move");
  main(()->{app.game=mate;app.me=1;app.local=true;app.solo=false;app.reviewIndex=4;app.reviewMode=0;app.review();});fits();screen("chess-play-from-here");require(clickText("Play from here")&&clickText("Continue"),"Continue from review confirmation");require(app.game.seq==3&&app.game.winner<0&&app.game.turn==1,"Compare mode resumes before move");main(()->app.act(6,21,5));require(app.game.seq==4&&app.game.winner<0&&app.game.b[21]==-2,"Alternate continuation is legal");main(()->{app.save();app.restore();});require(app.game.chessMoves.size()==4&&app.game.b[21]==-2,"Branched match persists");main(()->{app.reviewIndex=1;app.reviewMode=1;app.review();});require(clickText("Play from here")&&clickText("Continue"),"Played-mode continuation");require(app.game.seq==1&&app.game.b[45]==1,"Played mode resumes after move");main(()->{app.local=false;app.host=true;app.reviewIndex=1;app.review();});require(find(app.root,"Play from here")==0&&app.undoPly()<0,"No unilateral online rewind");
  uiV3();say("All 15 game layouts and touch actions rechecked");
  say("PASS");result.putString("stream",report.toString());
 }catch(Throwable e){say("FAIL: "+e);result.putString("stream",report+"\n"+android.util.Log.getStackTraceString(e));}
 finally{if(app!=null){final byte[] prior=saved;final File target=file;final Map<String,?> previous=prefs,previousFleet=fleetPrefs;main(()->{clean();app.learnMode=false;app.openingLesson=-1;app.local=app.solo=false;try{if(target!=null){if(prior!=null)Files.write(target.toPath(),prior);else Files.deleteIfExists(target.toPath());}if(previous!=null){SharedPreferences.Editor edit=app.getSharedPreferences("coach",0).edit().clear();for(Map.Entry<String,?> e:previous.entrySet()){Object v=e.getValue();if(v instanceof String)edit.putString(e.getKey(),(String)v);else if(v instanceof Boolean)edit.putBoolean(e.getKey(),(Boolean)v);else if(v instanceof Integer)edit.putInt(e.getKey(),(Integer)v);}edit.commit();}if(previousFleet!=null){SharedPreferences.Editor edit=app.getSharedPreferences("fleet-draft",0).edit().clear();for(Map.Entry<String,?> e:previousFleet.entrySet())edit.putString(e.getKey(),(String)e.getValue());edit.commit();}app.restore();app.home();}catch(Exception e){throw new RuntimeException(e);}});}finish(report.toString().contains("FAIL:")?Activity.RESULT_CANCELED:Activity.RESULT_OK,result);}
 }
 void waitSequence(int seq){long until=SystemClock.uptimeMillis()+12000;while(app.game.seq<seq&&SystemClock.uptimeMillis()<until)SystemClock.sleep(80);require(app.game.seq==seq,"Expected move sequence "+seq);}
 void waitScore(){long until=SystemClock.uptimeMillis()+12000;while((app.coach==null||app.coachSeq!=app.game.seq)&&SystemClock.uptimeMillis()<until)SystemClock.sleep(80);require(app.coach!=null&&app.coachSeq==app.game.seq,"Live Stockfish score updates");}
 @Override void fits(){waitForIdleSync();SystemClock.sleep(250);super.fits();main(()->checkBounds(app.root));}
 void checkBounds(View view){if(view.getVisibility()!=View.VISIBLE)return;int[] at=new int[2];view.getLocationOnScreen(at);if(view instanceof Button)require(at[1]+view.getHeight()<=app.root.getHeight()-app.root.getPaddingBottom(),"Visible action fits screen: "+((Button)view).getText());if(view instanceof android.view.ViewGroup)for(int i=0;i<((android.view.ViewGroup)view).getChildCount();i++)checkBounds(((android.view.ViewGroup)view).getChildAt(i));}
 int find(View v,String part){int count=v instanceof TextView&&((TextView)v).getText().toString().contains(part)?1:0;if(v instanceof ViewGroup)for(int i=0;i<((ViewGroup)v).getChildCount();i++)count+=find(((ViewGroup)v).getChildAt(i),part);return count;}
}
