package com.traillink;
import java.io.*;import java.util.*;
public final class RiftTest {
 static int assertions;static void check(boolean value,String message){assertions++;if(!value)throw new AssertionError(message);}
 static RiftWar.Entity first(RiftWar w,int side,int type){for(RiftWar.Entity e:w.entities)if(e.side==side&&e.type==type)return e;throw new AssertionError("Missing entity "+type);}
 static boolean cmd(RiftWar w,int side,int action,RiftWar.Entity e,int type,int x,int y){return w.issue(side,w.lastCommand[side]+1,action,new int[]{e.id},type,x,y);}
 static void run()throws Exception{RiftWar w=new RiftWar(5,0,0);RiftWar.Entity worker=first(w,0,0),core=first(w,0,10);check(w.entities.size()==12,"Two cores and ten workers");check(w.cap(0)==12&&w.supply(0)==5,"Initial supply");check(!w.visible[0][12*36+30],"Enemy base hidden");int before=w.ore[0];for(int i=0;i<250;i++)w.step();check(w.ore[0]>before,"Workers deliver mined resources");check(!cmd(w,1,RiftWar.MOVE,worker,0,15,12),"Cannot command opponent");check(!cmd(w,0,RiftWar.BUILD,worker,12,30,12),"Cannot build in enemy fog");check(!cmd(w,0,RiftWar.BUILD,worker,13,9,15),"Prerequisite required");
  check(cmd(w,0,RiftWar.BUILD,worker,12,9,15),"Barracks construction placed");RiftWar.Entity barracks=first(w,0,12);for(int i=0;i<600&&barracks.build>0;i++)w.step();check(barracks.build==0,"Worker travels and completes structure");check(cmd(w,0,RiftWar.TRAIN,barracks,1,0,0),"Ranger queued");int ore=w.ore[0];check(cmd(w,0,RiftWar.CANCEL,barracks,0,0,0)&&w.ore[0]==ore+50,"Queue cancellation refunds");check(cmd(w,0,RiftWar.TRAIN,barracks,1,0,0),"Queue again");for(int i=0;i<80;i++)w.step();check(w.count(0,1)==1,"Unit produced");long serial=w.lastCommand[0];check(!w.issue(0,serial,RiftWar.STOP,new int[]{worker.id},0,0,0),"Duplicate command rejected");check(!w.issue(0,serial+100,RiftWar.STOP,new int[]{worker.id},0,0,0),"Huge sequence jump rejected");check(!cmd(w,0,RiftWar.MOVE,worker,0,-1,12),"Off-map order rejected");
  ByteArrayOutputStream bytes=new ByteArrayOutputStream();try(ObjectOutputStream out=new ObjectOutputStream(bytes)){out.writeObject(w);}RiftWar restored;try(ObjectInputStream in=new ObjectInputStream(new ByteArrayInputStream(bytes.toByteArray()))){restored=(RiftWar)in.readObject();}check(restored.tick==w.tick&&restored.ore[0]==w.ore[0]&&restored.entities.size()==w.entities.size(),"Simulation save round trip");for(RiftWar.Entity e:restored.entities)if(e.side==1&&e.building())e.hp=0;restored.step();check(restored.winner==0,"Structures destroyed ends match");
  RiftWar supply=new RiftWar(0,0,0);supply.ore[0]=10000;RiftWar.Entity hq=first(supply,0,10);for(int i=0;i<5;i++)check(cmd(supply,0,RiftWar.TRAIN,hq,0,0,0),"Queue capacity slot "+i);check(!cmd(supply,0,RiftWar.TRAIN,hq,0,0,0),"Queue cap enforced");
  RiftWar blocked=new RiftWar(0,0,0);RiftWar.Entity builder=first(blocked,0,0);builder.x=7;builder.y=12;builder.order=RiftWar.STOP;check(cmd(blocked,0,RiftWar.BUILD,builder,12,9,15),"Blocked-worker construction placed");RiftWar.Entity site=first(blocked,0,12);for(int i=0;i<600&&site.build>0;i++)blocked.step();check(site.build==0,"Builder routes around idle worker rather than oscillating");
  RiftWar tech=new RiftWar(0,0,0);tech.ore[0]=tech.gas[0]=10000;for(int t=11;t<=17;t++)tech.spawn(0,t,9+(t-11)%4*4,2+(t-11)/4*4,0);tech.spawn(0,RiftWar.RELAY,14,18,0);for(int type=0;type<6;type++){RiftWar.Entity producer=first(tech,0,type==0?10:type==1||type==4?12:type==2||type==3?13:17);int oldCount=tech.count(0,type);check(cmd(tech,0,RiftWar.TRAIN,producer,type,0,0),"Tech unit queues: "+type);for(int i=0;i<150;i++)tech.step();check(tech.count(0,type)==oldCount+1,"Tech unit completes: "+type);}
  RiftWar.Entity lab=first(tech,0,14);check(cmd(tech,0,RiftWar.RESEARCH,lab,20,0,0),"Weapons research queued");check(!cmd(tech,0,RiftWar.RESEARCH,lab,20,0,0),"Duplicate research blocked");for(int i=0;i<190;i++)tech.step();check(tech.weapons[0]==1,"Weapons research completes");check(tech.costOre(0,20)==200,"Research costs scale");
  RiftWar combat=new RiftWar(0,0,0);RiftWar.Entity siege=combat.spawn(0,3,16,12,0),air=combat.spawn(1,5,17,12,0);combat.vision();int hp=air.hp;combat.fight(siege);check(air.hp==hp,"Ground-only siege cannot shoot air");RiftWar.Entity infantry=combat.spawn(0,1,16,12,0);combat.fight(infantry);check(air.hp<hp,"Ranger can defend against air");RiftWar.Entity medic=combat.spawn(0,4,16,12,0);infantry.hp-=20;hp=infantry.hp;combat.heal(medic);check(infantry.hp>hp,"Mender heals allied units");combat.armor[1]=3;hp=air.hp;combat.hit(air,10);check(hp-air.hp==7,"Armor reduces incoming damage");
  RiftWar cargo=new RiftWar(0,0,0);RiftWar.Entity miner=first(cargo,0,0);miner.carry=8;miner.carryKind=1;check(cmd(cargo,0,RiftWar.GATHER,miner,0,8,7),"Retarget laden harvester");check(miner.returning&&miner.carry==8&&miner.carryKind==1,"Retargeting preserves cargo and resource kind");
  RiftWar construction=new RiftWar(0,0,0);RiftWar.Entity engineer=first(construction,0,0),damaged=construction.spawn(0,12,9,15,1);engineer.x=7;engineer.y=15;engineer.target=damaged.id;engineer.order=RiftWar.REPAIR;damaged.hp=100;construction.repair(engineer);check(damaged.build==0&&damaged.hp<damaged.max,"Finishing construction does not erase combat damage");
  RiftWar fractional=new RiftWar(0,0,0);RiftWar.Entity returning=first(fractional,0,0);returning.x=5;returning.y=9.52f;returning.carry=8;returning.carryKind=1;returning.returning=true;for(int t=0;t<20&&returning.carry>0;t++)fractional.step();check(returning.carry==0,"Fractional position approaches its rounded arrival cell and delivers cargo");
 }
 public static void main(String[] args)throws Exception{run();System.out.println("Rift rules PASS: "+assertions);if(args.length>0){for(int map=0;map<3;map++){RiftWar w=new RiftWar(12,map,0);long start=System.nanoTime();for(int t=0;t<12000&&w.winner<0;t++){w.step();w.bot(0,2);w.bot(1,1);if(t%2000==1999)System.out.println("map "+map+" tick "+w.tick+" entities "+w.entities.size()+" ore "+Arrays.toString(w.ore)+" gas "+Arrays.toString(w.gas)+" buildings "+w.count(0,12)+"/"+w.count(1,12));}System.out.println("Skirmish map "+map+": winner="+w.winner+" ticks="+w.tick+" elapsed ms="+(System.nanoTime()-start)/1000000);check(w.winner>=0,"AI skirmish reaches victory on map "+map);}}}
}
