package com.traillink;
import android.app.*;import android.content.*;import android.os.*;import android.graphics.*;import java.io.*;import java.nio.file.*;import java.util.*;import org.json.*;

public final class RiftDeviceTests extends V3DeviceTests {
 @Override public void onStart(){Bundle result=new Bundle();byte[] saved=null;File file=null;Map<String,?> prefs=null;try{
  Intent intent=new Intent();intent.setClassName("com.traillink","com.traillink.MainActivity");intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);app=(MainActivity)startActivitySync(intent);waitForIdleSync();file=new File(app.getFilesDir(),"match.bin");if(file.exists())saved=Files.readAllBytes(file.toPath());prefs=new HashMap<>(app.getSharedPreferences("coach",0).getAll());RiftTest.run();say("Rift rules assertions: "+RiftTest.assertions);
  main(()->{clean();app.solo=true;app.botLevel=1;app.startGame(15);app.me=0;app.game.rts.doctrine0=0;app.rtsView.cx=8;app.rtsView.cy=12;app.publishRts();});SystemClock.sleep(1500);require(app.rtsView.getWidth()>app.rtsView.getHeight(),"Landscape battlefield");layout();screen("rift-opening");
  RiftWar.Entity worker=RiftTest.first(app.game.rts,0,0);main(()->{worker.order=RiftWar.STOP;worker.x=7;worker.y=12;app.publishRts();});SystemClock.sleep(250);world(7,12);require(app.rtsView.selected.contains(worker.id),"Touch selects worker");control("Build");control("Barracks");world(9,15);require(app.game.rts.count(0,12)==1,"Touch places structure");RiftWar.Entity barracks=RiftTest.first(app.game.rts,0,12);main(()->{for(int t=0;t<600&&barracks.build>0;t++)app.game.rts.step();app.publishRts();});require(barracks.build==0,"Construction completes");world(9,15);control("Ranger");require(barracks.queue.contains(1),"Touch queues production");main(()->{for(int t=0;t<70;t++)app.game.rts.step();app.publishRts();});require(app.game.rts.count(0,1)>0,"Queued unit spawns");control("Army");control("Attack move");world(13,12);RiftWar.Entity ranger=RiftTest.first(app.game.rts,0,1);require(ranger.order==RiftWar.ATTACK,"Attack move issued by touch");layout();screen("rift-construction");
  main(()->app.rtsMenu());int paused=app.game.rts.tick;SystemClock.sleep(500);require(app.game.rts.tick==paused,"Menu pauses simulation");require(clickText("Resume battle"),"Resume menu");SystemClock.sleep(350);require(app.game.rts.tick>paused,"Simulation resumes");main(()->{app.rtsPaused=true;app.save();int tick=app.game.rts.tick;app.restore();require(app.game.rts.tick==tick,"RTS save/restore");app.rtsPaused=false;app.publishRts();});
  RiftWar filter=new RiftWar(0,0,0);JSONObject view=RiftWire.snapshot(filter,0,"test",false);require(view.optJSONArray("units").length()==6,"Hidden enemy entities excluded");RiftWar.Entity scout=filter.spawn(0,RiftWar.SCOUT,28,12,0);RiftWar.Entity enemy=RiftTest.first(filter,1,RiftWar.CORE);enemy.queue.add(0);filter.vision();view=RiftWire.snapshot(filter,0,"test",false);boolean seen=false;for(int i=0;i<view.getJSONArray("units").length();i++){JSONArray unit=view.getJSONArray("units").getJSONArray(i);if(unit.getInt(0)==enemy.id){seen=true;require(unit.getJSONArray(10).length()==0,"Enemy production queue private");}}require(seen,"Scout reveals enemy");scout.hp=0;filter.step();view=RiftWire.snapshot(filter,0,"test",false);for(int i=0;i<view.getJSONArray("units").length();i++)require(view.getJSONArray("units").getJSONArray(i).getInt(1)==0,"Enemy disappears when vision is lost");
  main(()->{app.game.rts.ore[0]=3000;app.game.rts.gas[0]=2000;app.game.rts.spawn(0,RiftWar.FACTORY,11,9,0);app.game.rts.spawn(0,RiftWar.LAB,5,17,0);app.game.rts.spawn(0,RiftWar.AIRPAD,12,17,0);for(int t=1;t<6;t++)app.game.rts.spawn(0,t,11+t*.6f,13,0);app.rtsView.cx=10;app.rtsView.cy=12;app.publishRts();});layout();screen("rift-advanced-fixture");
  main(()->{app.local=false;app.host=true;app.ready=true;app.link.connected=true;app.rtsPeerActive=true;RiftWar.Entity remote=RiftTest.first(app.game.rts,1,0);long id=app.game.rts.lastCommand[1]+1;JSONObject command=MainActivity.obj("type","rts_order","session","stale","command",id,"action",RiftWar.MOVE,"ids",MainActivity.array(new int[]{remote.id}),"unit",0,"x",20,"y",12);app.message(command);require(app.game.rts.lastCommand[1]<id,"Stale session command rejected");try{command.put("session",app.session);}catch(Exception e){throw new RuntimeException(e);}app.message(command);require(app.game.rts.lastCommand[1]==id&&remote.order==RiftWar.MOVE&&remote.goalX==20,"Host routes peer orders to peer-owned units");try{command.put("x",18);}catch(Exception e){throw new RuntimeException(e);}app.message(command);require(remote.goalX==20,"Duplicate peer order rejected");app.rtsPeerActive=false;require(app.rtsIsPaused(),"Peer away pauses host");Game retained=app.game;JSONObject remoteFrame=RiftWire.snapshot(retained.rts,1,app.session,true);app.host=false;app.game=null;app.me=1;app.state=remoteFrame;app.home();app.message(remoteFrame);require(!app.rtsVisible&&!app.inGame,"Background peer snapshots do not reopen a room-paused battle");app.game=retained;app.me=0;app.local=true;app.host=false;app.ready=false;app.link.connected=false;app.rtsPeerActive=false;app.state=app.snapshot(0);app.showRts();app.publishRts();});say("Host command routing, session validation, duplicate rejection and pause gating passed (in-process; not a radio test)");
  RiftWar stress=new RiftWar(0,0,0);for(int side=0;side<2;side++)for(int i=0;i<65;i++){RiftWar.Entity u=stress.spawn(side,i%5+1,side==0?8+i%6:25+i%6,3+i%18,0);u.order=RiftWar.ATTACK;u.goalX=side==0?30:5;u.goalY=12;}long[] duration=new long[300];for(int i=0;i<duration.length;i++){long begin=System.nanoTime();stress.step();duration[i]=System.nanoTime()-begin;}Arrays.sort(duration);int bytes=RiftWire.snapshot(stress,0,"stress",false).toString().getBytes("UTF-8").length;require(bytes<65536,"Snapshot fits transport envelope");say("130-unit stress: p95 simulation tick "+duration[285]/1000000.0+" ms; filtered frame "+bytes+" bytes");require(duration[285]<100000000,"10 Hz tick budget");
  main(()->{for(RiftWar.Entity e:app.game.rts.entities)if(e.side==1&&e.building())e.hp=0;app.game.rts.step();app.game.winner=app.game.rts.winner;app.publishRts();});require(app.game.winner==0,"Victory displayed");layout();screen("rift-victory");main(()->app.home());SystemClock.sleep(600);require(!app.rtsVisible,"Returns to board-game room");say("PASS");
 }catch(Throwable e){say("FAIL: "+e);say(android.util.Log.getStackTraceString(e));}
 finally{if(app!=null){final byte[] prior=saved;final File target=file;final Map<String,?> previous=prefs;main(()->{clean();app.rtsVisible=false;app.rtsView=null;app.rtsPaused=false;app.local=app.solo=false;try{if(target!=null){if(prior!=null)Files.write(target.toPath(),prior);else Files.deleteIfExists(target.toPath());}if(previous!=null){SharedPreferences.Editor edit=app.getSharedPreferences("coach",0).edit().clear();for(Map.Entry<String,?> e:previous.entrySet()){Object v=e.getValue();if(v instanceof String)edit.putString(e.getKey(),(String)v);else if(v instanceof Boolean)edit.putBoolean(e.getKey(),(Boolean)v);else if(v instanceof Integer)edit.putInt(e.getKey(),(Integer)v);}edit.commit();}app.restore();app.home();}catch(Exception e){throw new RuntimeException(e);}});}result.putString("stream",report.toString());finish(report.toString().contains("FAIL:")?Activity.RESULT_CANCELED:Activity.RESULT_OK,result);}
 }
 void layout(){waitForIdleSync();SystemClock.sleep(250);main(()->{noScroll(app.root);require(app.rtsView.field.height()>app.dp(100),"Usable battlefield");for(RiftView.Hit hit:app.rtsView.buttons)require(hit.rect.left>=0&&hit.rect.right<=app.rtsView.getWidth()+1&&hit.rect.bottom<=app.rtsView.getHeight()+1,"HUD fits: "+hit.label);});}
 void world(float x,float y){waitForIdleSync();SystemClock.sleep(200);int[] pos=new int[2];main(()->app.rtsView.getLocationOnScreen(pos));require(app.rtsView.field.contains(app.rtsView.sx(x),app.rtsView.sy(y)),"Test world target in viewport");tap(pos[0]+app.rtsView.sx(x),pos[1]+app.rtsView.sy(y));}
 void control(String prefix){waitForIdleSync();SystemClock.sleep(200);RiftView.Hit chosen=null;for(RiftView.Hit hit:new ArrayList<>(app.rtsView.buttons))if(hit.label.startsWith(prefix)){chosen=hit;break;}require(chosen!=null,"HUD control "+prefix);int[] pos=new int[2];main(()->app.rtsView.getLocationOnScreen(pos));tap(pos[0]+chosen.rect.centerX(),pos[1]+chosen.rect.centerY());}
}
