package com.traillink;
import android.app.*;import android.os.*;import android.content.*;import android.view.*;import org.json.*;import java.util.*;
public final class UpgradeDeviceTests extends DeviceTests {
 @Override public void onStart(){Bundle result=new Bundle();try{Intent intent=new Intent();intent.setClassName("com.traillink","com.traillink.MainActivity");intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);app=(MainActivity)startActivitySync(intent);waitForIdleSync();String mode=args.getString("mode","ui");if(mode.equals("reset")){main(()->{clean();app.local=false;app.chats.clear();app.save();app.home();});screen("v2-final-home");}else if(mode.equals("ui"))upgradeUI();else if(mode.equals("bots"))bots();else if(mode.equals("host")||mode.equals("client"))radio(mode.equals("host"));else if(mode.equals("recover-host")||mode.equals("recover-client"))recover(mode.equals("recover-host"));else if(mode.equals("review"))review();else if(mode.equals("scan"))scan();say("PASS");result.putString("stream",report.toString());finish(Activity.RESULT_OK,result);}catch(Throwable t){say("FAIL: "+t);result.putString("stream",report+"\n"+android.util.Log.getStackTraceString(t));finish(Activity.RESULT_CANCELED,result);}}
 void clean(){app.link.close();app.local=true;app.solo=false;app.ready=false;app.host=false;app.session=UUID.randomUUID().toString();app.savedPeer="";app.game=null;app.state=null;app.analyzing="";}
 void fresh(int id){main(()->{clean();app.game=new Game(id,19);app.me=0;app.showSnapshot();});SystemClock.sleep(250);}
 void upgradeUI()throws Exception{for(int id=0;id<15;id++){fresh(id);screen("v2-"+id);require(app.root.getPaddingLeft()>=app.dp(20)&&app.root.getPaddingRight()>=app.dp(20),"Safe side margins");require((app.getWindow().getAttributes().flags&WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)!=0,"Screen stays awake");if(id==1){int a=app.game.b[60],b=app.game.b[61];cell(60);cell(61);require(app.game.b[60]==b&&app.game.b[61]==a&&app.game.seq==1,"Army swap via touch");main(()->{app.game.move(1,-10,0,0);app.act(-10,0,0);app.showSnapshot();});}else if(id==7){for(int ship=0;ship<5;ship++){final int pick=ship;main(()->app.ship=pick);cell(ship*10);}require(app.game.setupComplete(0),"Manual fleet touch placement");main(()->{app.game.randomSetup(1);app.game.move(1,-10,0,0);app.act(-10,0,0);app.showSnapshot();});screen("v2-battleship-full");}int before=app.game.seq;int[] move=app.game.legal().get(0);if(id==14){require(!clickText("Hold & bank 0"),"Inactive hold hidden");require(clickText("Roll the die"),"Roll button");}else if(id==11){cell(move[0]);require(clickText("Take 1"),"Nim chooser");}else if(id==0||id==1||id==2){cell(move[0]);cell(move[1]);}else cell(move[0]);require(app.game.seq==before+1,"Touch action applied: "+Game.NAMES[id]);say("UI passed: "+Game.NAMES[id]);}main(()->{clean();app.home();});screen("v2-home");}
 void bots()throws Exception{for(int level=0;level<3;level++)for(int id=0;id<15;id++){final int kind=id,difficulty=level;final int[] before={0};main(()->{clean();app.solo=true;app.botLevel=difficulty;app.startGame(kind);if(app.game.setup){app.game.randomSetup(app.me);app.act(-10,0,0);}for(int t=0;t<30&&app.game.turn==app.me&&app.game.winner<0;t++){int[] m=app.game.legal().get(0);app.act(m[0],m[1],5);}before[0]=app.game.seq;});long end=SystemClock.uptimeMillis()+15000;while(SystemClock.uptimeMillis()<end&&app.game.seq==before[0])SystemClock.sleep(100);require(app.game.seq>before[0],"Bot responded: "+Game.NAMES[id]+" "+level);say("Bot response: "+Game.NAMES[id]+" / "+Bot.LEVELS[level]);}main(()->{clean();app.home();});}
 void review()throws Exception{main(()->{clean();app.game=new Game(0,1);app.game.move(0,53,45,5);app.game.move(1,12,28,5);app.game.move(0,54,38,5);app.game.move(1,3,39,5);app.showSnapshot();app.reviewIndex=4;app.review();});long end=SystemClock.uptimeMillis()+25000;while(app.game.analysis.size()<4&&SystemClock.uptimeMillis()<end)SystemClock.sleep(250);require(app.game.analysis.size()==4,"All chess plies analyzed");require(app.game.analysis.get(3).contains("forced mate"),"Mate recommendation");screen("v2-chess-analysis");main(()->{app.save();app.game=null;app.state=null;app.restore();});require(app.game.analysis.size()==4&&app.game.history.size()==5,"Review persisted");say("Chess best-move analysis, navigation, persistence passed");}
 void scan()throws Exception{main(()->{clean();app.local=false;app.devices();});require(app.seen.size()==0,"Bonded offline devices not prepopulated");SystemClock.sleep(18000);screen("v2-nearby-devices");say("Fresh discovery list: "+app.seen.size()+" nearby devices");main(()->app.deviceDialog.dismiss());}

 void playScript(int target)throws Exception{int[] cells={0,3,1,4,2};long end=SystemClock.uptimeMillis()+20000;while(SystemClock.uptimeMillis()<end&&(app.state==null||app.state.optInt("seq")<target)){main(()->{if(app.state!=null&&app.state.optInt("seq")<target&&app.state.optInt("turn")==app.me&&!app.awaiting)app.act(cells[app.state.optInt("seq")],0,5);});SystemClock.sleep(60);}require(app.state!=null&&app.state.optInt("seq")==target,"Script sequence "+target);}
 android.view.View findView(android.view.View v,String text){if(v instanceof android.widget.TextView&&text.equals(((android.widget.TextView)v).getText().toString()))return v;if(v instanceof android.view.ViewGroup){android.view.ViewGroup group=(android.view.ViewGroup)v;for(int i=0;i<group.getChildCount();i++){android.view.View found=findView(group.getChildAt(i),text);if(found!=null)return found;}}return null;}
 void recover(boolean hosting)throws Exception{main(()->{clean();app.local=false;app.host=hosting;if(hosting)app.link.host();else app.link.join(app.adapter.getRemoteDevice(args.getString("address")));});waitConnected();if(hosting)main(()->app.startGame(5));playScript(2);String token=app.session;int side=app.me;
  if(hosting){main(()->{app.ready=false;app.link.close();app.save();app.game=null;app.state=null;app.restore();});SystemClock.sleep(1500);main(()->app.link.host());}
  else{long end=SystemClock.uptimeMillis()+10000;while(connected()&&SystemClock.uptimeMillis()<end)SystemClock.sleep(100);require(!connected(),"Socket loss detected");main(()->{app.save();app.state=null;app.restore();});SystemClock.sleep(2000);main(()->app.link.join(app.adapter.getRemoteDevice(args.getString("address"))));}
  waitConnected();require(app.session.equals(token)&&app.me==side,"Match and random side survived disk reload");if(!hosting){main(()->app.send(MainActivity.obj("type","move","session",token,"seq",-1,"a",8,"z",0,"choice",5)));SystemClock.sleep(250);require(app.state.optInt("seq")==2,"Stale sequence rejected");main(()->app.send(MainActivity.obj("type","move","session","wrong","seq",2,"a",8,"z",0,"choice",5)));SystemClock.sleep(250);require(app.state.optInt("seq")==2,"Wrong session rejected");}else SystemClock.sleep(700);
  playScript(5);require(app.state.optInt("winner")==0,"Resumed match finished");say("Disconnect, save/reload, random sides, stale-message rejection and resumed win passed");
  if(!hosting){main(()->{android.view.View replay=findView(app.root,"Replay · new match");require(replay!=null,"Replay is visible in result UI");replay.performClick();});}
  long end=SystemClock.uptimeMillis()+12000;while(token.equals(app.session)&&SystemClock.uptimeMillis()<end){if(hosting)clickText("Play");SystemClock.sleep(100);}require(!token.equals(app.session)&&app.state.optInt("id")==5&&app.state.optInt("seq")==0,"Guest rematch accepted and reset");say("Guest replay button + host acceptance passed");
  if(hosting){main(()->{app.startGame(0);app.game.move(0,53,45,5);app.game.move(1,12,28,5);app.game.move(0,54,38,5);app.game.move(1,3,39,5);app.showSnapshot();});}
  end=SystemClock.uptimeMillis()+35000;while(SystemClock.uptimeMillis()<end){if(hosting?app.game.analysis.size()==4:app.reviewBoards.length()==5&&app.analysisNotes.length()==5&&!app.analysisNotes.optString(4).isEmpty())break;SystemClock.sleep(100);}
  require(hosting?app.game.analysis.size()==4:app.reviewBoards.length()==5&&app.analysisNotes.optString(4).contains("forced mate"),"Chess engine review transferred");main(()->{app.reviewIndex=4;app.review();});screen(hosting?"v2-bt-analysis-host":"v2-bt-analysis-guest");say("Full chess review + best-move analysis over Bluetooth passed");SystemClock.sleep(1500);
 }

 void radio(boolean hosting)throws Exception{main(()->{clean();app.local=false;app.host=hosting;if(hosting)app.link.host();else app.link.join(app.adapter.getRemoteDevice(args.getString("address")));});waitConnected();main(()->app.sendChat(hosting?"V2 host chat ✓":"V2 guest chat ✓"));long chatEnd=SystemClock.uptimeMillis()+10000;while(app.chats.stream().noneMatch(s->s.contains(hosting?"guest chat":"host chat"))&&SystemClock.uptimeMillis()<chatEnd)SystemClock.sleep(100);require(app.chats.stream().anyMatch(s->s.contains(hosting?"guest chat":"host chat")),"Two-way Bluetooth chat");say("Chat passed");Random random=new Random(95);int[] starters={0,0};
  if(hosting){for(int id=0;id<15;id++){final int kind=id;if(id%2==0){long until=SystemClock.uptimeMillis()+12000;while((app.game==null||app.game.id!=id)&&SystemClock.uptimeMillis()<until){clickText("Play");SystemClock.sleep(100);}}else main(()->app.invite(kind));long until=SystemClock.uptimeMillis()+12000;while((app.game==null||app.game.id!=id)&&SystemClock.uptimeMillis()<until)SystemClock.sleep(100);require(app.game!=null&&app.game.id==id,"Offer/suggestion accepted "+id);starters[app.me]++;int limit=id==1?100:1200;for(int steps=0;steps<limit&&app.game.winner<0;steps++){main(()->{if(app.game.setup&&!app.game.prepared[app.me]){app.game.randomSetup(app.me);app.act(-10,0,0);}else if(!app.game.setup&&app.game.turn==app.me){int[] move=app.game.legal().get(random.nextInt(app.game.legal().size()));app.act(move[0],move[1],5);}});SystemClock.sleep(35);}if(app.game.winner<0){main(()->{app.game.winner=1-app.me;app.game.seq++;app.game.note="Test resignation after gameplay";app.showSnapshot();});}say("Bluetooth "+Game.NAMES[id]+" finished; seq="+app.game.seq+" host side="+app.me);SystemClock.sleep(1600);}require(starters[0]>0&&starters[1]>0,"Both random starting assignments observed");say("Randomized roles: "+Arrays.toString(starters));
  }else{int nextSuggestion=0,finished=0,last=-1;long until=SystemClock.uptimeMillis()+600000;while(finished<15&&SystemClock.uptimeMillis()<until){if(nextSuggestion<15&&(app.state==null||app.state.optInt("winner")>=0)&&app.pendingGame<0&&nextSuggestion%2==0&&(nextSuggestion==0||last==nextSuggestion-1)){final int offer=nextSuggestion;main(()->app.invite(offer));nextSuggestion+=2;}clickText("Play");main(()->{if(app.state==null||app.state.optInt("winner")>=0||app.awaiting)return;if(app.state.optBoolean("setup")&&!app.state.optJSONArray("prepared").optBoolean(app.me)){if(!app.state.optBoolean("canReady"))app.act(-11,0,0);else app.act(-10,0,0);}else if(!app.state.optBoolean("setup")&&app.state.optInt("turn")==app.me){JSONArray moves=app.state.optJSONArray("moves");if(moves.length()>0){JSONArray m=moves.optJSONArray(random.nextInt(moves.length()));app.act(m.optInt(0),m.optInt(1),5);}}});if(app.state!=null&&app.state.optInt("winner")>=0&&app.state.optInt("id")!=last){last=app.state.optInt("id");finished++;say("Guest received result: "+Game.NAMES[last]);}SystemClock.sleep(30);}require(finished==15,"All 15 results received, got "+finished);}
  main(()->app.home());screen(hosting?"v2-connected-host":"v2-connected-guest");
 }
}
