package com.traillink;
import android.app.*;import android.os.*;import android.content.*;import android.view.*;import android.widget.*;import org.json.*;import java.util.*;
public class V3DeviceTests extends DeviceTests {
 @Override public void onStart(){Bundle result=new Bundle();try{Intent intent=new Intent();intent.setClassName("com.traillink","com.traillink.MainActivity");intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);app=(MainActivity)startActivitySync(intent);waitForIdleSync();String mode=args.getString("mode","ui");if(mode.equals("ui"))uiV3();else if(mode.equals("host")||mode.equals("client"))radioV3(mode.equals("host"));else if(mode.equals("reset")){main(()->{clean();app.local=false;app.save();app.home();});}say("PASS");result.putString("stream",report.toString());finish(Activity.RESULT_OK,result);}catch(Throwable t){say("FAIL: "+t);result.putString("stream",report+"\n"+android.util.Log.getStackTraceString(t));finish(Activity.RESULT_CANCELED,result);}}
 void clean(){app.learnMode=false;app.openingLesson=-1;app.link.close();app.local=true;app.solo=false;app.ready=false;app.host=false;app.session=UUID.randomUUID().toString();app.savedPeer="";app.game=null;app.state=null;app.analyzing="";app.fleetDraft=null;app.gameScreen=false;app.reviewing=false;app.chats.clear();}
 void noScroll(View v){require(!(v instanceof ScrollView),"No scrolling containers");if(v instanceof ViewGroup){ViewGroup group=(ViewGroup)v;for(int i=0;i<group.getChildCount();i++)noScroll(group.getChildAt(i));}}
 void fits(){main(()->{noScroll(app.root);if(app.board!=null&&app.board.isAttachedToWindow()){int[] pos=new int[2];app.board.getLocationOnScreen(pos);require(pos[0]>=app.dp(16),"Board side inset");require(app.board.getHeight()>app.dp(140),"Board has usable height");require(pos[1]+app.board.getHeight()<=app.getResources().getDisplayMetrics().heightPixels,"Board fits screen");}});}
 void fresh(int id){main(()->{clean();app.game=new Game(id,19);app.me=0;app.showSnapshot();});SystemClock.sleep(150);}
 void uiV3()throws Exception{V3Test.run();say("V3 rules assertions: "+V3Test.assertions);for(int id=0;id<15;id++){fresh(id);fits();screen("v3-"+id);if(id==1){cell(60);cell(61);require(app.game.seq==1,"Stratego touch swap");main(()->{app.game.move(1,-10,0,0);app.act(-10,0,0);app.showSnapshot();});}else if(id==7){BoardView original=app.board;for(int ship=0;ship<5;ship++){final int pick=ship;main(()->{app.ship=pick;app.updateFleet();});long start=SystemClock.uptimeMillis();cell(ship*10);require(app.board==original,"Placement reuses board");require(SystemClock.uptimeMillis()-start<1500,"Placement responds promptly");}require(app.game.seq==0&&app.fleetDraft.setupComplete(0),"Fleet draft is local and complete");screen("v3-fleet-placed");main(()->{app.game.randomSetup(1);app.game.move(1,-10,0,0);app.lockFleet();});}
 int seq=app.game.seq;int[] move=app.game.legal().get(0);if(id==14)require(clickText("Roll"),"Roll control");else if(id==11){cell(move[0]);require(clickText("Take 1"),"Nim dialog");}else if(id==0||id==1||id==2){cell(move[0]);cell(move[1]);}else if(id==13)cell(40);else cell(move[0]);require(app.game.seq==seq+1,"Touch move "+Game.NAMES[id]);require(!app.game.lastMove.isEmpty(),"Last move recorded");if(id==9){require(app.board.animating(),"Sowing animation runs");screen("v3-mancala-animation");SystemClock.sleep(3200);require(!app.board.animating(),"Animation finishes");}say("No-scroll touch passed: "+Game.NAMES[id]);}
  fresh(13);main(()->{app.act(-3,0,5);app.act(-3,0,5);app.act(-4,0,5);require(app.active()&&!app.game.prepared[app.me],"Second local Go approval reachable");app.act(-4,0,5);require(app.game.winner==1,"Local Go scoring completes");});say("Go pass-and-play approvals passed");main(()->{clean();app.home();});fits();screen("v3-home");for(int page=0;page<3;page++){final int p=page;main(()->{app.libraryPage=p;app.catalog();});fits();screen("v3-library-"+page);}main(()->{clean();app.game=new Game(0,1);app.game.move(0,53,45,5);app.game.move(1,12,28,5);app.game.move(0,54,38,5);app.game.move(1,3,39,5);app.showSnapshot();});long until=SystemClock.uptimeMillis()+20000;while(app.game.analysis.size()<4&&SystemClock.uptimeMillis()<until)SystemClock.sleep(100);require(app.game.analysisBest.size()==4,"Review best-move coordinates");main(()->{app.reviewIndex=4;app.reviewMode=0;app.review();});SystemClock.sleep(200);fits();require(app.board.s.optInt("playedFrom")==3&&app.board.s.optInt("bestTo")==39,"Both review overlays mapped");screen("v3-chess-review");main(()->{app.reviewIndex=3;app.reviewMode=0;app.review();});SystemClock.sleep(150);fits();require(app.board.s.optInt("playedFrom")==54&&app.board.s.optInt("playedTo")==38,"Played g4 overlay");require(app.board.s.optInt("bestFrom")!=54||app.board.s.optInt("bestTo")!=38,"Different recommended move");screen("v3-chess-comparison");main(()->{app.reviewMode=1;app.review();});require(app.board.s.optJSONArray("b").optInt(38)==1&&!app.board.s.has("bestFrom"),"Played mode shows resulting position");main(()->{app.reviewMode=2;app.review();});require(app.board.s.optJSONArray("b").optInt(54)==1&&!app.board.s.has("playedFrom"),"Best mode shows pre-move position");say("Distinct played/best arrows and review modes passed");main(()->{clean();app.local=false;app.save();app.home();});}
 void radioV3(boolean hosting)throws Exception{main(()->{clean();app.local=false;app.host=hosting;if(hosting)app.link.host();else app.link.join(app.adapter.getRemoteDevice(args.getString("address")));});waitConnected();
 if(hosting){main(()->app.startGame(7));long end=SystemClock.uptimeMillis()+15000;while(app.game.setup&&SystemClock.uptimeMillis()<end){main(()->{if(!app.game.prepared[app.me]){app.ensureDraft();app.fleetDraft.randomSetup(0);app.lockFleet();}});SystemClock.sleep(100);}require(!app.game.setup,"Two atomic fleets locked");for(int target=1;target<=4;target++){while(app.game.seq<target+2&&SystemClock.uptimeMillis()<end){main(()->{if(app.game.turn==app.me){int[] m=app.game.legal().get(0);app.act(m[0],0,5);}});SystemClock.sleep(80);}}say("Battleship local setup + real Bluetooth actions: "+app.game.seq);SystemClock.sleep(600);main(()->app.startGame(9));end=SystemClock.uptimeMillis()+15000;while(app.game.seq<2&&SystemClock.uptimeMillis()<end){main(()->{if(app.game.turn==app.me&&app.active()&&!app.board.animating()){int[] m=app.game.legal().get(0);app.act(m[0],0,5);}});SystemClock.sleep(100);}require(app.game.seq>=2,"Mancala moves synchronized");say("Mancala ordered sow path synced");SystemClock.sleep(3500);main(()->app.startGame(13));end=SystemClock.uptimeMillis()+12000;while(app.game.phase==0&&SystemClock.uptimeMillis()<end){main(()->{if(app.game.turn==app.me)app.act(-3,0,5);});SystemClock.sleep(100);}main(()->app.act(-4,0,5));while(app.game.winner<0&&SystemClock.uptimeMillis()<end)SystemClock.sleep(100);require(app.game.winner==1,"Go two-pass scoring + approval sync");say("Go scoring over Bluetooth passed");SystemClock.sleep(1000);main(()->{app.startGame(0);app.game.move(0,53,45,5);app.game.move(1,12,28,5);app.game.move(0,54,38,5);app.game.move(1,3,39,5);app.showSnapshot();});end=SystemClock.uptimeMillis()+25000;while(app.game.analysisBest.size()<4&&SystemClock.uptimeMillis()<end)SystemClock.sleep(100);SystemClock.sleep(2000);}
 else{int finished=0;long end=SystemClock.uptimeMillis()+90000;while(SystemClock.uptimeMillis()<end){main(()->{if(app.state==null||app.awaiting)return;int id=app.state.optInt("id");if(id==7){if(app.state.optBoolean("setup")&&!app.state.optJSONArray("prepared").optBoolean(app.me)){app.ensureDraft();app.fleetDraft.randomSetup(0);app.lockFleet();}else if(app.active()){JSONArray moves=app.state.optJSONArray("moves");if(moves.length()>0)app.act(moves.optJSONArray(0).optInt(0),0,5);}}else if(id==9&&app.active()&&!app.board.animating()){JSONArray moves=app.state.optJSONArray("moves");if(moves.length()>0)app.act(moves.optJSONArray(0).optInt(0),0,5);}else if(id==13&&app.active()){app.act(app.state.optInt("phase")==1?-4:-3,0,5);}});if(app.state!=null&&app.state.optInt("id")==0&&app.reviewBest.length()==5&&app.reviewBest.optJSONArray(4)!=null&&app.reviewBest.optJSONArray(4).optInt(1,-1)==39){finished=1;break;}SystemClock.sleep(100);}require(finished==1,"Guest received SAN and best-move board coordinates");say("Guest fleet / sow / Go / chess overlays received");}
 main(()->{app.reviewIndex=4;app.reviewMode=0;app.review();});screen(hosting?"v3-bt-review-host":"v3-bt-review-client");}
}
