package com.traillink;
import java.util.*;
public final class V3Test {
 static int assertions;static void check(boolean ok,String what){assertions++;if(!ok)throw new AssertionError(what);}
 static Game blank(int id){Game g=new Game(id,7);Arrays.fill(g.b,0);g.setup=false;return g;}
 public static void main(String[] args){run();System.out.println("V3 PASS: "+assertions);}
 public static void run(){Game g=new Game(0,1);check(ChessNotation.san(g,52,36,5).equals("e4"),"SAN pawn");check(ChessNotation.san(g,62,45,5).equals("Nf3"),"SAN knight");g=blank(0);g.b[60]=6;g.b[4]=-6;g.b[63]=4;check(ChessNotation.san(g,60,62,5).equals("O-O"),"SAN castle");g=blank(0);g.b[60]=6;g.b[4]=-6;g.b[57]=2;g.b[61]=2;check(ChessNotation.san(g,57,51,5).equals("Nbd2"),"SAN file disambiguation");g=blank(0);g.b[60]=6;g.b[7]=-6;g.b[8]=1;check(ChessNotation.san(g,8,0,5).equals("a8=Q+"),"SAN promotion check");g=new Game(0,1);g.move(0,53,45,5);g.move(1,12,28,5);g.move(0,54,38,5);check(ChessNotation.san(g,3,39,5).equals("Qh4#"),"SAN checkmate");g.move(1,3,39,5);String report=new ChessAnalysis(2000).analyze(ChessAnalysis.position(g,3),g.chessMoves.get(3));check(report.contains("Best found: Qh4#"),"Analysis SAN");
  g=new Game(9,1);check(g.move(0,2,0,5),"Mancala sow");check(Arrays.equals(g.sowPath,new int[]{3,4,5,6}),"Ordered sow animation");check(g.beforeMove[2]==4&&g.b[2]==0&&g.b[6]==1,"Sow before/after");check(g.lastA==2&&g.lastPlayer==0&&!g.lastMove.isEmpty(),"Last move metadata");
  g=new Game(7,1);Game draft=new Game(7,2);draft.randomSetup(0);int[] layout=Arrays.copyOf(draft.b,100);check(g.applyFleet(0,layout),"Atomic fleet upload");check(g.prepared[0]&&g.setup,"Fleet lock waits for other");check(!g.applyFleet(0,layout),"Cannot replace locked fleet");Game bad=new Game(7,1);layout[0]=9;check(!bad.applyFleet(0,layout),"Fleet input validated");
  g=blank(13);g.b[10]=-1;g.b[1]=g.b[9]=g.b[11]=1;check(g.move(0,19,0,5)&&g.b[10]==0&&g.count[0]==1,"Go captures group");g=blank(13);g.b[1]=g.b[9]=g.b[11]=g.b[19]=-1;check(!g.move(0,10,0,5),"Go suicide rejected");g=blank(13);int[] after=g.b.clone();after[40]=1;g.goPositions.add(Game.goKey(after));check(!g.move(0,40,0,5),"Go superko rejected");g=new Game(13,2);check(g.n==9&&g.legal().size()==82,"Go opening 81 points + pass");check(g.move(0,-3,0,5)&&g.move(1,-3,0,5)&&g.phase==1,"Two passes enter scoring");check(g.move(0,-4,0,5)&&g.winner<0&&g.move(1,-4,0,5)&&g.winner==1,"Agreed komi scoring");g=blank(13);g.b[0]=1;g.b[80]=-1;g.phase=1;check(g.move(0,0,0,5)&&g.aux[0]==1,"Mark dead group");check(g.move(1,-4,0,5)&&g.prepared[1],"Approval tracked");check(g.move(0,0,0,5)&&!g.prepared[1],"Mark change clears approvals");check(g.move(1,-5,0,5)&&g.phase==0&&g.aux[0]==0,"Disputed score resumes play");
  for(int id=0;id<15;id++){g=new Game(id,3);if(g.setup)for(int p=0;p<2;p++){g.randomSetup(p);g.move(p,-10,0,0);}int[] move=g.legal().get(0);check(g.move(g.turn,move[0],move[1],5)&&!g.lastMove.isEmpty(),"Last move all games: "+Game.NAMES[id]);}for(int level=0;level<3;level++){g=new Game(13,19);Bot bot=new Bot(level,1);for(int i=0;i<12&&g.phase==0;i++){int[] move=bot.choose(g,g.turn);check(move!=null&&g.move(g.turn,move[0],move[1],5),"Go bot legal level "+level);}}
 }
}
